### ISSUE TITLE
Multi-stack parser

### ISSUE THREAD

**Issue by isagalaev** [highlightjs/highlight.js#1140]
## Problem

[Source](http://softwaremaniacs.org/blog/2014/07/26/highlight-js-what-next/en/):

> Our current syntax can't express things defined as a sequence of other things, like this:
> 
> ```
> function ::= <title> '=' <params> '->' <body>
> ```
> 
> The problem here is that you don't know that you're in a function definition until you get to the -> symbol. Our parser can start a new parsing mode based only on a single starting lexeme: an opening quote, a keyword, a number, etc.
> 
> To work around that we use a horrible kludge:
> 1. Match the whole body of the mode with a single regex.
> 2. Start a new mode at the beginning of the matched string.
> 3. Return the whole thing back to the parser.
> 4. Parse it again, by the rules of the new mode.
> 
> Not only it's ugly, it also works only when we're lucky that the whole body can actually be parsed by a regex.
## Solution design

We need to implement a "multi-stack" parser: instead of keeping track of a single stack of parsing modes the parser should be able to keep multiple stacks representing alternative parsing strategies to which it can go back if the current stack dead-ends for some reason. This effectively becomes a tree:

```
                                      stacks
                                      +----+
[root]---[ ]---[ ]---[ ]---[top]  <---|    |
          |           |               +----+
          |           +---[x]     <---|    | 
          |                           +----+
          +---[x]                 <---|    |
          |                           +----+
          +---[x]                 <---|    |
                                      +----+
```

This is an inverted tree with the `stacks` array keeping references to alternative parsing strategies (stacks) with each mode having a reference to its parent.

The topmost (or the rightmost) branch is the only long one and it represents the current alternative being parsed. Every other branch is exactly one level deep — a lead node representing a point from which to restart parsing if the current branch fails.

Operations:

**Discover**: upon finding lexemes (one or more) opening new possible modes add them to the beginning of the `stacks` array in the order they're defined. The old `top` is updated with the current index in the source so we could parse farther if all new strategies fail. `stacks[0]` becomes the new `top`.

**Cancel**: upon finding a canceling condition remove `top` from `stacks`, set `top` to the next available stack. If `stacks` is empty, treat as we currently do illegals — drop parsing.

**Commit**: if the mode successfully reaches its `end` lexeme, it is removed from the `top` stack and `stacks` is cleaned up from any items pointing to that mode
## Syntax

Current idea is to have something like this: 

``` js
var PARAMS = {
  className: 'params',
  begin: /\(/, end: /\)/,
  contains: [...]
}

var FUNCTION = {
  className: 'function',
  is: [hljs.TITLE_MODE, PARAMS, /=>/]
}
```

Where `is` array is a syntactic sugar for something like this:

``` js
{
  className: 'title',
  starts: {
    cancel: /\S/,
    contains: [
      {
        className: 'params',
        begin: /\(/, end: /\)/,
        starts: {
          cacncel: /\S/,
          contains: [
            {
              begin: /=>/, relevance: 0
            }
          ]
        }
      }
    ]
  }
}
```

It's pretty obvious why we need some syntactic sugar for this :-)

`cancel` is a new attribute, similar to the current `illegal` with the exception that it only cancels the current parsing strategy, not the whole thing.

More syntactic sugar:
- Treat literal strings as keyword lists: `'a b c'` ⇒ `{className: 'keyword', begin: /\b(a|b|c)\b/}`
- Treat literal regexes as lexemes: `/=>/` ⇒ `{begin: /=>/, relevance: 0}`
## Simplifications

Unless I'm very much mistaken, implementing all this will allow us to drop `returnBegin`, `returnEnd` and also `beginKeywords` and make the whole definition syntax less convoluted. Fingers crossed :-)

---

This is a work in progress…

**Comment by tajmone** [comment]
I agree that using `returnBegin` and `returnEnd` is not most elegant, but usually the syntax parser is built a with specific linear approach in mind. I'm trying to envisage your new proposal applied to markdown, for example, which is reknown to present some hard-to-deal with edge cases (especially if the document is not well formated, or if uses "lazy" syntax instead of a cleaned up one).

Even PEG parsers have to resort to hacks to handle properly Markdown.

Will this new approach allow coders to mentally trace what actually goes on? Often, when writing my first syntax file, I'd realize that build failed (without error reports, just failed to build). So I would know that something wasn't right in the code, and I'd start to go through it mentally, tracing steps and looking for bugs.

Is this stack going to make "mental debugging" more complex? Are there risks of infinite loops and/or recursiveness? Presently, restorting to `returnBegin` and `returnEnd` is a precise strategy that one adopts when there is a clear picture in mind of what the limits are — and even though it isn't the most elegant approach, it's still quite linear.

Are there going to be some means to log the new parsing process, and trace what failed where and when? with some references to the stack states?

These considerations aside (it's difficoult to imagine the changes it will bring without having the code to play with), it seems that it would expand the parsing power of hjs — after all, the limits is proposes to address are significant ones, not trival.

Is it going to make parsing more resources-demanding? time consuming? or is it going to slim down execution times?

**Comment by yyyc514** [comment]
Some food for thought here:

```js
var CLASS = {
  className: 'class',
  keywords: "class extends",
  is: [/class/, TITLE_MODE, /extends with/, TITLE_MODE, /{/]
}
```

This looks reasonable but what is the scope of those keywords? The "flat" nature of is makes me want to assume this would "just work", but do `keywords` always get inherited? Do they only get inserted for static regex matches?

And how do I do a variant?

```js
var CLASS = {
  className: 'class',
  keywords: "class extends",
  variants: [
    {is: [/class/, TITLE_MODE, /extends with/, TITLE_MODE, /{/] },
    {is: [/class/, TITLE_MODE, /{/] }
  ]
}
```

**Comment by yyyc514** [comment]
And purely talking syntax I'd like to consider functions also:

```js
var CLASS = {
  className: 'class',
  keywords: "class extends",
  match: is([/class/, TITLE_MODE, /extends with/, TITLE_MODE, /{/], {allowSpaceBetween: true})
}
```

**Comment by yyyc514** [comment]
I really wonder if you couldn't just hack this by making highlight take a MODE (not a language name) and then just calling itself recursively and just let the JS stack manage all the messy state. ie:

```js
// inside main loop
while (...) {
 if (top.contains) {
   // pursue matches as usual
 } else if (top.is) {
     let restOfCode = ...
     let result = _highlight(restOfCode, {using: top.is})
     trimAfterLastMatch(result) 
     if (result.illegal) {
       // failed match
     } else {
       emitter.addTree(result.emitter)
       lastIndex += result.matchSize
     }
   }
}
```

But actually you have to deal with how do you start an is match in the first place... it's probably going to be precipitated by an actual match of a `begin` expression, probably the first "block" of the chain.  You could have a quick auto-returnBegin though... so that when it hit a mode that had an `is` it returned the content and then entered that mode... so the next iteration would be running the `is` branch shown above.

**Comment by yyyc514** [comment]
Then the question becomes is writing (and maintaining) (and having grammar writers) reason about the `is` to insane super complex ruleset better than just expanding the parser to actually have some time of true/real sequencing mode when it just jumps from one mode to another in a linear fashion rather than trying to find one of many possibilities.

**Comment by isagalaev** [comment]
(Just a heads-up, I've seen your messages but haven't got to actually reading through them and understanding :-) )

**Comment by isagalaev** [comment]
> Some food for thought here:
>
>     var CLASS = {
>       className: 'class',
>       keywords: "class extends",
>       is: [/class/, TITLE_MODE, { begin: /extends|uses/ }, TITLE_MODE, /{/]
> }
>
> This looks reasonable but what is the scope of those keywords?

Re-reading my own description (at the end, in "syntactic sugar") I think there wouldn't be a need to specify `keywords` in the parent mode. Any literal string inside `is` will be considered a keyword, or a list of them with some reasonable separator (initially I thought space separated, but a `|` is probably more familiar). So:
```js
var CLASS = {
  className: 'class',
  is: ['class', TITLE_MODE, 'extends|uses', TITLE_MODE, /{/]
}
```
> And purely talking syntax I'd like to consider functions also:

I actually wanted to move away from anything executable in language definitions. Eventually I wanted to provide dedicated syntax for everything case where language definitions currently use JavaScript, so they would become inert data. It just makes everything simpler. There wasn't any refactoring plan for that, it was more like a general gravitational pull to keep in mind when making any changes to the grammar: less imperative, more declarative.

> I really wonder if you couldn't just hack this by making highlight take a MODE (not a language name) and then just calling itself recursively and just let the JS stack manage all the messy state. 

Interesting :-) It should be theoretically equivalent to my original proposal with keeping stacks explicitly. And I can't predict which one of the ways will turn out to be easier.

> But actually you have to deal with how do you start an is match in the first place... it's probably going to be precipitated by an actual match of a begin expression, probably the first "block" of the chain. You could have a quick auto-returnBegin though... 

I really wanted to get rid of `returnBegin`… This is why I imagined `is` as a syntactic sugar expanding to `starts` with the first mode in the chain. This is incompatible with the recursion though… I really don't know :-)

> Then the question becomes is writing (and maintaining) (and having grammar writers) reason about the is to insane super complex ruleset better than just expanding the parser to actually have some time of true/real sequencing mode when it just jumps from one mode to another in a linear fashion rather than trying to find one of many possibilities.

Well, the whole problem is that you can't parse some languages linearly. Like, in C++ when a function definition can starts with arbitrary identifier, and it's not until you hit the parentheses of the argument list you even know what it was.

I don't think it's going to be hard to reason about for grammar authors. It's a simple pattern-matching idea: either this entire chain of modes matches or it doesn't. You don't need to know how it's implemented under the hood.
