### ISSUE TITLE
Getting r instead of relevance 

### ISSUE THREAD

**Issue by onilton** [highlightjs/highlight.js#1215]
The docs describe the some functions return an object with the attribute `relevance` as in

http://highlightjs.readthedocs.io/en/latest/api.html#highlight-name-value-ignore-illegals-continuation

But using the last version of highlight.js seems to return `r` instead of `relevance`

http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js

If you search the minified file you can verify this.

You will find `language:`, `value:` and `top:` but you won't find `relevance:`

**Comment by sourrust** [comment]
Thanks for reporting this. It is now fixed in master

**Comment by isagalaev** [comment]
This is a really old wart of our custom compression scheme, and because of that I suspect we may break some code in the wild that depends on `.r` in a compressed build rather than `.relevance`. I'll revert it for 9.5.0 since it would've been a breaking change.

Going forward I see two ways of dealing with the problem:

- document `.r` for compressed builds
- remove compression for the identifier `relevance` altogether

The former is easier and I'd say pretty reasonable. And I don't like the hack with `['relevance']` in some places but not others as it feels too fragile…

Thoughts?

**Comment by yyyc514** [comment]
I don't have enough context to know if this is still a relevant issue or not? Anyone else have any ideas?

**Comment by yyyc514** [comment]
> remove compression for the identifier relevance altogether

Easy enough, doing that.
