### ISSUE TITLE
(cpp) decltype(auto) preceded by specifiers

### ISSUE THREAD

**Issue by Arcoth** [highlightjs/highlight.js#1222]
If `constexpr decltype(auto)` occurs in C++(14) code, `decltype` is not highlighted correctly, presumably since this looks like a function declaration with `decltype` being the name. This will also occur with other specifiers, e.g. `friend`, `typedef`, `inline` etc.

In fact, this can occur with keywords other than `decltype`. See e.g. 

```
#define X
X new (p) int;
```

I'd suggest dropping that heuristic entirely.

**Comment by yyyc514** [comment]
Is this still an issue?

Wouldn't it also be resolved by simply excluding keywords from IDENT_RE so that a keyword would never count as the name of a function?   I assume there is no way to name a function a reserved keyword, correct?

**Comment by yyyc514** [comment]
This is worth thought because the parser by default doesn't look for keywords first, it looks for "language constructs" (other parser rules) and then in-between those it will highlight any keywords.  So the problem here is we first find a "function" and then we highlight it so we're looking for a title, not a keyword.

I wonder if this could be fixed with negative look-ahead, which is what I was hinting at.

I presume we "like" the ability to highlight function titles and that losing that would be a pretty big loss.

Can you provide a little more context regarding what `constexpr decltype(auto)` looks like in context of an actual C++ file?

**Comment by yyyc514** [comment]
```
#define X
X new (p) int;
```

We're never going to be able to handle all edge cases involving pre-processing directives - since we don't have access to the actual source - only the raw source.

**Comment by yyyc514** [comment]
@Arcoth Default arguments exist in C++, so couldn't one use ternary when defining a default argument?  So wouldn't `?` actually be valid?  Might fixing that help here even if the highlighter itself was still a little confused?

**Comment by yyyc514** [comment]
> This will also occur with other specifiers, e.g. friend, typedef, inline etc.

As far as I can tell these just work, the only real issue is with auto type.

After my PR:

<img width="519" alt="Screen Shot 2019-12-23 at 5 43 02 PM" src="https://user-images.githubusercontent.com/6473/71383738-b1274e80-25ab-11ea-9380-d29e3f85c887.png">

**Comment by yyyc514** [comment]
@Arcoth Does that look right to you?
