### ISSUE TITLE
(sql) remove vendor specific SQL keywords (they can live in their own grammars)

### ISSUE THREAD

**Issue by andrestaht** [highlightjs/highlight.js#1274]
Currently [sql.js](https://github.com/isagalaev/highlight.js/blob/master/src/languages/sql.js) keywords consist of different types of SQL keywords (SQL, [PostgreSQL](https://github.com/isagalaev/highlight.js/commit/42d6ba4b133b1b5f2c87115e8f0e1bddcc735b07#diff-73a3218e3423e943035e7c4f6aa04122), [Oracle](https://github.com/isagalaev/highlight.js/commit/c915a19a00c83901f4d741d072d946b7a9c435a2#diff-73a3218e3423e943035e7c4f6aa04122) etc).
Lets extract them (PostgreSQL, Oracle) into separate languages because it is causing issues when using standard SQL.

**Comment by Sannis** [comment]
@andrestaht can you post some code examples?

**Comment by Kirill** [comment]
Example MS SQL. After PRINT highlight break
![2017-02-26 20_39_20](https://cloud.githubusercontent.com/assets/302940/23342485/c6637cb6-fc63-11e6-8a9a-5b1daf6001a8.png)

```sql
USE db_main;
GO
SET NOCOUNT ON;

-- Rebuild or reorganize indexes based on their fragmentation levels
DECLARE @work_to_do TABLE (
    objectid int
    , indexid int
    , pagedensity float
    , fragmentation float
    , numrows int
)

DECLARE @objectid int;
DECLARE @indexid int;
DECLARE @schemaname nvarchar(130); 
DECLARE @objectname nvarchar(130); 
DECLARE @indexname nvarchar(130); 
DECLARE @numrows int
DECLARE @density float;
DECLARE @fragmentation float;
DECLARE @command nvarchar(4000); 
DECLARE @fillfactorset bit
DECLARE @numpages int

-- Select indexes that need to be defragmented based on the following
-- * Page density is low
-- * External fragmentation is high in relation to index size
PRINT 'Estimating fragmentation: Begin. ' + convert(nvarchar, getdate(), 121) 
INSERT @work_to_do
SELECT
    f.object_id
    , index_id
    , avg_page_space_used_in_percent
    , avg_fragmentation_in_percent
    , record_count
FROM 
    sys.dm_db_index_physical_stats (DB_ID(), NULL, NULL , NULL, 'SAMPLED') AS f
WHERE
    (f.avg_page_space_used_in_percent < 85.0 and f.avg_page_space_used_in_percent/100.0 * page_count < page_count - 1)
    or (f.page_count > 50 and f.avg_fragmentation_in_percent > 15.0)
    or (f.page_count > 10 and f.avg_fragmentation_in_percent > 80.0)

PRINT 'Number of indexes to rebuild: ' + cast(@@ROWCOUNT as nvarchar(20))

PRINT 'Estimating fragmentation: End. ' + convert(nvarchar, getdate(), 121)

SELECT @numpages = sum(ps.used_page_count)
FROM
    @work_to_do AS fi
    INNER JOIN sys.indexes AS i ON fi.objectid = i.object_id and fi.indexid = i.index_id
    INNER JOIN sys.dm_db_partition_stats AS ps on i.object_id = ps.object_id and i.index_id = ps.index_id

-- Declare the cursor for the list of indexes to be processed.
DECLARE curIndexes CURSOR FOR SELECT * FROM @work_to_do

-- Open the cursor.
OPEN curIndexes

-- Loop through the indexes
WHILE (1=1)
BEGIN
    FETCH NEXT FROM curIndexes
    INTO @objectid, @indexid, @density, @fragmentation, @numrows;
    IF @@FETCH_STATUS < 0 BREAK;

    SELECT 
        @objectname = QUOTENAME(o.name)
        , @schemaname = QUOTENAME(s.name)
    FROM 
        sys.objects AS o
        INNER JOIN sys.schemas as s ON s.schema_id = o.schema_id
    WHERE 
        o.object_id = @objectid;

    SELECT 
        @indexname = QUOTENAME(name)
        , @fillfactorset = CASE fill_factor WHEN 0 THEN 0 ELSE 1 END
    FROM 
        sys.indexes
    WHERE
        object_id = @objectid AND index_id = @indexid;

    IF ((@density BETWEEN 75.0 AND 85.0) AND @fillfactorset = 1) OR (@fragmentation < 30.0)
        SET @command = N'ALTER INDEX ' + @indexname + N' ON ' + @schemaname + N'.' + @objectname + N' REORGANIZE';
    ELSE IF @numrows >= 5000 AND @fillfactorset = 0
        SET @command = N'ALTER INDEX ' + @indexname + N' ON ' + @schemaname + N'.' + @objectname + N' REBUILD WITH (FILLFACTOR = 90)';
    ELSE
        SET @command = N'ALTER INDEX ' + @indexname + N' ON ' + @schemaname + N'.' + @objectname + N' REBUILD';
    PRINT convert(nvarchar, getdate(), 121) + N' Executing: ' + @command;
    EXEC (@command);
    PRINT convert(nvarchar, getdate(), 121) + N' Done.';
END

-- Close and deallocate the cursor.
CLOSE curIndexes;
DEALLOCATE curIndexes;


IF EXISTS (SELECT * FROM @work_to_do)
BEGIN
    PRINT 'Estimated number of pages in fragmented indexes: ' + cast(@numpages as nvarchar(20))
    SELECT @numpages = @numpages - sum(ps.used_page_count)
    FROM
        @work_to_do AS fi
        INNER JOIN sys.indexes AS i ON fi.objectid = i.object_id and fi.indexid = i.index_id
        INNER JOIN sys.dm_db_partition_stats AS ps on i.object_id = ps.object_id and i.index_id = ps.index_id

    PRINT 'Estimated number of pages freed: ' + cast(@numpages as nvarchar(20))
END
GO


--Update all statistics
PRINT 'Updating all statistics.' + convert(nvarchar, getdate(), 121) 
EXEC sp_updatestats
PRINT 'Done updating statistics.' + convert(nvarchar, getdate(), 121) 
GO
```

**Comment by DavidSimner** [comment]
For Microsoft SQL Server's Transact-SQL (T-SQL), it is extracted into its own language in https://github.com/isagalaev/highlight.js/pull/1524

**Comment by yyyc514** [comment]
What is the definition of "standard SQL"?

**Comment by egor-rogov** [comment]
> Lets extract them (PostgreSQL, Oracle) into separate languages because it is causing issues when using standard SQL.

That's a good idea. We've already done that with PostgreSQL; let's try to revive MSSQL PR.
Then we should be able to remove vendor specifics from the SQL.

> What is the definition of "standard SQL"?

Standard SQL is defined in the SQL Standard (:

**Comment by yyyc514** [comment]
Perhaps helpful:

https://blog.ansi.org/2018/10/sql-standard-iso-iec-9075-2016-ansi-x3-135/

**Comment by yyyc514** [comment]
And the PR mentioned earlier: https://github.com/highlightjs/highlight.js/pull/1524

**Comment by yyyc514** [comment]
Since we already have `TSQ` and `pgsql` I think we'd be open to a PR that removes all/most of the vendor specific keywords to slim this down.  Renaming this to reflect the goal.

**Comment by yyyc514** [comment]
> Since we already have TSQ and pgsql I think we'd be open to a PR that removes all/most of the vendor specific keywords to slim this down. Renaming this to reflect the goal.

Rather than removing keywords here one at a time (which would be a lot of work  - and likely means this becomes a zombie issue):

- **Remove `sql` completely.**  If it's not sufficient enough to be "generally useful" then it shouldn't exist and people should instead simply use the proper SQL variant grammar.
- **Start over with a very simple grammar** Start from an entirely clean slate. I'd then start by adding whatever the internet seems to agree are "common" SQL keywords, functions, datatypes... and I wouldn't be too shy about adding datatypes from various DBs. 

The latter would result in a "generally useful" SQL grammar that could be used with many SQL snippets and probably get us 90% there (while still being a tiny grammar)... then if someone didn't find that sufficient they could be pointed to one of the other more specific grammars.

As/if requests come in to add to the simple grammar they will be evaluated with the criteria "generally useful/common" SQL...

Reference:

- https://www.w3schools.com/sql/sql_datatypes.asp
- http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/sql/sql_functions.asp.html
- https://www.w3schools.com/sql/sql_ref_keywords.asp

I would look at resources other than w3schools, but this is a rough idea of the type of "general" things I'd add to the new grammar.

**Comment by yyyc514** [comment]
@egor-rogov If you're ok with the plan I'll slim this down and make a PR.

**Comment by yyyc514** [comment]
@andrestaht 

> because it is causing issues when using standard SQL.

Can you elaborate on this?  What actual issues was it causing?

**Comment by egor-rogov** [comment]
> Start over with a very simple grammar

Hm. Our SQL grammar is pretty simple right now. A lot of keywords is what makes it big.

I can see a lot or Oracle-isms in the grammar which you'll certainly loose if you start from scratch (and we don't have a separate Oracle grammar). Probably there are also something from other databases.

That's why I'm very fond of the idea. For me a safer (but harder) way is to identify and remove PostgreSQL and MSSQL specifics (as we already have separate grammars for them). And then repeat the exercise every time a new grammar appears.

**Comment by yyyc514** [comment]
> A lot of keywords is what makes it big.

Right, and that was the original reason this issue was filed.  The new grammar would have only a fraction of the keywords.  When I said simpler I meant it as in "less surface area, fewer keywords" not that the rules were complex now.

> I can see a lot or Oracle-isms in the grammar which you'll certainly loose if you start from scratch (and we don't have a separate Oracle grammar).

I think that is a separate problem.  Either this grammar is meant to cover everything or it's not.  I don't think the fact that we lack an Oracle grammar should prevent us from fixing the SQL grammar and closing out this issue.

>  For me a safer (but harder) way is to identify and remove PostgreSQL and MSSQL specifics (as we already have separate grammars for them). And then repeat the exercise every time a new grammar appears.

**Except that will never get done.** This issue dates back to 2016.  The solution I'm recommending closes this out with a very minimal investment in time - one I'm willing to make.  _Lack of Oracle support will either not be missed or will hopefully encourage someone to create the missing 3rd party Oracle SQL grammar._

If there is any real fear of "breaking" Oracle support I say let that fall under the version 10 umbrella of breaking changes.

**Comment by egor-rogov** [comment]
Honestly I don't see a real problem behind this issue. The original request wasn't illustrated by any example. The only provided example was MSSQL code, for which we have T-SQL grammar.
So I inclined to see this issue as something that is good to be done, but not urgent. Maybe I'll find some time to make a revision of keywords later. It is way better to me than to simply break existing highlighting.

**Comment by yyyc514** [comment]
> Honestly I don't see a real problem behind this issue. The original request wasn't illustrated by any example

I'm going to close this then.  The original specific problem (as stated here) is vague and the requested solution is honestly asking for 3rd party languages to be created - which isn't something we track here in the issue tracker in any case.

>  For me a safer (but harder) way is to identify and remove PostgreSQL and MSSQL specifics (as we already have separate grammars for them). And then repeat the exercise every time a new grammar appears.

I do understand your thinking on this, but at the same time find it very strange - that our core decisions about grammars should be influenced by which 3rd party grammars are available. It seems to tether/limit us in a very strange way to the 3rd party support.

If there truly was a real problem with the SQL grammar (it sounds like perhaps there is not, hence closing the issue) then I'd think our fixing it shouldn't be based on which 3rd party grammars do or do not exist.

Just food for thought.
