### ISSUE TITLE
Add ANTLR grammar

### ISSUE THREAD

**Issue by KvanTTT** [highlightjs/highlight.js#1290]
Should be like this (from ANTLR Idea plugin):

![antlr syntax highlight](https://cloud.githubusercontent.com/assets/1150330/9064293/8475bae6-3ad4-11e5-8b52-84d74dfe2b80.png)

**Comment by isagalaev** [comment]
To clarify: are you volunteering to implement it?

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

**Comment by KvanTTT** [comment]
> Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I don't think that issues with undefined periods are a problem. But it's your repository and your rules.

**Comment by yyyc514** [comment]
It’s not just the undefined period. We have many actual bugs that we will likely leave open until fixed. It’s really more about the fact that core doesn’t generally write the grammars so the odds of this ever being completed (unless you find a champion yourself) is very, very low.
