### ISSUE TITLE
How to highlight like VSCode

### ISSUE THREAD

**Issue by katopz** [highlightjs/highlight.js#1372]
Hi,

How can I highlight like I saw in VSCode? 
I mean `<`... `>` and also `{`...`}` (and maybe other bracket too) should render other color Is that possible?
![hilight](https://cloud.githubusercontent.com/assets/97060/20782212/495c3f50-b7bc-11e6-96d9-d819d69685dd.png)

Thanks

**Comment by yyyc514** [comment]
You'd have to write your own syntax parser (or look for one someone else has written).  It's been the core policy that (in general) Highlight.js built-in languages purposely do NOT highlight punctuation, operators, etc...

@marcoscaceres Do you know WHY that's the policy?  Ease of maintenance?  Style preference?  Legacy, ie, the fact that we don't have classes defined for those things, etc.?

**Comment by marcoscaceres** [comment]
I don't think there is a policy reason... we are basically free to do whatever. It's more user expectation.

**Comment by yyyc514** [comment]
> How can I highlight like I saw in VSCode?

@katopz Were you wanting to do the work and make a PR for better HTML colorizing?  Or was it really more of a "I wish they were nicer" type of question? :-)

Sure, it'd be nice if everything looked prettier, but the problem is usually finding people who want to make it their passion to put in the time to enhance the grammars to support that (and also not bloat them to a huge degree).

Also there is the problem that our themes only support so many types of content (see the docs)... so just add a new class of item like "html tag bracket" and then updating ALL the themes to support that is a big task.

I'm not sure we'd want a world where the parser is incredible but you can only tell if you use these 10 approved picture perfect themes. 

Complex problems. :)

**Comment by yyyc514** [comment]
VS Code is open source, so theoretically you could use it's highlighting engine instead, but I bet that's not such a simple task, and I wouldn't be surprised if it's 10x larger (or worse) than ours.

**Comment by katopz** [comment]
It's more like yes/no question ;) I will close this issue beause I already got answer. Thanks!

**Comment by yyyc514** [comment]
Ok, awesome!
