### ISSUE TITLE
JSX grammar cannot process self-closing tags properly

### ISSUE THREAD

**Issue by MayconDionisio** [highlightjs/highlight.js#1383]
before version 9.2 this code is completely highlighted. After this version the code isn't highlighted after CustomSidebar.

```js
import React from "react";
import ReactDOM from "react-dom";

class App extends React.Component {

  getCustomSidebar(props) {
    return <CustomSidebar {...props} />
  }

  render() {
    return (
      <MegadraftEditor
        editorState={this.state.editorState}
        onChange={this.onChange}
        sidebarRendererFn={this.getCustomSidebar}/>
    )
  }
}
```

**Comment by RileySpiller** [comment]
I would suggest importing Highlight.js and adding a React lifecycle method, such as `componentDidMount()` to tell the highlighter to do it's thing. 

```
import React from "react";
import ReactDOM from "react-dom";
import highlight from 'highlight.js';

class App extends React.Component {
  componentDidMount {
    highlight.initHighlighting();
  }

  getCustomSidebar(props) {
    return <CustomSidebar {...props} />
  }

  render() {
    return (
      <MegadraftEditor
        editorState={this.state.editorState}
        onChange={this.onChange}
        sidebarRendererFn={this.getCustomSidebar}/>
    )
  }
}

**Comment by yyyc514** [comment]
I've suggested elsewhere that long-term we need a JSX/React repository with it's own maintainers vs keeping this as part of "javascript"... that said this is due to the fact that currently we don't support self-closing tags.  If you add a closing tag you'll see it highlights correctly.

If someone wants to take a swing at a PR you want to focus on:

https://github.com/highlightjs/highlight.js/blob/master/src/languages/javascript.js#L155

**Comment by yyyc514** [comment]
Closing this [as a dup] in favor of https://github.com/highlightjs/highlight.js/issues/1915 as there is a lot more history and discussion there.
