### ISSUE TITLE
auto detection not working (need to use class which makes box looking ugly)

### ISSUE THREAD

**Issue by Devrandomuser** [highlightjs/highlight.js#1397]
Using this code inside my html:

       <pre>
	&lt;?php
	echo "You've received: ";
	?></pre>

Requires me to use `<code class="php">` so my code looks like this:

	<pre><code class="php">
	&lt;?php
	echo "You've received: ";
	?></code></pre>

Because of this extra class now my design doesn't look well, there's a border around the pre itself.
Here you can see this: [here](https://puu.sh/t8Urn/de02086706.png).
Please fix the auto detection regarding this, so I won't have to use `<code class="php">` anymore.

**Comment by jeffreydwalter** [comment]
I'm also seeing pretty vanilla php being detected as python. :/

**Comment by yyyc514** [comment]
Sadly, auto detection is something that's simply impossible to get right all the time (especially for small snippets).  There is an issue open (needing a PR) so that you could do something like:

```
<pre class="php"></pre>
```

An avoid the code block, but right now yes you need both in order to assign the language (which is the best way to guarantee accurate results).
