### ISSUE TITLE
Classes `hljs-attribute` vs `hljs-attr` mismatch

### ISSUE THREAD

**Issue by feimosi** [highlightjs/highlight.js#1472]
`highlight.js` used to append `hljs-attribute` class in the past, but now it's `hljs-attr`. Unfortunately styles are not updated to match that. I've spotted it after migrating from 8.1 to 9.10.
See
https://github.com/isagalaev/highlight.js/blob/master/src/languages/xml.js#L14
and
https://github.com/isagalaev/highlight.js/blob/master/src/styles/tomorrow-night.css#L37

**Comment by isagalaev** [comment]
There was a huge [overhaul of the style rules][#348] for 9.0, and the change you're describing is an intentional decision. We now have [both `attr` and `attribute`][ref] with slightly different semantics, and attribute names within XML tags get the "less important" `attr` which is not highlighted in many styles by choice.

Having said that, if you want to advocate Tomorrow in particular should have a different color for "attr", we should pick a color that doesn't break other usages of this class name in [crmsh fix gcode haml htmlbars ini javascript languages nix puppet xml yaml].

[#348]: https://github.com/isagalaev/highlight.js/issues/348
[ref]: http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html

**Comment by feimosi** [comment]
Well, I didn't know that, but still I reported the issue because styling after the update is worse for my HTML snippets.

For comaprison, here's how it used to look like:
![image](https://cloud.githubusercontent.com/assets/5721520/23826389/8ce45306-069b-11e7-9c76-137fcb28b5cd.png)
Here's how the new Tomorrow-Night looks like:
![image](https://cloud.githubusercontent.com/assets/5721520/23826372/5119fce0-069b-11e7-9360-2ef9e40450e4.png)

If we just change the CSS rule to use `hljs-attr` instead of  `hljs-attribute`, we can achieve:
![image](https://cloud.githubusercontent.com/assets/5721520/23826410/ce737aa4-069b-11e7-8609-fa168edf05d5.png)
Note: on this example I also 'fixed' `< >`

**Comment by yyyc514** [comment]
Closing this:

- It was an intentional change.
- It has received very little discussion (so most must be ok with the change or not care)
- Adjusting the CSS is always a fairly easy possibility.

Trying to clear out old issues.

**Comment by rstudner** [comment]
I'm seeing this happening in 11.6.0 still.

I have 2 yaml blocks on a page, one gets hljs-attribute and the other gets hljs-attr

Is this right :)?
