### ISSUE TITLE
Request: Add Panda grammar

### ISSUE THREAD

**Issue by sydev** [highlightjs/highlight.js#1485]
Panda syntax is a nice editor theme. Have a look: http://panda.siamak.work/.
A highlight.js panda style would be nice.

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
