### ISSUE TITLE
sql.js is missing foreign keyword

### ISSUE THREAD

**Issue by ben3005** [highlightjs/highlight.js#1488]
Self explanatory really, the sql.js file is missing foreign as a keyword so it doesn't get highlighted.

Removed in [this commit](https://github.com/isagalaev/highlight.js/commit/00685a0ba2b5d1aaa98237294ef57734a978d40b#diff-73a3218e3423e943035e7c4f6aa04122L63)

**Comment by DavidSimner** [comment]
For Microsoft SQL Server's Transact-SQL (T-SQL), `foreign` is added as a keyword in https://github.com/isagalaev/highlight.js/pull/1524

**Comment by yyyc514** [comment]
I pinging the commit asking if the removal was intentional for some reason:

https://github.com/highlightjs/highlight.js/commit/00685a0ba2b5d1aaa98237294ef57734a978d40b#diff-73a3218e3423e943035e7c4f6aa04122L63

If not I can't see why we wouldn't accept a PR to add it back if you wanted to submit one.

**Comment by egor-rogov** [comment]
It was fixed in #1564

**Comment by yyyc514** [comment]
Well, hahaha, I didn't even check if someone already put it back.  Thanks!
