### ISSUE TITLE
(Rust) Grammar doesn't recognize macro matchers

### ISSUE THREAD

**Issue by moonheart08** [highlightjs/highlight.js#1499]
- 'mut' is being highlighted like a type
- '&' is not being highlighted at all, but it probably should be.
- Doesnt recognize macro matchers (i.e. $abc:xyz and $abc)

I may or may not submit a PR patch for a thing or two, but dont count on it

**Comment by isagalaev** [comment]
> 'mut' is being highlighted like a type

Highlighted like a keyword for me (and the code says the same). My guess would be the language was misdetected in your example…

> &' is not being highlighted at all, but it probably should be.

No, it's intentional. We don't highlight punctuation normally.

> Doesnt recognize macro matchers (i.e. $abc:xyz and $abc)

Can't suggest off the top of my head which class name to use to highlight them… But if you'll ever find time to tackle it, feel free to submit a PR!

**Comment by yyyc514** [comment]
@moonheart08 Can you provide some examples of macro matchers in the real world?  Is the second half limited to the fragment specifiers such as `item`, `block`, etc?

Do you have a suggestion for how to classify them?

**Comment by moonheart08** [comment]
Yikes, 2 years ago. I don't even remember what I filed this issue _for_

**Comment by yyyc514** [comment]
Well do you want to provide some examples, or do we close the issue? :)

**Comment by moonheart08** [comment]
Close issue. I forgot it existed.
