### ISSUE TITLE
Request: URL highlighting

### ISSUE THREAD

**Issue by Klooven** [highlightjs/highlight.js#1599]
It would be good to have this feature for example in API documentations.

The variables in the URL (comes after the `?` in the URL), would have some color and the values of these would maybe have an other color.

Example:

![image](https://user-images.githubusercontent.com/12278148/30063407-4c6e509a-9257-11e7-8997-92698b693b20.png)

The colors would of course be determined by the theme used.

**Comment by yyyc514** [comment]
Which syntaxes are you suggesting support this?

**Comment by yyyc514** [comment]
Ping.

**Comment by yyyc514** [comment]
This sounds like more of perhaps a custom theme for highlighting URLs for me... I think in general purpose documentation I'd not sure I would always want the individual parts of the URL colored different ways (hence thinking this would be a custom theme).  

Also we don't really have classes for this... You could maybe use string and variable, but then a URL is really often highlighted as a string itself... so that's one issue.

If someone wanted to work on this as say a new theme that was an extension to markdown (or other documentation type themes) that might be nice.

Closing this because of age and inactivity. And it's not really obvious how we'd fit this into the package as it currently stands.

**Comment by yyyc514** [comment]
It's also possible someone could build this functionality as a plug-in running on TOP of Highlight.js... Let highlight.js highlight the code first, then your plugin could go back thru and highlight the URLs however it wanted, adding extra classes, etc.

**Comment by hracik** [comment]
I would like to have option like this, I need to display URLs and explain users how to setup tracking on their account and I am showing there URLs which we call, some with custom named parameters. Our URLs itself can contain lot of paramaters and would be great to see parameter, value pairs highlighted instead of one color multiline long URL address. Would be much easier to understand without additional explanations.

For example:
https://youxube.com?campaign=0&commission=8.4250&metrics%5Blanguage%5D%5Bname%5D=English&metrics%5Blanguage%5D%5Bcode%5D=en&metrics%5Bdevice%5D%5Bname%5D=desktop&metrics%5Bdevice%5D%5Bcode%5D=desktop&metrics%5Bbrowser%5D%5Bname%5D=Chrome&metrics%5Bbrowser%5D%5Bcode%5D=chrome&metrics%5BbrowserFamily%5D%5Bname%5D=Chrome&metrics%5BbrowserFamily%5D%5Bcode%5D=chrome&metrics%5BoperatingSystem%5D%5Bname%5D=Windows&metrics%5BoperatingSystem%5D%5Bcode%5D=windows&metrics%5BoperatingSystemFamily%5D%5Bname%5D=Windows&metrics%5BoperatingSystemFamily%5D%5Bcode%5D=windows&metrics%5BoperatingSystemVersion%5D%5Bname%5D=Windows+10&metrics%5BoperatingSystemVersion%5D%5Bcode%5D=windows_10

**Comment by Ircama** [comment]
This could be a simple mode to highlight an URL with the [default style](https://github.com/highlightjs/highlight.js/blob/main/src/styles/default.css):

```javascript
hljs.registerLanguage('url', function() {
  return {
    case_insensitive: true,
    contains: [
        {
            className: "code", // color #397300
            begin: /(https?|ftp|file):\/\//,
            end: /(?=(\/|\?))/
        },
        {
            className: "symbol", // color #ab5656
            begin: /(?<=((https?|ftp|file):\/\/[^\/]+)\/)[^?]+/,
        },
        {
            className: "literal", // color #695
            begin: /(?<=[?&])[^=?&]+/,
        },
        {
            className: "meta", // color #1f7199
            begin: /(?<=\=)[^=?&]+/,
        }
    ],
  }
});
```

Markdown:

````
```url
http://api.someservice.io/dothis?dothat=sayhello&message=goodbye
```
````

**Comment by Ircama** [comment]
Some examples:

````
```url
# General tests
http://127.0.0.1/dothis?dothat=sayhello&message=goodbye
http://api.someservice.io/path1/path2/dothis?dothat=sayhello&message=goodbye
http
http:
http://
http://test
http://test/
http://test:8000
http://test@authority
http://test@authority:8000
http://test/this
http://test/this/
http://api.someservice.io/dothis?dothat=sayhello&message=goodbye
http://api.someservice.io:8001/dothis?dothat=sayhello&message=goodbye
http://api.someservice.io@www.example.com/dothis?dothat=sayhello&message=goodbye
http://api.someservice.io@www.example.com:8001/dothis?dothat=sayhello&message=goodbye
https://www.google.com/maps/place/Duomo+di+Milano/@45.4641013,9.1897378,17z/data=!4m5!3m4!1s0x4786c6aec34636a1:0xab7f4e27101a2e13!8m2!3d45.4640976!4d9.1919265
http://2790524771?_x_tr_sl=en&amp;_x_tr_tl=it&amp;_x_tr_hl=it&amp;_x_tr_pto=sc
https://www.complex.org/blog/urls.html?_x_tr_sl=en&_x_tr_tl=it&_x_tr_hl=it&_x_tr_pto=sc

# Other tests
http://api.someservice.io/dothis?dothat=sayhello&message=goodbye
https://vumbnail.com/W2EMHNhyEnQ.jpg
https://vumbnail.com/youtube/W2EMHNhyEnQ.jpg
https://vumbnail.com:3000/W2EMHNhyEnQ_word_with-dash.jpg?query=string&object[property]=value&object.property=value
https://canary.vumbnail.com:3000/W2EMHNhyEnQ_word_with-dash.jpg?query=string&object[property]=value&object.property=value
```
````

![tests](https://user-images.githubusercontent.com/8292987/201782593-592f3cfc-f904-425b-a8a9-d29dbbd52ed2.png)

**Comment by ZmotriN** [comment]
That's really cool, but some iOS browsers between iPhone 11 and iPhone 14 doesn't support the lookbehind (?<=).

**Comment by joshgoebel** [comment]
Safari is VERY late to the party on supporting this (iOS 16.4 and up support it), and we've waiting a long time for them.  Everyone else has had this support for years.  Starting with version 12 we'll be allowing look-behind into the core library... those needing to support these older OSes will need to continue to use v11.
