### ISSUE TITLE
Request: Add Agda grammar

### ISSUE THREAD

**Issue by jonaprieto** [highlightjs/highlight.js#1626]
Since I'm using [Shiba](https://github.com/rhysd/Shiba) app to help me previewing my README files for Github, I noted that it does not support Agda syntax, something that Github syntax highlighting does. Agda syntax is pretty much based on Haskell syntax. 

Blocking: https://github.com/rhysd/Shiba/issues/39
CC'ing @rhysd

**Comment by yyyc514** [comment]
Anyone would be welcome to add support for this.  Currently we're encouraging languages live in their own repositories... so anyone can do this.  If someone steps up to maintain it we're happy to let the repository live at `highlightjs` organization.

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
