### ISSUE TITLE
there wiil be an error when es6 template mixed with img tag 

### ISSUE THREAD

**Issue by lessfish** [highlightjs/highlight.js#1630]
code like this:

```html
<pre>
  <code class="js">
    $.get(api, res => {
      if (!res.status && !Array.isArray(res.data)) {
          let tpl = `
              <a href="${res.data.url}">
                  <img class="live-recommend-img" src="${res.data.bannerUrl}" width=255 height=80 />
              </a>
          `
          $('#live-recommend').html(tpl)
          $('#live-recommend-wrapper').removeClass('hidden')
      }
    })
  </code>
</pre>
```

the result will be:

![github](https://user-images.githubusercontent.com/10890665/32528683-56d900b2-c46f-11e7-9a4e-87857f29eb09.png)

another question if it's ok, what's the difference between this one and the [shim one](https://github.com/components/highlightjs)?

**Comment by yyyc514** [comment]
If you just include HTML inside your <code> tags it will be treated as HTML.  That's just how the browser works (try it without Highlight.js) - and Highlight.js preserves such HTML when it's present - because sometimes you can do useful things with it, like add extra highlights or hover overs, etc.  You'll need to properly HTML escape any "raw" content you want inside the code tag that you don't want the browser interpreting as HTML.

Ie:

```
&lt;img class=&quot;...
```
