### ISSUE TITLE
Request: Add language for Regex

### ISSUE THREAD

**Issue by ttimasdf** [highlightjs/highlight.js#1633]
We extensively used regex but did not have syntax highlight for it..

**Comment by yyyc514** [comment]
No, but someone would be welcome to create a syntax for it.  We're preferring external repositories now for new languages... so all this needs is a maintainer and someone to build it and then we'd be happy to setup a `highlightjs/highlightjs-regex` GitHub repo just to help make it easier for people to find the language.

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
