### ISSUE TITLE
Request: Add YOPTASCRIPT grammar

### ISSUE THREAD

**Issue by Zekfad** [highlightjs/highlight.js#1655]
Site: https://yopta.space/
Example:
```
гыы gop внатуре пиздишь, lt нах

куку йопта law()  жЫ
    вилкойвглаз(gop типа нечотко)  жЫ
        ксива.малява("Я и правда язык") нах
        gop сука чотко нах
     есть  иливжопураз  жЫ
        gop сука чотко нах
        потрещим(semki чоблясука трулио)  жЫ
            lt сука ксива.вычислитьЛохаПоНомеру("list") нах
            ебало.шухер("Привет, йопта") нах
         есть
     есть
 есть
```

**Comment by HawkeyePierce89** [comment]
чёт проиграл в голосину

**Comment by Zekfad** [comment]
Ну, а хули нет. Пусть будет. :)

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
