### ISSUE TITLE
Add Perl 6 support

### ISSUE THREAD

**Issue by sumanstats** [highlightjs/highlight.js#1674]
Hi there,

What is the status of [Perl 6](https://perl6.org/) support in `highlight.js` package?

Is it planned?
`Perl 6` is a mature production ready language and would love to see this library support it.

**Comment by kawaii** [comment]
+1 for Perl 6 support.

**Comment by yyyc514** [comment]
Is anyone volunteering to write the syntax for it and maintain it?  That's all we need to get the ball rolling now that languages are simply external repos.

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

If someone steps up to the plate it'd be great to have a Perl 6 grammar! :-)

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

**Comment by finanalyst** [comment]
I'm willing to start the ball rolling.
I've put in a separate request for a repo.

**Comment by ggoebel** [comment]
finanalys: not sure if joshgoebel will see this as he has marked it closed
