### ISSUE TITLE
colouring an inline block?

### ISSUE THREAD

**Issue by shawaj** [highlightjs/highlight.js#1699]
hi there,

Have got this working great using just a big block using:
```
hljs.initHighlightingOnLoad();
```

but now I am trying to get it so that big blocks of text inside `<pre><code>` tags highlight in a block, but that smaller blocks of text (single lines) will highlight inline using `<p><code>` tags or just code tags.

So far I have tried
```
<script>
for (i in document.getElementsByTagName("code")) {
  console.log(document.getElementsByTagName("code")[i]);
};
      hljs.initHighlightingOnLoad();
    </script>
```

But not had much luck. Can anyone point me in the right direction?

**Comment by yyyc514** [comment]
`init` will only run the very first time... you need to look at the source of init and do something similar:

```
function initHighlighting() {
    if (initHighlighting.called)
      return;
    initHighlighting.called = true;

    var blocks = document.querySelectorAll('pre code');
    ArrayProto.forEach.call(blocks, highlightBlock);
  }
```

Notably the last two lines.  Be careful though as there are no protections now to prevent blocks from being highlighted over and over (if you ask it to) which could bloat the pages HTML and memory usage.

Does that help?

**Comment by yyyc514** [comment]
Quite possibly related:

https://github.com/highlightjs/highlight.js/issues/2019

One could imagine that being allow to pass an array also - but then I think the problem is dealing with code tags both outside and include pre blocks... I guess you could keep track of which ones you already colored and then the ordering would be:

---

Closing this as asked and answered (clearing out old issues).  If you have any other questions feel free to ask!
