### ISSUE TITLE
Highlight (interpolated or not) bash variables 

### ISSUE THREAD

**Issue by codebymikey** [highlightjs/highlight.js#1727]
Variables (interpolated within string quotes or not) should be highlighted like this otherwise they blend in with the rest of the string - a good example of good syntax highlighting is from PHPStorm:

![image](https://user-images.githubusercontent.com/9484406/38610505-fbdc1928-3d78-11e8-85fe-7ba0aa7dde54.png)

compared to the current (Dracula theme) one:

![image](https://user-images.githubusercontent.com/9484406/38610668-71ee21e2-3d79-11e8-870e-bd186241f299.png)

**Comment by yyyc514** [comment]
Currently Highlight.js does not highlight variables on purpose.  In the past this has been philosophical, not sure what it is now or if it might be changing.  I'm closing this as a dup in favor of https://github.com/highlightjs/highlight.js/issues/1732 though. My personal feeling is we should let each community decide for themselves, but that first requires breaking out the grammars into separate ones and then finding people in said communities willing to take on responsibility for the maintenance of said grammars.

Also some languages are *technically* easier to highlight than others because of how they name variables... PHP being a great example of that.

If you'd like to weigh in on the value of highlighting variables and the bigger discussion please do so on that thread (and I'll rename it to be a bit more generic).
