### ISSUE TITLE
(cpp) types with an underscore aren't recognized as the start of a function

### ISSUE THREAD

**Issue by cppcooper** [highlightjs/highlight.js#1730]
Take for example the following code.
```cpp
    int8_t Get_Tile_Value()
    {
        return ( ( *Region & bitmask ) >> bit_position );
    }
```
If `int8_t` is a recognized type (a la `<script>hljs.getLanguage('cpp').keyword += '  int8_t';</script>`), highlight.js will recognize it and highlight it, but will not highlight the function name.

**Comment by yyyc514** [comment]
```
      {
        className: 'function',
        begin: '(' + hljs.IDENT_RE + '[\\*&\\s]+)+' + FUNCTION_TITLE,
```

I think this is because we don't consider that IDENT_RE can include `_`... types without _ work just fine... really CPP probably needs a TYPE_NAME_RE that we use here instead of the more generic IDENT_RE which is used in a zillion places.

Switching to that and allowing it to match _ in the name would likely fix this.  Would you be up to contributing a PR?

**Comment by yyyc514** [comment]
> If int8_t is a recognized type

We don't really recognize types themselves (other than very basic ones)...

**Comment by yyyc514** [comment]
Ha, spoke too soon:

```js
  var CPP_PRIMITIVE_TYPES = {
    className: 'keyword',
    begin: '\\b[a-z\\d_]*_t\\b'
  };
```

We recognize `_t` names as  types.

**Comment by cppcooper** [comment]
It will quite possibly be years before I swing back around to working with this project. I'm open to contributing, but it is about 12th in line.

**Comment by yyyc514** [comment]
Well I tagged it if someone comes along and wants to help contribute.
