### ISSUE TITLE
Give up on AUTHORS.ru.txt?

### ISSUE THREAD

**Issue by isagalaev** [highlightjs/highlight.js#1761]
The existence of this file is a carry over from the times when <s>dinosaurs roamed</s> the library was being developed by a local community. It remained as a kind of a funny quirk contributing to the projects's lore and not requiring too much hassle. However with me <s>out</s> being much less hands on, it's in danger of becoming hard to maintain, as all other active maintainers don't write in Russian.

So, should we give up on this tradition?

**Comment by gusbemacbe** [comment]
You have put it because you and other "old" maintainers with Russian names and family names are Russians, but since you invited new maintainers who are not Russian-speaking and one of members is American, we think we must discard it. Your official site and Highlight.js developer guide site do not have Russian version. 

I am Brazilian and not Russian-speaking, I added Ahmad's name in Russian and suggested him to add to AUTHOR.ru because I am studying Russian and Ukrainian.

**Comment by ldct** [comment]
+1 to deleting this file
