### ISSUE TITLE
Add Windows/DOS Batch file grammar

### ISSUE THREAD

**Issue by DaemonPhenex** [highlightjs/highlight.js#1801]
I reported an issue of this not being present with https://github.com/hackjutsu/Lepton 
Response:
![ntsretn](https://user-images.githubusercontent.com/36192863/44335754-418ad780-a42a-11e8-9158-d31bd8252ed7.PNG)

**Comment by yyyc514** [comment]
Does Powershell count?

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see Idris, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests

**Comment by JamesTheAwesomeDude** [comment]
For anyone who's considering contributing this, here's an MIT-licensed grammar description you can <s>steal</s> *base yours off of*:  
https://github.com/microsoft/vscode-textmate/blob/975e2e3fad39172a3081d4004ccf56a4f9485297/test-cases/themes/syntaxes/Batch%20File.tmLanguage

It looks like that file is the grammar [Sublime used](https://forum.sublimetext.com/t/comments-in-batch-files/9863), which was then [harvested by Ace](https://github.com/ajaxorg/ace/blob/v1.32.3/src/mode/batchfile_highlight_rules.js#L1), which is what's [used by Linguist](https://github.com/github-linguist/linguist/blob/v7.28.0/lib/linguist/languages.yml#L528), which is [what Github uses](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)&hellip; so it'll probably be at least a "serviceable" starting point
