### ISSUE TITLE
(csharp) generic base class not handled

### ISSUE THREAD

**Issue by onionhammer** [highlightjs/highlight.js#1852]
Doesnt work:

```c#
public class ListOfStates : Seed<DataSeedTestContext>
{ }
```

Works
```c#
public class ListOfStates : Seed
{ }
```

**Comment by yyyc514** [comment]
Is this still an issue?  Is so could you create a quick jsfiddle with a working example?

A quick template you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/

I think this is because <> aren't currently allowed  in a class declaration... would this be a problem for namespaces also, or just classes?

**Comment by yyyc514** [comment]
Weekend ping.

**Comment by onionhammer** [comment]
It appears to work now

https://jsfiddle.net/L1ysbh6c/

**Comment by yyyc514** [comment]
Awesome.  Thanks.
