### ISSUE TITLE
Readme not contains actual working and screenshots

### ISSUE THREAD

**Issue by laal-patte** [highlightjs/highlight.js#1922]
What exactly is meant by highlighting code, maybe include some screenshots/working to show working of highlightjs

**Comment by hawezo** [comment]
I don't know what's wrong with what you tried, but the readme contains clear explanations on what is the purpose of the library.

> Highlight.js is a syntax highlighter written in JavaScript.

Highlighting means emphasizing something. In this case, it means centering attention on important keywords that are part of a code. For example, the word `function` will be highlighted in PHP because it is an important keyword.

The code in the readme does work as well, I tested it. I'm not sure the screenshots are necessary in the readme, but if you really wanted to see some working examples, there are plenty on the [library's website](https://highlightjs.org/static/demo/) (which is [indicated in the readme](https://github.com/highlightjs/highlight.js#links), by the way).
