### ISSUE TITLE
Add Idris language

### ISSUE THREAD

**Issue by Kazark** [highlightjs/highlight.js#1937]
[Idris](https://www.idris-lang.org/) is already supported by GitHub's Linguist, as you can see at the [Idris repo](https://github.com/idris-lang/idris-dev) itself. [Here](https://github.com/idris-hackers/idris-sublime/tree/4268aefba37457de01c14a3f2c23107af6c9e269) is the syntax highlighting plugin for Sublime, in case that's useful. The [syntax guide](http://docs.idris-lang.org/en/latest/reference/syntax-guide.html) is also relevant.

Idris's community is growing; version 2 is on the way, and there is already books about it. In short, worth supporting.

**Comment by yyyc514** [comment]
> Idris's community is growing; version 2 is on the way, and there is already books about it. In short, worth supporting.

Sounds like it, but the core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see Idris, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
