### ISSUE TITLE
(javascript) syntax highlighter is confused by regexp literals

### ISSUE THREAD

**Issue by paladox** [highlightjs/highlight.js#1962]
js like:

```js
      hash += (hash === '#' ? '' : '&').replace(
          /(^#|&)test=[^&]*(&test=[^&]*)*&?/g,
          '$1') + 'test=' + encodeURIComponent(testName);
```

is not correctly being highlighted under highlight.js see https://chromium-review.googlesource.com/c/chromium/src/+/594890/22/third_party/WebKit/LayoutTests/external/wpt/async_cookies/resources/testharness-helpers.js#35 (line 35) and see bug report at https://bugs.chromium.org/p/gerrit/issues/detail?id=7296

**Comment by rehmsen** [comment]
I looked into this a bit, and I believe the underlying issue is the newline:

highlight.js allows partial highlighting by returning the `top` of the current mode stack, and accepting a `continuation` parameter to keep going where one left off [1].

Gerrit (which powers the link @paladox provided) and possibly others rely on this and apply highlighting line by line. This is useful if one does not want the highlighting markup to mess with other markup around the line such as line numbers or diff/coverage markers. 

Picking a simpler example, that also fails to highlight for us:
```
var x = 
    /\w+/;
```

If this is passed to highlightjs as a whole, it works like a charm (I tried it locally).

However, Gerrit effectively passes the two lines into `highlight` separately [2]:
```
result = highlightjs.highlight('js', 'var x =', true);
result = highlightjs.highlight('js', '  /\w+/;', true, result.top);
```

which fails in the following way:

On the first call, highlightjs get into the value mode [3] (as it should), but then tries to match that modes terminators here [4], which, because the JS language does not define `end`, defaults to `\b|\B` [5]. Now `\b` matches the end of the string `'var x='`, and so highlightjs pops that mode off the stack, and the first invokation of highlight actually return with `top` set to the top-level JS mode. 

Now the second call goes in, but highlight.js' JS mode does not match top-level regexps - they are only matched in value mode [6]. And so it ends up ignoring the first characters, then finds the `+` which puts it into value mode, then finds the second `/` which puts it in regexp mode, and messes up the highlighting of everything that follows.

The exact same problem occurs for TypeScript.

A very simple fix for this issue (but I still need to verify if it breaks anything else) is to set `endsWithParent` in the value mode, which will cause it to not default to `\b|\B`, and makes it not break out of value mode after the end of the first call, and then parses everything just fine

I will try to add some tests for this, make the change and send a PR - let me know if you think that is the wrong fix.

[1] https://highlightjs.readthedocs.io/en/latest/api.html#highlight-name-value-ignore-illegals-continuation
[2] https://gerrit.googlesource.com/gerrit/+/refs/heads/master/polygerrit-ui/app/elements/diff/gr-syntax-layer/gr-syntax-layer.js#354
[3] https://github.com/highlightjs/highlight.js/blob/master/src/languages/javascript.js#L92
[4] https://github.com/highlightjs/highlight.js/blob/master/src/highlight.js#L578
[5] https://github.com/highlightjs/highlight.js/blob/master/src/highlight.js#L334
[6] https://github.com/highlightjs/highlight.js/blob/master/src/languages/javascript.js#L98

**Comment by yyyc514** [comment]
An actual jsfiddle (preferred) or screen capture showing what is happening or not happening in the case here could be great.

Quick template:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by yyyc514** [comment]
Telling the diff between / (division) and regex is a thorny issue though, quite a few issues regarding that.

**Comment by rehmsen** [comment]
Here is a fiddle: https://jsfiddle.net/nmeqhxav/12/

Highlighting the same regexp with line break at once works, line-by-line it does not.

**Comment by yyyc514** [comment]
Closing this as a dup of: https://github.com/highlightjs/highlight.js/issues/2050
