### ISSUE TITLE
(cpp) constructor does not support initializers

### ISSUE THREAD

**Issue by SF-Zhou** [highlightjs/highlight.js#1980]
```js
highlight('c++', 'void Do() {}').value
// ''<span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-title">Do</span><span class="hljs-params">()</span> </span>{}', highlight OK

highlight('c++', 'A(): a(10) {}').value
// 'A(): a(<span class="hljs-number">10</span>) {}', only highlight number

highlight('c++', 'explicit A(): a(10) {}').value
// 'explicit A(): a(10) {}', not highlight
```

**Comment by yyyc514** [comment]
The current behavior is different but still not "correct" I'd say.  This is because "initializer expressions" (not sure what the correct term is) aren't currently supported by the syntax...

So we really have no idea what all the `: a(10)` stuff is about... so that would need to be added.

**Comment by yyyc514** [comment]
Can someone provide more complex examples of this or is it really always just a simpler string or number literal that would be passed?

**Comment by joshgoebel** [comment]
@klmr Probably also some LHF (although I'm probably not familiar with ALL the variants here).  I had a simple fix for this long ago but dunno where it went.

**Comment by klmr** [comment]
Ouch. This looks like another C++ syntax induced nightmare. :-(

**Comment by joshgoebel** [comment]
Right now it's only broken because we use illegal to flag certain characters... which is a HARD stop if it hits once of the illegals .... so it might not be as ugly as you think - remember you don't have to parse it all.  Just removing illegal would "fix" it, but illegals help the auto-detect so these things are always worth taking a closer look to see if there is an "in-between" solution.
