### ISSUE TITLE
install 9.15.x fail workaround

### ISSUE THREAD

**Issue by tvkit** [highlightjs/highlight.js#1992]
Apologies for posting this "workaround" as in issue, but it helped me to get past the recently reported 9.15.x npm install failures. Figured it might be helpful to share. The related threads, #1984 & #1986, are currently locked; otherwise, I would have posted there.

Basically, I just pulled the latest from the master repo:

`npm install https://github.com/highlightjs/highlight.js.git --save-dev`

To grab a specific working commit (e.g., 9.15.4)

`npm install  https://github.com/highlightjs/highlight.js/archive/bb1e500b75436eed4d905a0283ff8ec0002faab5.tar.gz --save-dev`

Details on grabbing a specific commit @ [SO](https://stackoverflow.com/a/49081254/241296)

**Comment by MarcGodard** [comment]
I agree with the guy about depending on open source projects and businesses to some degree, but this also breaks a lot of other hobbyists' projects (like mine). Also, not sure what the lesson is for businesses, most that I have worked for DO contribute a lot of open source code that many other open source projects depend on. The way I see it, business and open source work well together in the node / javascript space and I feel they mostly help each other out. To think otherwise is maybe a lack of experience, or at the very least the lack of good experiences.

**Comment by marcoscaceres** [comment]
Thanks @tvkit, appreciate it you posting a workaround. I just pushed v9.15.5 - and it seems to get things working again.
