### ISSUE TITLE
Request: Add TypoScript and FLUID grammars

### ISSUE THREAD

**Issue by AKaravas** [highlightjs/highlight.js#2030]
I was wondering if you could add TypoScript and Fluid on your framework. I am creating an extension for TYPO3 and it would be nice to have the syntax for TYPO3 too.

**Comment by marcoscaceres** [comment]
Hi @AKaravas, unfortunately, we are a little bit under-resourced to add new languages so we rely on the community for help. If you have links to the language definitions, that would be really helpful... can usually find an existing language to base off.

**Comment by DanielSiepmann** [comment]
Fluid is basically HTML with additional inline syntax. I'm not aware of any definition. The Templates are parsed with RegEx (https://github.com/TYPO3/Fluid). This is the official documentation regarding Syntax of Fluid: https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_SYNTAX.md

Regarding TypoScript: Someone already created a highlighter for pygments, this is used on docs.typo3.org: https://github.com/TYPO3-Documentation/Pygments-TypoScript-Lexer/ Poorly this is a bit out of date. The new import and condition syntax is not covered, as far as I know. Same might be valid for some keywords.

**Comment by yyyc514** [comment]
Repeating a bit of what Macro already said...

The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is all up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

---

Rather than leave these issues open to languish forever (as we have in the past) we're going to start closing them (to clean up the issues list).

I've moved this request to the wish list:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
