### ISSUE TITLE
When the language is set to lua and sql, some lua syntax highlighting is invalid.

### ISSUE THREAD

**Issue by AmazingMoon** [highlightjs/highlight.js#2036]
`highlightAuto(code, ['lua', 'sql']).value`

Some lua syntax highlighting is invalid.

**Comment by yyyc514** [comment]
Closing this issue because no specific examples are provided (when means we couldn't really even look into it even if we wanted to).  Also: Auto-detection is "best effort" only. It won't always be correct, and that's expected.

If you have a PR or specific ideas of how to improve the auto-detection for these two languages we'd love to hear them, but otherwise we can't do much with this type of issue.

If you need 100% correct highlighting in all cases, you need to manually tell Highlight.js the proper language for each block of code as documented in the docs.
