### ISSUE TITLE
(toml) Add support for TOML arrays

### ISSUE THREAD

**Issue by marcinx** [highlightjs/highlight.js#2063]
Hi Team,

TOML currently handles this case correctly

```
moo=["foo"]
```

but highlighting is not applied when multiple values are present in the array, e.g.

```
KNOWN_PEERS = [
    "finland.some-host.com:11625",
    "germany.some-host.com:11625",
    "hongkong.some-host.com:11625",
]
```

Thanks for your help!

**Comment by yyyc514** [comment]
Example:

https://jsfiddle.net/fx6byraw/1/

The problem is we don't support arrays at all.. we support strings... and we assume values must be on a single line... so we realize you have a string (we know nothing about the array), but the rest is not because at the end of the line we have no idea what the rest of that content it.

Someone wanting to tackle this would need to add REAL array support to `ini` to detect array elements, etc... this would start to feel a lot like the JSON parser.  Right now the "value" parsing part of ini is not that clever.

At that point it might make sense to split out ini from TOML though (not sure).

**Comment by yyyc514** [comment]
Could be beginner friendly.  You'd learn a lot by looking at the JSON grammar as an example.
