### ISSUE TITLE
custome keyword highlight

### ISSUE THREAD

**Issue by Myqilixiang** [highlightjs/highlight.js#2085]
I wanna to highlight a customer word,just like the "TODO" ,how can i make it
![image](https://user-images.githubusercontent.com/16489959/62261676-bb07b400-b448-11e9-8d72-be91d86388f9.png)

**Comment by marcoscaceres** [comment]
You might need to fork the language definition that handles Vue and add a custom rule for it. Then load the custom language definition instead of the standard Vue one.

**Comment by Cheezmeister** [comment]
Shouldn't this use case be handled by https://github.com/highlightjs/highlight.js/issues/609?

**Comment by yyyc514** [comment]
If your organization just uses a different/expanded lists of tags you could just alter the comment detection in the highlight.js source:

```js
    mode.contains.push({
      className: 'doctag',
      begin: '(?:TODO|FIXME|NOTE|BUG|XXX):',
      relevance: 0
    });
```

Add your custom tags there, and then all comments would get support for them.

**Comment by yyyc514** [comment]
You could also pre-parse the raw text for all mentions and then wrap them with your own highlighted HTML and then let Highlight.js chew on that.

Example:

https://github.com/highlightjs/highlight.js/issues/2064

**Comment by yyyc514** [comment]
Oh, I was just about to suggest hljs should expose these things, **but it already does.** So you could probably (without touching the raw JS accomplish what you wanted by:

```js
last_item = ...
hljs.COMMENT.contains[last_item].begin = '(?:TODO|FIXME|NOTE|BUG|XXX|FRACK!!!!):',
```

Though to be future proof you might want to detect which one was the "doctag" rule and edit it rather than going straight for the last rule...

That would magically accomplish what you wanted for almost all languages without changing the core library.
