### ISSUE TITLE
(bash) Nested strings are not parsed correctly

### ISSUE THREAD

**Issue by behrangsa** [highlightjs/highlight.js#2099]
Example:

```bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TLS_DIR="$SCRIPT_DIR/../src/main/resources/tls"
ROOT_DIR="$SCRIPT_DIR/.."
```

---

This is really two things.

- [x] String within string (the posted issue)
- [x] Variable within variable (issue below, from #1978)

**Comment by yyyc514** [comment]
Bash syntax currently only supports simple variables inside `$()` blocks:

```js
  };
  var QUOTE_STRING = {
    className: 'string',
    begin: /"/, end: /"/,
    contains: [
      hljs.BACKSLASH_ESCAPE,
      VAR,
      {
        className: 'variable',
        begin: /\$\(/, end: /\)/,
        contains: [hljs.BACKSLASH_ESCAPE]
      }
    ]
  };
```

To fix this you'd have to make bash self-referential (ie you can have bash inside bash)... I'm not sure that's possible (but need to learn).

**Comment by yyyc514** [comment]
This also applies to simple variables without variables (same issue really from #1978):

> In a bash script, you may have a variable WURST und refer to it via $WURST or ${WURST}.
You can supply a default value ${WURST:-salami} and that default value may itself be a variable
${WURST:-${CARNE}}. And this is where there's a bug in highlight.js:
In the last example, of the two closing curly braces at the end only the first one gets color, the latter one doesn't -- although it should because it is the closing brace to the very first opening curly brace.
