### ISSUE TITLE
Code cleanup: Replace regex-strings by native regex

### ISSUE THREAD

**Issue by nknapp** [highlightjs/highlight.js#2196]
Throughout the code of highlight.js, there are many places where strings containing regular expressions are used instead of natvie regex-statements. For example:

```js
  // Common regexps
  hljs.IDENT_RE = '[a-zA-Z]\\w*';
  hljs.UNDERSCORE_IDENT_RE = '[a-zA-Z_]\\w*';
  hljs.NUMBER_RE = '\\b\\d+(\\.\\d+)?';
```

I think the code would be much more readable by using native expressions. The primary gain would be to get rid of the confusing double backslashes (or quadruple backslashes in other cases).

```js
  // Common regexps
  hljs.IDENT_RE = /[a-zA-Z]\w*/;
  hljs.UNDERSCORE_IDENT_RE = /[a-zA-Z_]\w*/;
  hljs.NUMBER_RE = /\b\d+(\.\d+)?/;
```

I actually tried this change and a lot of tests fail, so other code would have to be changed as well.

The question is: Do you think this is a valuable change? I'm not sure if I have  the time to work on it, but I might if you want it.

**Comment by yyyc514** [comment]
I think there are a lot higher priorities... and often the strings are that way because they are later summed up and converted into LARGER regexes (or added to other strings, as you likely see by the failing tests)... so there might be performance implications as well.  

Usually I'm against sweeping changes to a codebase like this kind of thing. Also seems like the kind of thing to easily get wrong and I'm not convinced our tests are 100% good enough to catch subtle mistakes in this kind of transition.

What would be useful is perhaps an issue thread discussing if there is any rhyme or reason to why the languages themselves often use one or the other with no logic at all - and seeing if over the long-run that is something worth improving on. :-)

Are you just bored and looking for things to work on? :-)

**Comment by yyyc514** [comment]
The strings do make it much easier for Highlight.js to be used to highlight itself, LOL. ;-)

**Comment by yyyc514** [comment]
And it's worth asking if there might be some reason we don't know about that strings were preferred in the first place. (other than the need for concatenation)  @egor-rogov  @idleberg  Any idea?

**Comment by yyyc514** [comment]
It's really too bad JS doesn't have operator overloading...

**Comment by nknapp** [comment]
No I'm definitely not bored. Such things come to my mind when I try to analyse and understand code and I notice that it is just difficult.to read

**Comment by egor-rogov** [comment]
> And it's worth asking if there might be some reason we don't know about that strings were preferred in the first place. (other than the need for concatenation)

If such a reason exists, I'm not aware of it.

> I think there are a lot higher priorities
> Usually I'm against sweeping changes to a codebase like this kind of thing

Agree.

**Comment by yyyc514** [comment]
I think if we're making "deep dives" into fixing lots of issues with a certain grammar (like the recent Handlebars work, etc.) and while we're there (in a separate commit, to make review easy) it makes sense to turn strings into regexes (where no fancy string addition is necessary), I'd be ok with doing it as it comes up in the natural course of things.

Or just do it organically... there are so many strings that a few more aren't making my day significantly better or worse. :-)
