### ISSUE TITLE
New language: custom log

### ISSUE THREAD

**Issue by ladrob** [highlightjs/highlight.js#2215]
Hi,
This issue is rather - nice to have - type, probably important to more ...
There are many application logs which use keywords like: OK, Passed, Error, Warning, Failed, Info, Debug, Missing, True, False
Would be nice to have such "system language" which highlighted:
- in red: Error, Failed, Missing, False
- in yellow: Warning
- in green: OK, Passed, True
- in blue: Info, Debug

Best regards, Robert

**Comment by yyyc514** [comment]
The core team doesn't have a plan for ongoing development of new syntaxes (typically it's all we can do to keep up with support, issues, PRs, etc) - building support for new languages is mostly up to the larger community.  If you'd really like to see this language, perhaps you know a developer who'd be willing to put in the time to develop and maintain a grammar for it?

Because of this fact we close issues like this (preferring a single wish list) rather than have these linger potentially forever on the issue list. 

Pretty sure someone was already working on this idea though:

---

If you'd like to add this to the wishlist, please do:
https://github.com/highlightjs/highlight.js/wiki/Grammar-Requests
