### ISSUE TITLE
Get rid of incorrect NPM highlightjs

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2250]
The correct package is "highlight.js".  I'd push one last "fake" version of the old package that just pins a dependency on the new package.  Or if there is some better way of resolving dups like this I'd be all ears.

It's sad to see 16,000 people a week using this old version just because Google sends them there first.

Thoughts?  Objections?

@egor-rogov

**Comment by egor-rogov** [comment]
You mean this? https://www.npmjs.com/package/highlightjs
I guess we should do something about it, although I'm not knowledgeable in NPM.
@marcoscaceres?

**Comment by yyyc514** [comment]
Yep, that's what I mean.

**Comment by marcoscaceres** [comment]
We might need to talk to @isagalaev (sorry again to rope you in!) as somehow we need to publish script to publish to both (I don't have permissions to publish that package)... we can't really delete the "other" (but not "fake") package as so many people are depending on it.

**Comment by isagalaev** [comment]
I was very surprised to see myself even attached to that NPM package %-) What I think it is, is a package built from https://github.com/components/highlightjs which is a completely independent effort of packaging highlight.js into Bower (because we refused to provide every imaginable packaging solution-of-the-week ourselves). So it's not really a fake, it's a distribution. And actually says "Shim repository for highlight.js" on the box.

It is possible thought that these guys are not interested in maintaining it anymore, in which case it might be worth talking to them and asking to remove the outdated package from npm.

**Comment by isagalaev** [comment]
> We might need to talk to @isagalaev (sorry again to rope you in!)

It's totally fine. There are certainly things in the history of the project that only I can remember.

**Comment by yyyc514** [comment]
Evidentally Marco already made a question with no response:

https://github.com/components/highlightjs/issues/47

I just pinged it.

**Comment by marcoscaceres** [comment]
Someone might need to just make a pull request. Looks like all that’s needed is to update the version in a few files and run make.

**Comment by yyyc514** [comment]
Package has been bumped and then officially deprecated now on NPM.  I think that closes this issue in my mind. CC @egor-rogov
