### ISSUE TITLE
Thoughts on release management

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2252]
Since I've done 2 releases now I thought I'd type up my thoughts and see if we could find some kind of consensus.  I'd prefer to have somewhat stable releases that are separate from ongoing development work... IE, we can release 9.16.2 with a SINGLE hot fix without releasing a bunch of other random stuff that's slated for the 9.17 release.

This also gives us the power to slide bug fixes into patch releases easily if we choose to (cherry-pick, etc) while saving the enhancements for minor/major versions.  _Though of course I'd prefer not to release every time we fix a bug, unless it was critical._

To that end currently we have a `9_16_stable` branch that I'm releasing from.

Master tracks the ongoing 9.17 work...

Open to thoughts/discussion.

**Comment by yyyc514** [comment]
One question is when work begins on a new version at what point the repo should change from 9.16.x to 9.17... most of my professional work has been with private repos and clients where this type of public versioning wasn't critical.

I'd like the new build system to label builds (in the JS) with the git hash and such niceness, but still I think the question is whether it's:

`9.16.2 (hash)` or `9.17 (hash)` or ``9.17.beta (hash)` or what not.

**Comment by yyyc514** [comment]
I think I like the rails way: 
https://github.com/rails/rails/blob/master/RAILS_VERSION

If we did that, that would mean I'd update the current version to 9.17.alpha or some such while work was in progress.

**Comment by egor-rogov** [comment]
IMO having master + stable branch(es) is a right way, but it is more complicated either. It is a must when release cycle is long, and you can commit something that must be accompanied by another commit to work properly, and you absolutely don't want to introduce any new functionality until next major release, and so on. In a sense, it is an indicator of maturity of the project.
I think we can yet live without that complexity, but if you feel we need it and you have time and energy - why, go ahead.
(And of course it would be great if you spend some of your time & energy to update Maintainer's guide with the procedure so that we can follow :)

**Comment by yyyc514** [comment]
I'll see what I can do.
