### ISSUE TITLE
[Question] Is there a way to "highlight" just certain lines?

### ISSUE THREAD

**Issue by kud** [highlightjs/highlight.js#2253]
Hey.

I would like to know if it's possible to highlight just some lines. For sure I still want the colours on the whole code, but I also would like a highlight on certain part of code.

Some of highlighters in markdown use this trick (remove the `\` here, it's just to display it well):

```
\```javascript{2-5}
{...}
\```
```

to highlight the lines from 2th to 5th.

It could be great to have it here.

You've got an example here: https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html

  
![Screen Shot 2019-11-03 at 12 35 05](https://user-images.githubusercontent.com/655838/68084482-63f1f080-fe36-11e9-95fb-eea92fb88054.png)

Thanks!

**Comment by yyyc514** [comment]
That works with markdown, but hard to define a general way to do this (by just modifying the source code) with all languages.  Also, our philosophy has always been a bit more on the minimalist side.  See: https://highlightjs.readthedocs.io/en/latest/line-numbers.html

That said if you wanted to work on your own plugin on top of Highlight.js to provide this functionality, that'd be a spiffy idea. We've been talking about such things lately and making that easier to do:

https://github.com/highlightjs/highlight.js/issues/2225

This type of pluging likely be some sort of post-render plug-in... but to get started you'd just WRAP us... so your function would be like:

```js
function highlightWithLines(block) {
   hl's.highlight(block);
  // your code goes here and takes the generated code applies your custom
  // modifications then updates the DOM accordingly
}
```

Then if we later added a hook for a plugin then your plugin would just hook that and would also look the same except your code would move into a callback inside your plug-in rather than wrapping us.

**Comment by kud** [comment]
Thank you :) The thing is I'm using https://github.com/weswigham/metalsmith-metallic so I've got to go deeper to understand how to deal with this feature.

Thank you!

**Comment by yyyc514** [comment]
I’m not 100% sure when I the pipeline you use that. Do you run it before the MD to HTML conversion? Looks super simple though. It’s only 90 lines of code. If you added a plugin to Highlight.js to support this you’d simply  have to modify this metallic thingy to pass thru the line numbering info from your raw markdown into the format the plugin inside Highlight.js expected. 

Still my thoughts about how to get started without a plugin would apply just the same. Just now you have one library to wrap and one to hack.

**Comment by yyyc514** [comment]
Ref: https://github.com/highlightjs/highlight.js/issues/858

**Comment by yyyc514** [comment]
See also: https://github.com/highlightjs/highlight.js/issues/1561

You can also do your line-based markup FIRST... and then call highlightBlock (this works if you're using the browser because the DOM auto-merge stuff will preserve your HTML and then auto-merge it after highlighting... 

Closing as asked and answered.

**Comment by kud** [comment]
Thank you :)

**Comment by eric-wieser** [comment]
For any future readers confused by this issue, note that "DOM auto-merge stuff" was removed in #2889.

**Comment by mnapoli** [comment]
@eric-wieser I've been through all the threads I think, did you find any way to make this work? I couldn't find any…

**Comment by eric-wieser** [comment]
I've just been using the old version, as that's what ships with reveal.js anyway, which is where I was using it.
