### ISSUE TITLE
(kotlin) Incorrect handling of strings with triple quotes

### ISSUE THREAD

**Issue by gdmfilippov** [highlightjs/highlight.js#2280]
The following Kotlin code has incorrect highlighting. 
The triple quotes string ends insided myFun, but highlightjs highlight the string till the end of file.
```
fun myFun(f: Boolean): String {
  return if (f) """f="true"""" else """f="false""""
}

fun main(args: Array<String>) {
    println(myFun(true))
    println(myFun(false))
}
```
P.S. This is a correct Kotlin code, it prints
```
f="true"
f="false"
```

**Comment by yyyc514** [comment]
How does it know which quotes end the string?

**Comment by Qumeric** [comment]
There are three subsequent quotes which begin and end the raw string literal. If there are more subsequent quotes then we use the first subsequent three for beginning and the last subsequent three for ending.

So """x""""""" is correct and contain ' x"""" ' (spaces are for better visibility)
The same goes for """""x""".
""""""x""" is incorrect because we open and close the raw string literal right away. 
"""x"""e""" is incorrect as well because it is just a string "x" and the "e" literal and three quotes opening the new (not closed) string.

Hope it helps!

**Comment by yyyc514** [comment]
So sounds like we close with `“”” not “`.  Might be a simple fix with look ahead.
