### ISSUE TITLE
(bash) "clone" considered built-in, but really it's Zsh, not bash

### ISSUE THREAD

**Issue by patricknelson** [highlightjs/highlight.js#2302]
For some reason, we're experiencing `clone` being highlighted seemingly incorrectly in code we're flagging as `bash`:

![image](https://user-images.githubusercontent.com/4269377/69756314-13a54000-110f-11ea-9955-e58e4efb850d.png)

I tracked it down to this, and it seems to be coming from `zsh` built-ins: https://github.com/highlightjs/highlight.js/blob/master/src/languages/bash.js#L58-L60

Would it be possible for us to maybe separate `bash` and `zsh` and then maybe configure `zsh` to inherit highlighting from `bash` whilst adding it's own additional keywords? Or, does `clone` belong there at all? It may belong, I'm just not familiar with Zsh.

**Comment by yyyc514** [comment]
http://info2html.sourceforge.net/cgi-bin/info2html-demo/info2html?(zsh)The%2520zsh%2Fclone%2520Module

**Comment by yyyc514** [comment]
> Would it be possible for us to maybe separate bash and zsh and then maybe configure zsh to inherit highlighting from bash whilst adding it's own additional keywords?

That's a possibility, but not sure it's worth the trouble.  It would also be a breaking change.

**Comment by yyyc514** [comment]
This is also used by "Shell" to highlight lines inside a "Shell Session"... if we split this then we start to run into the problems like we have with templates now... (that a templating language can often pair with many other rendered languages)

So you'd ALSO need a Bash Shell Session language, a Zsh Shell Session language, etc... 2 languages turn into 4 (at least).

**Comment by yyyc514** [comment]
I think in cases where someone has to pick the language manually it makes the selection easier to have a single language for this, I just think the current one is poorly named. @egor-rogov Any thought here?

**Comment by patricknelson** [comment]
Yeah I can see how it gets a bit hairy. From our perspective (were we're here strictly for the `bash` highlighting), it looks like a bug for words like `clone` in a simple `git clone ...` to get highlighted, as it's not really a bash built-in. Even in the case of `zsh`, that would get highlighted, so segmenting into two different languages doesn't _necessarily_ solve the core issue per se (as it's a simple word match and not addressing context). 

I haven't looked at the internals of `highlight.js` yet, so I don't know if it's able to more intelligently highlight based on the location of keywords; go too far and you're building an interpreter, not a highlighter 😄

**Comment by yyyc514** [comment]
> Even in the case of zsh, that would get highlighted, so segmenting into two different languages doesn't necessarily solve the core issue per se (as it's a simple word match and not addressing context).

Exactly, which is why I'm not a big fan of changing the way this currently works.  We simply find works wherever in the file and highlight them.  We don't syntactically parser and evaluate Bash/Zsh etc... so there is no good way for us to tell if someone is a command or an argument.

> so I don't know if it's able to more intelligently highlight based on the location of keywords

You have options, but commands can appear anywhere... you could have subshells, `&&` commands, etc... And then my thought was ignore double words like "git clone". But then you could theoretically do `time [command]`... although I could see arguments that perhaps you shouldn't highlight command there, but OTTOMH I just imagined you would.

@egor-rogov How would you feel about an exception for `git clone`? Although that's kind of a dangerous road to start walking down.

Or would you be more of a fan of splitting the grammars?

---

My gut take here is this isn't a big enough issue to warrant big changes.

**Comment by yyyc514** [comment]
Closing this with "My gut take here is this isn't a big enough issue to warrant big changes."  What is happening here is intended (but suboptimal behavior).  **I don't think the core issue here is resolvable** without a pull bash/sh/zsh interpretive pipeline.  I'm welcome to be proven wrong.

Also, one big negative to splitting languages into smaller and smaller packages (sh, bash, zsh, etc.) is that there is more chance for neglect.  It's easier for us to maintain "shell scripting" as a single language than to keep track of 4 different (but very similar) languages.  Dependencies can help a LITTLE here, but often come with their own issues.

This situation might be improved with ES6 modules and the new build pipeline.  We will see.  I'm not 100% opposed to say a separate "zsh" grammar on it's own merits, but seeing as how that doesn't actually solve the REAL issue here...

**Comment by patricknelson** [comment]
Alright, thanks for the consideration!

**Comment by yyyc514** [comment]
If it's your own site it's pretty easy to build a customized version of Highlight.js... you could build one that removes clone from your Bash language... just to fix your own site...

**Comment by patricknelson** [comment]
Hah, well I was serious, thank you 😄 This was just a really minor request and I wanted to just confirm if it was easy to do and, understandably, it has a fairly broad impact which makes a bunch of sense. 

I run a large site with a lot of open source code on it (we've got a bunch of articles on [tech.ebayinc.com](https://tech.ebayinc.com/) where this is used).  While we _certainly could_ tweak it, I have a policy in my dev team to not modify any sort of core libraries unless we can ensure they are persisted in the actual OSS code itself, due to the risk of losing those changes over time as we upgrade things (just creates technical debt). So, normally we first attempt changes by leveraging an already exposed API where we could extend with a custom module to add our desired functionality (e.g. adding "ebay-bash" syntax highlighting). If that's not possible, that's where we'd consider doing a pull request and this issue was just to explore the feasibility of that.

That said, if we do upgrade our deploy workflow, we might be able to leverage something that would make it easier for us to do that without any changes here. Like maybe using webpack or browserify to compile a modified version that then ships with our JS bundle which will then include our custom language highlighter. 

**I will say:** It'd be _pretty cool_ if you could augment the library with your own configuration code similar to the code in [the language list here](https://github.com/highlightjs/highlight.js/tree/master/src/languages) at _run time_ in the browser (during initialization). However, poking through a few of these, that looks potentially complicated as well (particularly if you want broad browser support).

**Comment by yyyc514** [comment]
> Like maybe using webpack or browserify to compile a modified version that then ships with our JS bundle which will then include our custom language highlighter.

Well languages are pluginable... so you could just make a new Bash and plug that in... and all you'd break is that you wouldn't get any upstream changes to Bash unless you checked.  You merely need to do `registerLanguage("bash", newDefinition)`... it'd be fairly trivial to add to any typical build pipeline.  The README has docs on using additional/custom languages.

> I will say: It'd be pretty cool if you could augment the library with your own configuration code similar to the code in the language list here at run time in the browser (during initialization). 

I'm not sure **exactly** what you're asking/suggested here.  Languages ARE configured at run-time already.  The default build just bundles some common sense default languages (which are then registered with the library at run-time).

**Comment by yyyc514** [comment]
Ha, I think you could actually define your own bash and run-time and inherit from the existing bash and then overwrite it:

```js
newBash = function() {
  oldBash = hljs.requireLanguage("bash").rawDefinition()
  oldBash.keywords.build_in.replce("clone ","");
}
hljs.registerLanguage("bash", newBash)
```

Or very close.

**Comment by yyyc514** [comment]
Oh, `requireLanguage` is new... so you could use `getLanguage()` if you're on production code.

**Comment by patricknelson** [comment]
Ok cool! Is this documented somewhere? If not maybe that’s all we need 😁

**Comment by yyyc514** [comment]
https://github.com/highlightjs/highlight.js/pull/2311/files

The whole process, no... but look at C++/Arduino for another sample.
