### ISSUE TITLE
Free Resource: Highlight.js languages as HTML Select and JSON

### ISSUE THREAD

**Issue by command** [highlightjs/highlight.js#2338]
Howdy! I needed the list of languages as an HTML select and figured other people might benefit from that, too. Here's a Codepen with the HTML as well as a little script to generate the list as an array of JSON objects: https://codepen.io/command-the-scripter/pen/JjoyKQE

**Comment by yyyc514** [comment]
I'm not quite sure what to do with this.  It's not an issue, so it can't live here... and we don't really use the wiki for stuff like this...

**Comment by egor-rogov** [comment]
Probably it could be helpful if we supply such list of languages for each bundle?.. Yet I'm not sure too.

**Comment by yyyc514** [comment]
I've thought for a long time each grammar should include a name key and encode it's own properly formatted name, ie "C++", "FreePascal", "LaTeX"... Then you could generate this with 2-3 lines of JS and the core library... but right now it's impossible since the names can't be found anywhere.

@egor-rogov Any objection to adding `name`?  We could default a name to it's filename (at runtime) if no one wants to resolve this a single huge PR against all languages.

**Comment by egor-rogov** [comment]
Don't we already have this name in the grammar file header? `Language` class in `tools/lib/language.js` works with it.

**Comment by taufik-nurrohman** [comment]
Use `hljs.listLanguages()` and let external I18N system to convert language key into human readable name?

**Comment by yyyc514** [comment]
@egor-rogov Oh sure you can already do this if you have the RAW source, but not the library - I'd like to see that changed so that `name` is actually a key of each language.

**Comment by yyyc514** [comment]
Creating #2394 to follow up on this.  Closing this as a duplicate issue of that.
