### ISSUE TITLE
How can I use use highlight.js in TS without all the languages?

### ISSUE THREAD

**Issue by rtfpessoa** [highlightjs/highlight.js#2340]
I read in the README about importing `import * as hljs from 'highlight.js/lib/highlight.js';` instead of the index but this does not have types. Anyone know how I can get types for the file instead of the module?

**Comment by yyyc514** [comment]
The readme answers this and has an example also:

https://github.com/highlightjs/highlight.js#commonjs

Require whichever languages you need *individially*, then register them.  Just look at the `index.js` file to see how it's done.

**Comment by rtfpessoa** [comment]
@yyyc514 that is exactly what I stated in my question.
I know that you have an example on the README but I cannot make it work without hacks in Typescript, since the projects has not typings for the `highlight.js/lib/highlight.js` file and just has for `highlight.js or `index.js` file which forces all the languages.

**Comment by yyyc514** [comment]
Sorry for any confusion.

>  since the projects has not typings for the highlight.js/lib/highlight.js file and just has for highlight.js or index.js

I think you're asking a Typescript specific question.  I'm having trouble understanding.  Where is it that we have (or provide) types for the library?  Our NPM package is just a bunch of JS files we build.

So I'm not sure why you have types for one thing but not others.  Someone more familiar with TS might have to jump in here or you might have to make some suggestions on how we might go about even fixing this - since right now I haven no idea.

**Comment by rtfpessoa** [comment]
This is definitely a TS specific question, maybe I could have pointed to the source of the types.
They are here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/highlight.js/index.d.ts and were contributed by @nikeee, @sourrust and @joshuakgoldberg, maybe they have some suggestion regarding this?

**Comment by yyyc514** [comment]
Feels like perhaps this issue should be filed/asked against the DefinitelyTyped repo, perhaps?  We don't provide typescript types with our npm distro.

**Comment by JoshuaKGoldberg** [comment]
Hi! Agreed. This feels like two questions:

* Can we improve the typings of highlight.js in DefinitelyTyped?
* How do you declare these types in TypeScript?

FWIW, https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules (or if that's not clear, https://stackoverflow.com/questions/44058101/typescript-declare-third-party-modules) might be helpful for both.

**Comment by rtfpessoa** [comment]
Thanks for the help here I opened an issue in DefinitelyTypedto follow with the discussion.

**Comment by KingDarBoja** [comment]
Facing some issues with this library as the current documentation (CommonJS section), states that we should import the core file instead of the default import.

> Therefore it is likely to be more efficient to import only the library and the languages you need:
>
> ```typescript
> import hljs from 'highlight.js/lib/core';
> import javascript from 'highlight.js/lib/languages/javascript';
> hljs.registerLanguage('javascript', javascript);
> ```

However, trying to do on my Angular 9 `app.component.ts` file, I get this error:

`Cannot find module 'highlight.js/lib/core'.`

![image](https://user-images.githubusercontent.com/30560560/76359832-d0e82c00-62e9-11ea-98c1-e15d4816ab34.png)

**Comment by yyyc514** [comment]
Please see the stable documentation:

https://github.com/highlightjs/highlight.js/tree/9-18-stable

OR use the v10 beta:

https://www.npmjs.com/package/@highlightjs/highlight.js

**Comment by KingDarBoja** [comment]
@yyyc514 I didn't know there was a different npm package for the v10 but glad to see your quick response 👍

**Comment by yyyc514** [comment]
Yeah, there is an open PR to change the readme.  I just published the beta to it's new location today and we're still trying to sort out the proper transition.

**Comment by yyyc514** [comment]
@nikeee, @sourrust and @JoshuaKGoldberg 

Could any of you help?  I'd like to move the types into our repository (so we keep them up-to-date as the library changes, but I'm having a heck of a time figuring out how to do this or f it's even possible).  Could any of you look at:

https://github.com/highlightjs/highlight.js/issues/2603
