### ISSUE TITLE
JavaScript highlighting breaks on left angle bracket (less-than, <)

### ISSUE THREAD

**Issue by sompylasar** [highlightjs/highlight.js#238]
This may be reproduced with the jQuery code ( http://code.jquery.com/jquery-1.10.1.js )

The less-than `<` operator, bit-shift operator `<<` and some occurrences of `<` in comments produce a `tag` highlighting.

Examples from the jQuery code where `tag` is produced:

```
        // BMP codepoint
        high < 0 ?

// Support: Android<4.0
// Detect silently failing push.apply

// Support: Chrome<<14
// Always assume duplicates if they aren't passed to the comparison function

// General-purpose constants
strundefined = typeof undefined,
MAX_NEGATIVE = 1 << 31,
```

It looks like a major bug to me.

Also looks like the following lines of the language definition somehow connected to the issue, but I don't exactly sure how to fix it (and if they are the only cause):

```
      { // E4X
        begin: '<', end: '>;',
        subLanguage: 'xml'
      }
```

**Comment by unilobo** [comment]
Hey, just using version 8/9 and this seems to suffer the same problem?

Namely, html does not display correctly unless replacing left angle bracket with &lt;.

I wish you would mention this in docs/readme. d:)

Is this expected behavior or a bug?

Example here;

http://codepen.io/2dareis2do/pen/ygdWXV

**Comment by isagalaev** [comment]
@unilobo the behavior you're seeing is not caused by this bug which deals with a raw staring to highlight. Yours is just plain lack of escaping in HTML: you need to escape `<` in HTML if you want it literally. `<code>` has no special escaping rules and `<h2>` inside `<code>` is just a tag, same as everywhere else. This has nothing to do with highlight.js, really :-)
