### ISSUE TITLE
NOTICE: v10 series does not support IE11 or legacy browsers.

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlight.js#2501]
**This is a known issue and is intentional.  We're dropping support for these older browsers.**

Please see: https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md

This is intentional and due to limited developer time and these older browsers waning market share.  If your site absolutely must support such older browsers we recommend you continue to use the 9.0 version of Highlight.js, although it will no longer be receiving updates or fixes.

Or to get the best of both worlds your site might want to browser sniff and serve version 9 to legacy browsers but serve up the new version 10 for everyone else.

**Comment by droshev** [comment]
Hello,
I understand your decision. It is not great to support browsers like IE11, but on the other side it is not a legacy browser until October 2025 and there are quite some serious companies are still using it productively. 
I understand that for version 10 you won't want to support IE11 but at least could you offer some support for v9?

**Comment by yyyc514** [comment]
A quick overview:

- Highlight.js v9.x is still entirely usable as far as I know.
- IE 11 has only 5% market share and shrinking.
- AFAIK we have 0 maintainers interested in supporting IE11.

If someone finds a HUGE problem with v9 they are always free to file an issue, and I would at least review it, but without additional help I'm not sure I have time to support old, dying platforms. Just spending time tracking down an Object.freeze bug in IE11 for one of the last 9.x releases was already SUPER annoying and time that could have been much better spent on any number of other issues.

So I'm not sure there is anything to really discuss here at the moment until we actually have a real serious problem with v9. Unless you want to elaborate on what you meant by "support".

**Comment by yyyc514** [comment]
Auto-closing.

**Comment by puzrin** [comment]
@yyyc514 I do not object against ancient browsers drop, but i don't like HOW it was done. You could leave transpiler to es5 - that should cost nothing, since you transpile from ts anyway.

9.x has serious bug https://github.com/markdown-it/markdown-it/issues/676. As user, i'm ok to just upgrade highlightjs from time to time. But removal of es5 syntax in generatetd code caused more problems than expected.

Could you consider return es5 back?

**Comment by yyyc514** [comment]
>  I do not object against ancient browsers drop, but i don't like HOW it was done.

How was it done that you disapprove of?  

> You could leave transpiler to es5 - that should cost nothing, since you transpile from ts anyway.

We do not use the TypeScript compiler, we only use TS commented types it to improve our linting experience.   I also know it's  not this simple since we've had issues in the past with obscure browser behavior in older browsers - EVEN when we were using all ES5 code.  So even if we transpiled to ES5 that does not entirely save us from dealing with weird compatibly bugs with old browsers (like IE11).

> Could you consider return es5 back?

I'll keep listening, but right now it seems like 99.99% of people don't care and with the very limited time we have this doesn't seem a very good use of time for the project.

> 9.x has serious bug markdown-it/markdown-it#676. 

If someone wants to make a readable PR, the solution is clear, and it has good tests... I'm not opposed to merging it into the `9-18-stable` branch... but at just a glance I'm not even sure what that code snippet is supposed to be - so it's hard to say if this is a problem with the parser, the grammar, or a run-away regex.

**Comment by puzrin** [comment]
> How was it done that you disapprove of?

I have test, just parsing assets in es5 mode. Now it fails because 10.x in published package uses es6 syntax. Some other tests fail too, but i did not investigated details yet.

> I'll keep listening, but right now it seems like 99.99% of people don't care and with the very limited time we have this doesn't seem a very good use of time for the project.

Referring to those who "not care" may be a kind of [survivorship bias](https://en.wikipedia.org/wiki/Survivorship_bias) :). 

I don' write es5 manually (that's really horrible). But all web-related packages have automated es5 builds, and that works really well. If you don't use async/await, regex `/u` flags and so on, cost is about zero.

I do not suggest to reduce development comfort anyhow. But i suggest to be more gently with published things.

**Comment by yyyc514** [comment]
> How was it done that you disapprove of?

I meant some issue with the way we handled the release itself.  I understand that you wish we still supported IE11.  But we released a major new version. That version dropped support. It was all quite orderly. This information was available on the GitHub prior to v10 being released and v9 is still available.

> Referring to those who "not care" may be a kind of survivorship bias :).

Perhaps but the support forums here are the only thing we have to gauge demand.  And even then we have to have developers to fulfill that demand.  I'm not really interested in working on IE11 (at all) [nor do I have any way to test it] so that demand might not matter without volunteers to match the demand interested in maintaining support for old browsers.

> But all web-related packages have automated es5 builds

I doubt this. :-)  But again the problem isn't just a build problem.  The problem is we don't have time or attention to support such an old browser.  

> If you don't use async/await, 

Sounds like things we'd like to use in the future. :-)  We don't want to be limited by what works in IE11, hence dropping support.

> regex /u flags and so on, 

And this is definitely something someone will ask for eventually.

> cost is about zero.

This is always a lie, the cost is never 0. :)

**Comment by puzrin** [comment]
> I understand that you wish we still supported IE11.

No. I said this explicit. I DON'T ask IE11 support. I wish es5 syntax in published releases, to avoid issues with browserify.

> Sounds like things we'd like to use in the future. :-) We don't want to be limited by what works in IE11, hence dropping support.

It looks like using imaginated future benefits to argue real problems in present. As author of js-yaml & markown-it parsers, i can't imagine how async parsing can simplify anything.

> > regex /u flags and so on,
> 
> And this is definitely something someone will ask for eventually.

If that's really needed, this could be declared explicit (and we could find how to solve that). Because if this is used only in specific languages - that's not a big deal. Right now i've seen only one reason - you don't like IE11 very much.

> > cost is about zero.
> 
> This is always a lie, the cost is never 0. :)

"About zero" is NOT zero. It is "very small". For example, you have repo for CND publish, where content is autogenerated. You could do similar autogenerated `@highlightjs/es5` - it very similar and doesn't look difficult to maintain.

**Comment by yyyc514** [comment]
> No. I said this explicit. I DON'T ask IE11 support. I wish es5 syntax in published releases, to avoid issues with browserify.

Ah, that's a little different.  Still feels like the real problem here is with browserify, not us.  Just out of curiosity how do libraries with 100s or 1000s of files do that?  Do they ship two entirely different NPM packages?  Sounds like that is what you're suggesting below.

> i can't imagine how async parsing can simplify anything.

Seems highly relevant to just-in-time loading of grammars via HTTP/fetch/etc... of course there are more boring ways of doing those things, but as long as we support only new browsers there is no reason to avoid the nice new abstractions we have available to us.  That is a clear advantage.

> Right now i've seen only one reason - you don't like IE11 very much.

This is true, but as I've said it's not JUST that.  There is a bigger picture.

> "About zero" is NOT zero. It is "very small".

Let me correct.  The cost is _rarely_ about zero. :-)

> For example, you have repo for CND publish, where content is autogenerated. You could do similar autogenerated @highlightjs/es5 - it very similar and doesn't look difficult to maintain.

And let's say we did that, would we then have to purposely block older browsers that we no longer support?  I'm not interested in pretending to support things we don't or being unclear.  _There is a reason we dropped support for IE11._ We have no one on the team who wants to support it.

**Comment by puzrin** [comment]
> **Sorry I missed that.** Ah, that's a little different. Still feels like the real problem here is with browserify, not us.

I'm here not not to shame or search who is guilty. I'm to search constructive solution, if that's possible. Browserify has babelify plugin, but it doesn't touch dependencies, if those have no appropriate config in their package.json. This may be bad or good, but for many years that's de-facto behaviour. 

> Just out of curiosity how do libraries with 100s or 1000s of files do that? Do they ship two entirely different NPM packages? Sounds like that is what you're suggesting below.

- https://github.com/codemirror/CodeMirror [any] ./src => [es5] ./lib is the most common case.
- lodash publish a lot of sub-packages

That's all subjective and depends on personal preferences.

I do not insist on separate package. That was only a quick example - solutions available, without intrusion into your development process (because asking you to reorganize all your process would be impolite). If you don't like this approach, and have additional requirements, i could search something different.

> Let me correct. The cost is _rarely_ about zero IME. :-) This could possibly take me at least few hours to figure out (then create new npm packages, updating a deployment pipeline, CI, etc...) - and that's time that I feel could be better spent elsewhere. That's not counting future time spend to support this new pipeline and any problems with it - purposely filter out browsers we do not support, etc. I've been in Tech for over 25 years, things are rarely as simple as those "outside" think they.

You already has pipeline for CDN, very similar. IMO it's ok for preliminary estimates. I try to be constructive, with respect to your time, and suggest reuseable solutions with ~ predictable costs. If something concrete is deeply wrong - let me know, and i will try to suggest something better.

> And let's say we did that, would we then have to purposely block older browsers that we no longer support? I'm not interested in pretending to support things we don't or being unclear. _There is a reason we dropped support for IE11._ We have no one on the team willing to support it.

IMO, as any problem, this can be splitted into parts:

1. What goal should be reached?
   - (?) stop waste time for IE11 debug
   - (?) need some es6 features ( `=>`, `...args`, classes, ...)
   - ... something else (i don't know all your intents)
2. How can we reach this goal?

For example, one of solutions could be to tune "autocommenter" action to close issue when IE11 mentioned. Or you could test user agent (or js features) and throw exception "IE11 sucks".

Another approach would be to ask directly in tracker "do you still need es5 distribution of hljs (but without official ie11 support)?". And so on...

Usually, there are multiple ways to reach desired goal.

**Comment by yyyc514** [comment]
Well I certainly wasn't trying to shame anyone... but ES6 is the new thing, and pretty common now in the browser-side ecosystem at least - has been for years (so much so that we can use it and out of millions of downloads you're one of the few people pushing back).  So it seems tooling really needs to catch up.  Perhaps "motivate" would be a better word. :-)

If there is one magic line we can just add to package.json to solve this that MIGHT be doable. :-)  But you haven't mentioned it yet. :-)  That would be interesting to learn about.  Is there such a thing?

_Honestly I have no idea how the files get to the CDNs, lol._  I've asked and I've been told we don't trigger the CDNs... or maybe that's something we setup long ago... but we do have a process (that I've never seen) that does auto-build and publish to our website and NPM when new tags are pushed to git.

I'm super familiar with the overall library and grammars at this point - and I built the new build system we currently use, but the whole "deployment" process (for new releases) is still pretty opaque to me. So don't assume I know everything just because I'm the current maintainer. :-)

> Another approach would be to ask directly in tracker "do you still need es5 distribution of hljs (but without official ie11 support)?". And so on...

You're free to open such an issue and I'll leave it open (at least for a while) to serve as a discussion area for thoughts/workarounds (I feel there are likely a few) and other folks who share this concern... and we can go from there.  This issue was open for quite a while though and saw very little traffic, though perhaps your ES5 issue is a different beast.

**Comment by puzrin** [comment]
> If there is one magic line we can just add to package.json to solve this that MIGHT be doable. :-) But you haven't mentioned it yet. :-) That would be interesting to learn about. Is there such a thing?

https://github.com/defunctzombie/package-browser-field-spec

But i would not recommend to substitute hundreds of files. Hidden forced duality may become ass pain at some moment. I would be ok to just require files from `/dist/es5` folder. This can be in git-ignore, but been built on tests & pre-publish hook.

Full list of choices (at all, not for this package) is:

- `browser` field, for small hacks
- transpile /src => /lib
- additional builds in `/dist`
- auto-generated multiple packages

> _Honestly I have no idea how the files get to the CDNs, lol._ I've asked and I've been told we don't trigger the CDNs... or maybe that's something we setup long ago... but we do have a process (that I've never seen) that does auto-build and publish to our website and NPM when new tags are pushed to git.

If you speak about jsdelivr/cdnjs - those take updates from npm regisry.

Who and how run scrips, and why https://github.com/highlightjs/cdn-release commits go from @isagalaev - no idea. I think, now this can be done via Gihub Actions in more explicit (less magical) way.

> I'm super familiar with the overall library and grammars at this point - and I built the new build system we currently use, but the whole "deployment" process (for new releases) is still pretty opaque to me. So don't assume I know everything just because I'm the current maintainer. :-)

If it's the main blocker, i could try to help.

> You're free to open such an issue and I'll leave it open (at least for a while) to serve as a discussion area for thoughts/workarounds (I feel there are likely a few) and other folks who share this concern... and we can go from there. This issue was open for quite a while though and saw very little traffic, though perhaps your ES5 issue is a different beast.

https://github.com/highlightjs/highlight.js/issues/2642 i tried be neutral and not give any direct promises. Please edit if something is wrong.
