### ISSUE TITLE
Question: only color specific lines?

### ISSUE THREAD

**Issue by connor** [highlightjs/highlight.js#2579]
Hey there,

I searched the issues and couldn't find anything, so apologies if this has already been answered.

Is there a way to _only_ color specific lines of code?

For example, if I am using `highlight.js` on a technical document where each section builds upon one another, I only want to color the _new_ items in that code block.

Quick example:

```js
var foo = 'foo';
```

...further down the page...

```js
var foo = 'foo'; // this would be greyed out, as if it's a comment
var bar = 'bar';
var baz = 'baz';
```

Hopefully that makes sense.

---

Anyways, is this possible? Any guidance?

Thanks so much!

**Comment by yyyc514** [comment]
I think the best way to do this would be with some sort of simple preprocessor.

The actual code:

```
var foo = 'foo'; 
var bar = 'bar';
var baz = 'baz';
```

After pre-processing:

```
////var foo = 'foo'; 
var bar = 'bar';
var baz = 'baz';
```

Where //// is the "magic escape sequence" to mean "discolor".... but //// is conveniently also a comment... so now you just highlight the whole file normally... then you "cleanup the output" by removing `////` whenever it appears after a `>` because the generated code will be `<span class=comment">////`...

**Comment by connor** [comment]
Perfect, that’s similar to what I had in mind. Thank you!

________________________________
