### ISSUE TITLE
[Request] Highlight Rust `unsafe` keyword differently from others

### ISSUE THREAD

**Issue by anp** [highlightjs/highlight.js#2585]
I'd appreciate a more distinct visual indicator of unsafe blocks and functions when reviewing highlighted code.

Currently it appears that [`unsafe` is a keyword](https://github.com/highlightjs/highlight.js/blob/debfdf7cc9822a49e7f033b2c286ef025ce8d3c8/src/languages/rust.js#L15). I'm not very familiar with hljs and so I'm not sure if the best option is to give it a custom mode(?) or if there's a built-in mode (a warning?) or if there's a way to e.g. apply a bold to the keyword but treat it as a keyword otherwise.

**Comment by yyyc514** [comment]
You could easily make a custom Rust grammar/theme and treat it however you like (flag it css class "unsafe", etc).  For the core library you're stuck with the CSS classes we have now:

https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html

And I'm not sure anything else fits - though if you have a suggestion, I'm listening.

There is also this discussion:

https://github.com/highlightjs/highlight.js/issues/2500

Optimally what you'd want is `keyword.unsafe` PERHAPS... but that wouldn't give you anything without a custom themes since none of the themes know what keyword.unsafe is.

---

OR you could try to do this with a post-highlighting plugin... highlight the code and then scan it yourself for `unsafe` (wrapped as a keyword) and manually alter the class (or add `style`)...

**Comment by anp** [comment]
Super useful info, thanks! Helpful to know that it's a Rust-only weirdness to have "that one special keyword".

Agree that a custom CSS class offers an enticing amount of control but needing to teach all the themes about it sounds...less fun (especially since I don't actually have a clear idea for what it "should" look like).

The post-processing sounds like it would actually make it possible to implement my original suggestion from work chat: wrap every `unsafe` instance with `<marquee />` :sweat_smile: .

Looking at the CSS classes, I'm wondering how easy it would be to add `strong` to the existing keyword styling. It would at least be a place to start.

**Comment by yyyc514** [comment]
> The post-processing sounds like it would actually make it possible to implement my original suggestion from work chat: wrap every unsafe instance with <marquee />

Well, that'd be ONE way to do it...

> Looking at the CSS classes, I'm wondering how easy it would be to add strong to the existing keyword styling.

I'm not sure it'll work but try adjusting the keys of the keywords:

```ts
    keywords: {
      $pattern: hljs.IDENT_RE + '!?',
      "keyword strong": "unsafe",
      keyword: KEYWORDS,
```

I'm not sure that'll actually work, but it's "where to start".  If not then you'd remove unsafe from keywords and make a rule for it instead with `beginKeywords`.

**Comment by yyyc514** [comment]
Closing this as it currently does not make sense until we perhaps have higher fidelity grammars where you could have say a more specific “keyword.unsafe” class that custom themes could then use to target Rust.
