### ISSUE TITLE
Bug: Alias collisons

### ISSUE THREAD

**Issue by GeeLaw** [highlightjs/highlight.js#2626]
There is one bug in alias handling and two instances (not sure if they are by design or a bug) of alias collision. They are found in release 10.1.1.

The mistake is that Arduino language incorrectly picks up the aliases of C++. This is because it [inherits from C++](https://github.com/highlightjs/highlight.js/blob/93fd0d7335e2b8b94dd122dc2898db8c86343257/src/languages/arduino.js#L98) but does not strip off the aliases. This affects functionaltiy. It seems that later-registered languages' aliases overwrite any earlier registration. Since Arduino is registered after C++ (because the former requires the latter), calling `getLanguage('c++')` will give Arduino (`arduino` with alias `c++`) instead of C++ (`cpp` with alias `c++`).

**Suggested Change.** add `delete ARDUINO.aliases` before returning.

The two instances of alias collision:

- Both Lasso and LiveScript have alias `ls`.
- Both SML and OCaml have alias `ml`.

Again, the resolutions of `ls` and `ml` depend on the registration order. However, these two cases might be sensible since both languages involved could have been meant by the aliases, and the problem does not appear if only one language is registered.

**Comment by yyyc514** [comment]
**Thanks for detailed and super informative report.**

> add delete ARDUINO.aliases before returning.

Or perhaps set to `ino`.  I'll give this some thought.  This might be getting into how people expect the grammars to respond though... if someone asked ARDUINO what it's aliases were, would "cpp" be a valid answer? _I think it might be._

>  calling getLanguage('c++') will give Arduino (arduino with alias c++) instead of C++ (cpp with alias c++).

I think this is the real issue.  Though I'm not sure we can have our cake here and eat it also.

> The two instances of alias collision:

Oh boy... I'd think this doesn't come up in practice because people probably don't use both these languages simultaneously, but we really should decide how to handle that better - because people surely could load them both if they desired.

**Comment by yyyc514** [comment]
@allejo @egor-rogov Any thoughts?

CC @wooorm

**Comment by wooorm** [comment]
> It seems that later-registered languages' aliases overwrite any earlier registration. 

To me it sounds like the current behavior is the most reasonable approach.
Same with an object: `map = {a: 1}`. If I now set `map.a = 2`, well, then `a` is 2. 🤷‍♂️

I understand lasso and livescript. I don‘t know sml or ocaml so can’t comment there. For Arduino, I don’t think it should register an alias for `cpp`.

**Comment by yyyc514** [comment]
I'm asking less about the collision behavior (which makes sense) and more about what do we do about the existing collisions we already have within the core library. :)

**Comment by yyyc514** [comment]
Resolved.

https://github.com/highlightjs/highlight.js/commit/7f63502b1cd7fda116a8731f74d4af1a203a179a
https://github.com/highlightjs/highlight.js/commit/e3665447f9b345c6a562986385353dffc018ce59
