### ISSUE TITLE
(parser) Public API methods should validate input types better

### ISSUE THREAD

**Issue by emanuelb** [highlightjs/highlight.js#2631]
Running `hljs.highlightAuto(1)`

Result:

```
Uncaught TypeError: value.replace is not a function
    at escapeHTML (/home/user/node_modules/highlight.js/lib/core.js:45:6)
    at justTextHighlightResult (/home/user/node_modules/highlight.js/lib/core.js:1763:14)
    at Object.highlightAuto (/home/user/node_modules/highlight.js/lib/core.js:1787:18)
```

it happend when I forget to use .toString() in below code on `buffer`:

```
var fs = require('fs');
var buffer = fs.readFileSync("file");
hljs.highlightAuto(buffer)
```

fix:
ensure code param is in correct type (string) otherwise return error (it's not string, type is X)

**Comment by yyyc514** [comment]
We probably could do better here, but if someone was going to tackle this I'd want a PR that dealt with ALL the public API methods, not just the "issue of the day"... ie fix the whole problem (I've renamed the issue accordingly)  I'd prefer not to add a ton of validation clutter to the codebase either  - we have a lot of API public methods - I'd want to wrap this kind of thing up in some type of nice abstraction:

```js
validateTypes(arguments,
      ["languageName", "code", "ignoreIllegals","continuation"],
      {
        languageName: "string", 
        code: "string", 
        ignoreIllegals: "boolean?", 
        continuation: "object?"
    }
```

This raises a few questions:

- Is there a nice JS type library we could pull in to do this for us - vs writing it from scratch? 
- Would we even want to do that (use an external lib) since currently we are "zero requirements" and always have been...
- Could we somehow do this at compile time using our existing TypeScript typing  - is there tooling for that kind of thing?

I'm not opposed to this - if it's done nicely/properly - but we've also managed without it for forever, so I'd say it's not the highest priority IMHO.  Leaving this open to continue the discussion.

**Comment by yyyc514** [comment]
This work would pair well with https://github.com/highlightjs/highlight.js/issues/2277

**Comment by joshgoebel** [comment]
_Periodic issue review._  This type of feature is really not helpful once code is in production - and would only add bloat while providing zero or almost zero benefit.  It would make some sense perhaps in a debug or development build - which isn't something we currently have.  I'm not sure it's worth creating another build target (dev) just to add run-time type validation.  Setting this to auto-close.
