### ISSUE TITLE
[Request] ... Script for adding new language

### ISSUE THREAD

**Issue by nagayev** [highlightjs/highlight.js#2795]
Recently I added a new language (javascript-repl). I suggest adding a script that will help with this. The input is the name of the language and the author's name. The script creates a folder for the language, writes the author's name and changes (to AUTHORS.txt and CHANGES.md), and creates test files.

**Comment by joshgoebel** [comment]
Since _as a general rule_ we don't allow adding/merging of new languages into core I'm not sure this is at all necessary.  `javascript-repl` avoids this as it's truly more of an extension to JS rather than a whole new language grammar.

There are two cases I see here off the top of my head:

- 1st party (core library) language grammar creation
- 3rd party language grammar creation

I think the first happens so rarely and is SO easy to do on it's own that a script isn't necessary.  And I'd suggest for the second that what would be better is a whole template repository, not a script... and you could argue that this already exists in the form of one of the simpler 3rd party grammar repos (like say robots.txt, etc).

So I'm not sure I see a need here at all.

**Comment by nagayev** [comment]
@joshgoebel 
Okey, may be you are right.

**Comment by taufik-nurrohman** [comment]
It would probably be good if we have some site that showcase 3rd party languages, themes and plugins just like https://vimawesome.com and https://vimcolors.com in the future.

Narrow down the core language support so that core teams can maintain just the essential ones. Let others maintains their projects related to _Highlight.js_ languages, themes and plugins following the core updates.

**Comment by joshgoebel** [comment]
Anyone who'd like to step up and create/maintain a `awesome-highlightjs` repo or site, that'd be awesome. :-)  It could probably be accomplished with just a GitHub repo / site / GitHub actions. (ie all on GitHub, no need for external hosting, costs, etc.)

I was thinking the other day though that perhaps we could use a `SUPPORTED_PLUGINS.md` or something though in this repo with links to plugins people have built.  ie, just like SUPPORTED_LANGUAGES, but for plugins.  I dislike the word "supported" though since the core team does not support 3rd party stuff.  I honestly don't have a feel for what plugins are even out there right now.

> I’m thinking about letting new programming language owners to officially create their own syntax highlighter.

I'm not sure what you're saying/asking here... this is exactly why 3rd party grammars exist.  Anyone can create one and then add it to SUPPORTED_LANGUAGES.
