### ISSUE TITLE
Proposal: Language "Champions"

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#2825]
**Is your request related to a specific problem you're having?**

It would be nice to have a way to spotlight people who go out of their way to maintain/make significant contributions to our first party grammars.  Also have a "go to" person to route language specific issues to that hopefully is a bit of an expert in that language (meaning they bring a ton of language context to the table that the core team doesn't have, etc).

We could have a list in AUTHORS.txt or make a new document... open to suggestions.

**The solution you'd prefer / feature you'd like to see added...**

Come up with a "title" of some sort, have an official list... I'm open to other ideas.  Any way to add a little "prestige" might be nice.

**Any alternative solutions you considered...**

Nope.

**Additional context...**

https://github.com/highlightjs/highlight.js/issues/1678

**Comment by joshgoebel** [comment]
@egor-rogov  @allejo 

Pinging a few people who've made large grammar contributions lately.  @halirutan  @schtandard @klmr

**Comment by klmr** [comment]
I like the idea of having a “go to” person, and I’d be happy to fulfil this role for the R language definition (plus potentially others in the future).

**Comment by halirutan** [comment]
It was always my belief that when I put my name on it, I'm responsible for it. It doesn't mean that I have to do all future work/fixes, but I always tried to be approachable when issues pop up so that I can help or give advice. For the Wolfram Language, I have quite a collection of highlighters in my bag:

- [JPrettify](https://github.com/halirutan/JPrettify) that I needed back when Joomla was a thing
- [Google-Prettify](https://github.com/halirutan/WolframLanguage-Google-Prettify) which is used on the [official Wolfram Community site](https://community.wolfram.com/) and was used on StackExchange until 2020
- [Rouge](https://github.com/rouge-ruby/rouge/pull/854) which is a highlighter for Jekyll
- [an IntelliJ plugin for the Wolfram Language](https://wlplugin.halirutan.de/) which of course is much more than a simple highlighter and which has a full-fledged parser and can do context-sensitive highlighting.
- [And now Highlight.js](https://github.com/highlightjs/highlight.js/pull/2706)

That being said, I don't need a champions-club to feel responsible but it surely is a very nice idea. The big problem with such things is always where to put it so that anyone even sees it. Because right now, we already have a champions-club and it's called `AUTHORS.txt` 😂 

![image](https://user-images.githubusercontent.com/511683/98433792-a3e35780-20ca-11eb-8226-369940054f2d.png)

**Comment by schtandard** [comment]
> It was always my belief that when I put my name on it, I'm responsible for it. It doesn't mean that I have to do all future work/fixes, but I always tried to be approachable when issues pop up so that I can help or give advice.

This is how I feel, too. I would add that this also goes the other way: I would like to actually be approached when changes to the LaTeX grammar are discussed. I don't think GitHub has a feature to facilitate this (I might be wrong). Designating contributors as go-to persons for specific languages may be useful for this, too.

The name "Language Champion" sounds a bit weird to me, though. It feels like an achievement in a video game. (This may be just me, of course.) The best alternative I could come up with right now is "Sponsor" (in the sense of a godparent).

**Comment by halirutan** [comment]
@schtandard I agree on all points.

> I don't think GitHub has a feature to facilitate this (I might be wrong). 

One simple solution we used in another project is to just ping the right person if an issue pops up. When my name is mentioned somewhere, I get a notification in my inbox. Also, I assume it's easy for the maintainers to just ping the Godparent in an issue/PR to ensure they don't overlook any subtleties that might break things.

> The name "Language Champion" sounds a bit weird to me

I wouldn't mind if it's something funny/original that sticks. I like Godparent much more than Sponsor (which sounds so much like money). I guess we have a ton of funny things that we could use for ideas, like the [elders of the internet](https://youtu.be/iDbyYGrswtg) :)

**Comment by joshgoebel** [comment]
Language Elders sounds very middle earth or something. :)

**Comment by joshgoebel** [comment]
Related but very different I think we could also use a "themes champion"... someone who was more visual oriented (designer?) and had an interest in themes and language highlighting in perhaps a more abstract sense: https://github.com/highlightjs/highlight.js/issues/2817

**Comment by joshgoebel** [comment]
Closing discussion for now.  Anyone who wants to step up and actively maintain a grammar is welcome to be champion of record.
