### ISSUE TITLE
Variables/names are not considered tokens?

### ISSUE THREAD

**Issue by jameshfisher** [highlightjs/highlight.js#2839]
**Describe the issue**
Variables are not wrapped in their own token spans. This makes it impossible to highlight them.

**Which language seems to have the issue?**
All languages?

**Are you using `highlight` or `highlightAuto`?**
Issue is present with both

**Sample Code to Reproduce**

```
$ npm install highlight.js
$ node
> const hljs = require('highlight.js');
> hljs.highlight('c', 'int x = 5;').value
'<span class="hljs-keyword">int</span> x = <span class="hljs-number">5</span>;'
> hljs.highlight('js', 'const x = 5;').value
'<span class="hljs-keyword">const</span> x = <span class="hljs-number">5</span>;'
```

**Expected behavior**
Something like:

```
> hljs.highlight('c', 'int x = 5;').value
'<span class="hljs-keyword">int</span> <span class="hljs-name">x</span> = <span class="hljs-number">5</span>;'
> hljs.highlight('js', 'const x = 5;').value
'<span class="hljs-keyword">const</span> <span class="hljs-name">x</span> = <span class="hljs-number">5</span>;'
```

**Additional context**

Compare the [Rouge highlighter](http://rouge.jneen.net/v3.24.0/c/), which parses the above examples like this:

```
<code id="parse_code">
<span class="kt">int</span> 
<span class="n">x</span> 
<span class="o">=</span> 
<span class="mi">5</span>
<span class="p">;</span>
</code>
```

That is, variables are given the token class `n`.

**Comment by jameshfisher** [comment]
Note the same issue is present in prism.js: https://github.com/PrismJS/prism/issues/2625

**Comment by joshgoebel** [comment]
This **was** intentional.  In the past we've had some limited ideas on what we should highlight and that did not usually include variable *declarations*. We did (sometimes) highlight variables when they provide they were individually matchable with their own pattern (like `$variable`  in PHP - there is always a `$`).  See #2500.  We're more open to this now, but someone will need to put in the effort.  

Also this is likely much harder now than it will be slightly further down the road when a few parser improvements land, such as psuedo-look-behind, etc...  So we may not be ready to go here just yet, but we'd like to.  And to be clear this will be impossible for some languages since there will not be a way to detect all variables by simple pattern matching. For example: in C++ it can be hard to tell the difference between a variable init and a function definition.

Closing this as this type of work (and more) is tracked by #2500.

---

Are you interested in working on this issue and perhaps contributing some PRs?

**Comment by jameshfisher** [comment]
Ok, thanks @joshgoebel. I had much the same response on https://github.com/PrismJS/prism/issues/2625. I'm going to abandon syntax highlighting for now, as I mostly find it useful for highlighting variables/names.

I don't have the time to contribute patches atm, but may do when I come back to implementing syntax highlighting on my site!

**Comment by joshgoebel** [comment]
We'll be here.

It's possible in some languages you could do this with a catch all for identifiers - ie if it's an identifier but it's not a keyword, or attribute access, or function dispatch, then it must be a variable... that's worth asking but first we have to match all those other things first to exclude them, which is also part of #2500. :-)

**Comment by joshgoebel** [comment]
I'll agree with Prism in that highlight ALL identifiers as a single class isn't of much interest to us.  Of course (like with Prism) you could modify our grammars or CSS to get closer to such a look... but as a highlighter we're interested in knowing WHAT an identifier is:

- variable name  `var x = 5`
- function name ` function x() {}`
- function invoke `add(1,2)`
- attribute access `person.name` (name being the attribute access)

We'd likely highlight those 4 things all differently - though again with CSS one could imagine a theme that unified them all... or perhaps by hacking `classNameAliases`.  But it's not something we'd ship out of the box by default.

**Comment by jameshfisher** [comment]
My intuition is that `x` in `var x`, `x` in `function x() {}`, `add` in `add(1,2)`, and `person` in `person.name` are all examples of the same lexical class - something like "identifier".

Figuring out what the type of the value that they might refer to at runtime is a Hard Problem, and I wouldn't impose this on a syntax highlighter.

(I see an argument for `name` in `person.name` being a different class though, since it's identical to `person['name']`, rather than referring to a `name` variable.)

**Comment by joshgoebel** [comment]
> Figuring out what the type of the value that they might refer to at runtime is a Hard Problem, and I wouldn't impose this on a syntax highlighter.

Don't worry you're not imposing anything on us. :-)  In many cases it can be done with simple pattern matching (other highlighters do this also)... For many languages this gives a quite high hit rate - and results in very nice (and useful) highlighting in our opinion.  Those who disagree can substitute their own opinions simply by writing a few lines of simple CSS - or with some className aliasing.  That is part of our philosophy.  We have opinions, but most of the time we make it easy for people to extend us and assert their own opinions with a small amount of effort.

The hard cases are just random identifiers in the middle of code with little context:

```
if (x > 5 && y>45) { 
```

We're not interesting in becoming a complex expression parser so we simply don't aspire to highlight those.  I'm not sure we should either.  If someone wanted to experiment with what that would look like in various languages I'd be happy to take a look - but we still plan to highlight additional context when we can figure it out.  So if something like that every landed in core we'd still have a long lists of potential styles:

- variable
- variable.constant
- identifier
- function.dispatch
- function.title
- attribute access, etc

So someone wanting ALL identifiers to code the same would simply need to restyle the other variants.

**Comment by joshgoebel** [comment]
We do plan to tier some of these (which might help you a little) as in:

- variable
- variable.constant
- variable.property

But in this we're also restricted by legacy as-in whatever choices we make need to work well with our legacy themes/grammars/naming... So we're more likely to end up with:

- title.function
- title.class

Than say `name.function` and `name.class` because `title` has long been used for such things and would seamlessly work everywhere... A grammar or theme covering `title` would continue to work just fine but now whenever desired more nuance could be added by choosing to style `title.function` and `title.class` individually...
