### ISSUE TITLE
SUPPORTED_LANGUAGES.md table autogeneration

### ISSUE THREAD

**Issue by jonjensen** [highlightjs/highlight.js#2841]
Hello. Thanks for making highlight.js!

I noticed that some things in the SUPPORTED_LANGUAGES.md list are not complete or current. For example, it doesn't include `php8`, `c#`, `c-like`, etc.

I'd be happy to write a generator program to output the table based on the source code, so it's easy to keep current without any manual labor.

Then I noticed that the list table starts with `<!-- LANGLIST -->` and ends with `<!-- LANGLIST_END -->` which makes me think someone is already autogenerating it! But I don't see such a thing in the repository.

Would such automation be of interest if I get it working and make a pull request?

**Comment by joshgoebel** [comment]
Two thoughts: 

– How do we handle third-party languages?
– How and when does this automation get run?

The current problem is that no one thinks to update The list when changes happen, not that it’s hard to do. So just having automation doesn’t actually solve the problem unless that automation runs itself or there are some process put in place, etc. 

So if we can answer both those questions then this would definitely be interesting.

**Comment by joshgoebel** [comment]
Also some languages are really more templates like to c-like. It’s purposely not supposed to be on the list. So we need a way to filter out language like that.

**Comment by jonjensen** [comment]
@joshgoebel For third-party languages, I think we could have data for them in the generating script. It would know about the core languages itself, and third-party someone would have to program in when they're new. But given how many are core, that still removes a lot of manual labor.

The automation could be run manually, or as part of a build, I guess. Right now I know the table is out of date, but I don't know how many other things aside from what I noticed. With a manually-run script at least I just could run it and be done.

**Comment by joshgoebel** [comment]
I actually think the perfect automation here would probably leave the third-party data exactly as it is. So what you would do is open the file, read the data in between the two comments, parse it, remove all the first party languages, then add the first party languages back based on the current on desk representation of said languages, sort, and then split the output right back out between the comments. 

It’s currently a very good thing how easy it is for third-party language authors to add themselves by changing only a single file.  That makes it possible to do this using only the GitHub UI which I see as a win.  

If you were going to do this you’d want to take a look at the scripting that the build system already uses because the code to get the list of languages and aliases and such things is already written. The only part that would need to be written as the part to handle parsing and modifying the file, etc.

**Comment by joshgoebel** [comment]
Or actually it may not be that simple. Getting the aliases may not be as simple as you would think since that require actually running the language grammars directly.

**Comment by joshgoebel** [comment]
> I actually think the perfect automation here would probably...

If you want to take a stab at building out kind of what I suggested you’d be welcome to if that’s really what you wanna work on. I worry it might be harder than you think though and if you were interested in helping out in general they are probably lots of other much more pressing issues that I could point you to.

**Comment by joshgoebel** [comment]
Closing as: unneeded complexity for something that rarely happens.
