### ISSUE TITLE
(Swift) `params` does not handled nested parens properly

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2857]
In the following example:

```swift
func sizeOfRectangle(from corner1: (x: Double, y: Double), to corner2: (x: Double, y: Double)) -> (width: Double, height: Double) {
  let width = abs(corner2.x - corner1.x)
  let height = abs(corner2.y - corner1.y)
  return (width, height)
}
```

Only the part `from corner1: (x: Double, y: Double)` is highlighted as a parameter list. I assume the grammar thinks the closing parenthesis of the tuple is the closing parenthesis of the parameter list?

The grammar also doesn't support line breaks in parameter lists, so only the first line is highlighted.

I'm also wondering why the parameter list is highlighted at all? It can be really complex in Swift, so it doesn't make sense to me that it's just one color.

**Comment by joshgoebel** [comment]
> I assume the grammar thinks the closing parenthesis of the tuple is the closing parenthesis of the parameter list?

No, it's because `params` has `endsParent` so the nested params (any inside `()` group is considered more params [though it should really be unnamed] terminates as soon as the first `)` is hit because endParent fires for both and walks back up the mode tree.

To do this right you typically need a new mode.  If we had sugar for it it might look like this:

```js
          {  className: 'params',
            begin: /\(/, end: /\)/, endsParent: true,
            contains: [
              {'self', endsParent: false }, // this is magic sugar that doesn't exist plus being invalid JS, lol
              NUMBER,
```

So one has to have two modes OR remove the endsParent... I'm not sure what it's intended to do.  I mean I know what it's intended to do (end the `function`) but not why it's needed since the `{` will end the function anyways... unless perhaps you can have function declarations without bodies?  Many languages do this same trick but don't require `endsParent`.  First time I've seen it actually.

> The grammar also doesn't support line breaks in parameter lists, so only the first line is highlighted.

It most certainly does, I'm not sure what you're seeing.  There is no special handling of line breaks anywhere though.  The function is either terminated by `{` or by the closing `)` of any `params` group (or a few illegal characters).

> I'm also wondering why the parameter list is highlighted at all? It can be really complex in Swift, so it doesn't make sense to me that it's just one color.

This is something we traditionally highlight... it's up to themes to decide what to do with it... a theme that turns it all the same color probably isn't the best choice for Swift.  Our parsing is currently a tree though so it's possible for themes to style `params  > variable` differently than `variable` might appear elsewhere.  If we were going to consider changing this for individual languages I'd want to first look at all the themes and see if any of them target things inside of param groups. Right now OTTOMH only Atom One Reasonable seems to do this for ReasonML:

```css
.hljs-function .hljs-params .hljs-typing {
  color: #FD971F;
}
```

I'd be open to getting into a larger discussion about this though.  `params` is helpful for many languages because we can't/don't get into detail about what's inside params so in many simpler cases just blanketing the whole area with a class works nicely.  The more complex a language the more this starts to fall apart.

**Comment by joshgoebel** [comment]
Any time we're talking visual stuff screen grabs are often nice. :-)

**Comment by svanimpe** [comment]
Here's a screenshot:

<img width="375" alt="Screen Shot 2020-11-15 at 19 35 17" src="https://user-images.githubusercontent.com/1496250/99193509-b3713900-2779-11eb-9863-116d1fda76c2.png">

The "line break" issue was just me being confused. It's just the closing parenthesis again that ends the highlighting, not the line break.

> Are types and classes the same thing in Swift?

No, Swift also has `struct and `enum` types.

**Comment by joshgoebel** [comment]
>  It can be really complex in Swift, so it doesn't make sense to me that it's just one color.

What are some of the more complex cases?  Can I write 100 lines of code and insert an inline function as a default argument or something crazy?

Also, it truly shouldn't "all be one color"... in the best case the grammar should be enhanced to add some nuance... highlight types, labels, etc... the question is do we need the context of params to do that properly.  I feel like SOME of that content should indeed be highlighted as params, no?

For example here is the type of highlighting commonly seen:

<img width="454" alt="Screen Shot 2020-11-15 at 1 51 21 PM" src="https://user-images.githubusercontent.com/6473/99193860-aa687380-2749-11eb-87e9-434a6672b9de.png">

So for Swift perhaps only `to` `from` or `corner1` and `corner2` should be highlighted as params?  What would this look like in XCode, say?

**Comment by joshgoebel** [comment]
<img width="750" alt="Screen Shot 2020-11-15 at 1 53 42 PM" src="https://user-images.githubusercontent.com/6473/99193917-03380c00-274a-11eb-86a0-7e2f592ef889.png">

Just adding types is already much better.

**Comment by svanimpe** [comment]
Also leaving this here as a reminder for whoever picks this up:

<img width="430" alt="Screen Shot 2020-11-15 at 22 28 28" src="https://user-images.githubusercontent.com/1496250/99197290-e58e9500-2791-11eb-98b5-2bf1d33102b1.png">

Closures don't seem to be supported w.r.t. parameter highlighting?

**Comment by svanimpe** [comment]
Here's a screenshot from VS Code, which uses a TextMate grammar I believe:

<img width="575" alt="Screen Shot 2020-11-15 at 22 31 38" src="https://user-images.githubusercontent.com/1496250/99197380-782f3400-2792-11eb-8814-3243531458f8.png">

Xcode only highlights the types, not the parameter names (same for closures):

<img width="520" alt="Screen Shot 2020-11-15 at 22 33 26" src="https://user-images.githubusercontent.com/1496250/99197400-9ac14d00-2792-11eb-9974-98f5a123e0c8.png">

**Comment by joshgoebel** [comment]
> Closures don't seem to be supported w.r.t. parameter highlighting?

I'd guess not, typically we haven't supported highlighting function dispatch - though we're open to that now if it can be detected.
