### ISSUE TITLE
Is there a way to proper hightlight HTML code (including CSS and JS) ??

### ISSUE THREAD

**Issue by Neohiro79** [highlightjs/highlight.js#2884]
**Here is the Fiddle in question:**

> http://jsfiddle.net/neohiro79/zbfdhxjy/8/

Or am I missing some important script or setting?

**Comment by joshgoebel** [comment]
First none of that will work until your properly escape your HTML. Otherwise it’s just HTML not code to be highlighted.

https://www.freeformatter.com/html-escape.html

If you do that and then use the XML language to highlight the code block it should color Scripps with JavaScript and CSS with CSS automatically.

**Comment by Neohiro79** [comment]
Thanks for the quick reply. 

**So in consequence I'll better stick with [Rainbow.js](https://craig.is/making/rainbows) who finally WORKS as expected from startup:**

> https://jsfiddle.net/neohiro79/zbfdhxjy/9/

**Comment by joshgoebel** [comment]
That is a VERY bad idea and easy to shoot yourself in the foot (even if you control the code 100%).  And if you don't 100% control the code you've just opened up your site to all sorts of evil exploits.

https://jsfiddle.net/ajoshguy/dx73h1rc/

Here I am injecting JS into your page because you aren't doing proper escaping.

**Comment by joshgoebel** [comment]
I filed an issue: https://github.com/ccampbell/rainbow/issues/249

**Comment by joshgoebel** [comment]
A properly escape snippet works.  The comment will be highligted as an HTML comment.

```
<pre><code class="lang-xml">
&lt;!-- this is a html comment --&gt;
</code>
</pre>
```

**Comment by joshgoebel** [comment]
@Neohiro79 Once we get to v11 and dump the "you can include HTML" feature (requiring a plugin-in) I'll probably make changes to show an error message with a link to "educate" people when they try and include raw HTML like you were doing... so instead of just not working it'll send someone off to read and learn about WHY they need to properly escape their code.

Sadly we can't do this now since we allow HTML (for "clever uses") and it's impossible to know the users intention.  Were they including HTML on accident or on purpose... changing how this works would be a breaking change so something we'll have to push off until v11.

**Comment by Neohiro79** [comment]
I think, that's a good idea, since it will give me at least a `hint` what potentially went wrong ... ;-)
