### ISSUE TITLE
R syntax highlighting breaks at apostrophes inside comments 

### ISSUE THREAD

**Issue by vertesy** [highlightjs/highlight.js#2915]
R syntax highlighting breaks at apostrophes inside comments (language name) Short description of issue...

@Qeole asked me to move [Enlight/issues/16](https://github.com/Qeole/Enlight/issues/16).

1. Enlight uses highlight.js
2. I use Enlight inside firefox to higlight r syntax
3. When you check https://raw.githubusercontent.com/vertesy/CodeAndRoll/master/CodeAndRoll.R highlighted by Enlight in firefox
![image](https://user-images.githubusercontent.com/5101911/101834224-5c714080-3b3a-11eb-9256-1518962deb16.png)
you can see that R **syntax highlighting breaks apostrophes inside comments.** It is particularly bad for roxygen skeletons

Since I don't know anything else about Enlight nor highlight.js, @Qeole would be the appropriate person to follow up.

**Comment by Qeole** [comment]
Thanks @vertesy! Not much to add from my side. As a clarification: The add-on mentioned is used to provide syntax highlight in text files displayed by Firefox, it simply move the text into a `hljs` HTML code block, injects highlight.js into the page and triggers colouring. It does not alter the text or the way it should be highlighted, so the issue with parsing comments on the screenshot above would need to be addressed on the library side (not in the add-on itself).

The bug mentions here is not related to the add-on but to highlight.js, it just happens to impact the add-on which relies on the library. I'm happy to release a new version of the add-on with the latest version of highlight.js, if this issue is fixed. Also happy to provide more info if anything remains unclear.

**Comment by joshgoebel** [comment]
Are you sure you're library includes `r` and that you are manually specifying it with `language-r`?

I see no issues.
![Uploading Screen Shot 2020-12-12 at 12.57.02 PM.png…]()

**Comment by vertesy** [comment]
You are right, it was on auto-detect and I think it detected PHP.

It is unexpected, in particular because I selected use file extension.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/5101911/101993124-4c7f6b00-3cb8-11eb-892b-e72661bfb341.png">

auto-detect  options:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/5101911/101993128-628d2b80-3cb8-11eb-9fdb-92e0efdefa7b.png">

Thank you guys!

**Comment by Qeole** [comment]
Oh, detection from file extension is proper to the add-on. Because there are so many languages supported by highlight.js, I just recognise [a few of the most common file extensions](https://github.com/Qeole/Enlight/blob/master/scripts/enlight-content.js#L96). I don't want to do it for all languages, but if it's really too annoying in your case we can probably add it for R, too.

**Comment by joshgoebel** [comment]
@Qeole Many times (but not always) the extension will be included in the list of `aliases` for a grammar... or the name itself is the extension... you might want to consider taking this into account vs/plus hard coding a list...

**Comment by Qeole** [comment]
Interesting, I'll have a look. Thanks!
