### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by rxaviers** [highlightjs/highlight.js#292]
Consider adding Browser Support on the documentation.

As a baseline of the Object.create use, we have: (according to [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create))

| Chrome | Firefox (Gecko) | Internet Explorer | Opera | Safari |
| --- | --- | --- | --- | --- |
| 5 | 4.0 (2) | 9 | 11.60 | 5 |

**Comment by igorbelikov** [comment]
@isagalaev I think that the table of supported browsers should be added, so it's important when using your library in some less serious application and thank you for your work.

@rxaviers Thank you for reviewing supported browsers

**Comment by brianvoe** [comment]
So I think a reason to add browser support is because with a javascript project I am creating now i want to be able to create docs for it and if the browser support I have for my package cant be shown in docs cause the code highlighting doesnt support that browser, then it makes it look like my javascript package doesnt work in those browsers as well.

Right now my docs dont work in any version of edge or ie. 😞 
JS error on this (object doesnt support forEach) EDGE 14
"e.querySelectorAll("code").forEach"
