### ISSUE TITLE
Polynomial backtracking

### ISSUE THREAD

**Issue by svanimpe** [highlightjs/highlight.js#2928]
I'm running into issues with errors related to polynomial backtracking. For example, the following regex works but results in an error during testing:

```
lookahead(concat('\\s*(', Swift.identifier, '\\s*){1,2}\\s*:'))
```

Basically, I need to check if the upcoming code consists of two identifiers, separated by whitespace, and followed by a colon. If need, I need to match them as identifiers (function params in this case), not keywords.

The first error I got was caused by 0xFEFF being included in `Swift.identifier` (although that never gave me any errors before). When I removed that from the possible characters, the next error complained that I couldn't use `\s*`.

What's going on here?

**Comment by svanimpe** [comment]
The following workaround does seem fine:

```
begin: either(
  lookahead(concat(Swift.identifier, /\s*:/)),
  lookahead(concat(Swift.identifier, /\s+/, Swift.identifier, /\s*:/))
),
```

Is this because I'm using regexes instead of strings?

**Comment by joshgoebel** [comment]
> The first error I got was caused by 0xFEFF being included in Swift.identifier

You'd need to show me the specific error generated by the test suite.

> lookahead(concat('\\s*(', Swift.identifier, '\\s*){1,2}\\s*:'))

The problem here is your last two `\\s*`... there are a polynomial number of ways that they could match a long string of spaces...  The space could be matched by:

```
(', Swift.identifier, '\\s*)
```

Or the space could be matched by:

```
\\s*:'))
```

So given 100 spaces it's unclear if those spaces belong on the left or right, and in a worst case scenario (when it's difficult to find a match) the regex engine must exhaust ALL the possibilities... rewriting it as you've done to remove the ambiguity is correct idea.

But what is that last \\* needed?  It should already be handed by the prior rule, no? Why not just:

```
lookahead(concat('\\s*(', Swift.identifier, '\\s*){1,2}:'))
```

The space before the : will be matched by either the very first \\s* or by the identifier rule, no?

**Comment by joshgoebel** [comment]
I suggest reading up on backtracking (and the error generated by the test suite make a lot of sense once you understand the bigger picture), but it's a heavy topic.  I've known of it forever but only recently gained a much deeper understanding of it as I fixed so many of our issues and added those tests.

**Comment by svanimpe** [comment]
Got it! Thanks.
