### ISSUE TITLE
hljs only working after reloading the page

### ISSUE THREAD

**Issue by jvel07** [highlightjs/highlight.js#2963]
Hi, there! I really love this project. I am having issues tho. The highlighting only works after reloading the page, before reloading it looks like this:

![image](https://user-images.githubusercontent.com/10247930/104836159-32830a80-58ac-11eb-92b0-0380c25fa58f.png)

I am using hljs in this way at the <head> of my html file:

```
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/railscasts.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
```
When I inspect the element shown above (before reloading the page) the 'code' tag seems like it's not taking it from hljs as you can see in the image below:

![image](https://user-images.githubusercontent.com/10247930/104836466-75de7880-58ae-11eb-991b-2ab0685a87f6.png)

After reloading the page it looks like this (so it seems to be working):

![image](https://user-images.githubusercontent.com/10247930/104836446-5cd5c780-58ae-11eb-9648-05ad9490d74f.png)

Am I missing something in order to get it working without reloading the page?

Thanks,
jvel

**Comment by joshgoebel** [comment]
First, I would highly recommend upgrading to the latest release 10.5.  Older versions have potentially serious security issues - not to mention all the grammars fixes and improvements as well.

Is the HTML content in question here fully static or is it being rendered at all by Javascript at run-time?  Generally the behavior you're seeing really is quite strange so I'd suspect some issue with your setup - rather than the library itself.  Perhaps if sometimes the page is not fully-rendered at the time HLJS runs - then it would not see the block and could not highlight it.

It's harder to guess why this would *always* be different on the first pass than the second though. Are there errors loading the JS the first time? Are there errors in the Javascript console?

**Comment by jvel07** [comment]
Okay, I upgraded to the 10.5.0 version. 
The page is actually a static one. And no, the console is only showing a error not related to hljs:

`swup.min.js:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#.' is not a valid selector.
`
Is there a way to force a reload of hljs?

**Comment by joshgoebel** [comment]
>  And no, the console is only showing a error not related to hljs:

And is that different from the first load vs subsequent?

> Is there a way to force a reload of hljs?

I'm not sure exactly what you mean.  You could just wait and call `hljs.initHighlighting` instead of the onload stuff, but if you're truly just a static page I'm not sure why that would be necessary.

Can you just point us to the actual page in question so we could look at it?

**Comment by jvel07** [comment]
Thanks for your help.
> And is that different from the first load vs subsequent?

So I noticed that this error shows up when I click on the menu panel only. It seems to go away after navigating to the page from the menu.

Sorry, I am not an expert in HTML, etc... It is not my field. I think my site is static in the way that I have separate html files for each page, etc. It uses some js plugins tho.

>Can you just point us to the actual page in question so we could look at it?

Of course. So, you go to [joseegaslopez.com](url) and then you click on the menu/blog. Inside blog, you click on the very first one and there it is. The python block codes only load properly after reloading the page.

Note: I also had troubles with the horizontal scrollbar, when the lines of code are too wide, they can't be read. The scrollbar is not showing up. But maybe I have to open another issue I think?

**Comment by joshgoebel** [comment]
This doesn't look static at all... indeed the whole website disappears if I turn off Javascript.  I'll continue to guess that you're messing up something in your load ordering (that Highlight.js is loading too EARLY sometimes - and when it ). It looks (at first glance) like you're loading your blog content dynamically - so you'd also need to highlight it dynamically - after it's loaded... 

This will likely require writing Javascript and integrating that with whatever you're using to load/render your blog articles once they are clicked.

**Comment by joshgoebel** [comment]
>  I also had troubles with the horizontal scrollbar, when the lines of code are too wide, they can't be read. The scrollbar is not showing up. But maybe I have to open another issue I think?

Scrollbars is a purely CSS issue.  I'd suggest reading up on `overflow` and friends.

**Comment by joshgoebel** [comment]
Closing as this seems to be an issue with dynamic content rendering - not any issue with our library.  The solution (for any type of dynamic rendering) is to only call `highlightBlock` after the `pre/code` block has been added to the DOM - which likely means some custom JS.
