### ISSUE TITLE
github.com/highlightjs/gear-lib.git not available

### ISSUE THREAD

**Issue by SavchenkoAlexander** [highlightjs/highlight.js#3094]
Hi,

When I run command  'npm clean-install' on branch 9-18-stable, it fails.

npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/highlightjs/gear-lib.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

Can you restore github.com/highlightjs/gear-lib.git ?

I can't use latest version of highlight.js because I use it with Internet Explorer.

Thanks in advance.

**Comment by joshgoebel** [comment]
Right upfront I feel i must mention that 9.18 is no longer supported.

Then regarding `gear-lib`, I believe it's gone for good - it's certainly not something I have laying around anywhere (it was a custom patch of gear I believe).  It's also been a little while I think since I deleted it fully...  But it's only a dev dependency... _it's not needed to use the library at runtime._  You should be able to `npm install` into a project without gear or gear-lib.

**Comment by Himura2la** [comment]
We need to build highlight.js with custom language set from time to time, so I guess dev dependencies are also required...
And no, `npm install` does not work:

```
$ npm install
npm WARN tar ENOENT: no such file or directory, open '/home/himura/Documents/Git/highlight.js/node_modules/.staging/rollup-afeafec6/dist/rollup.d.ts'
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/highlightjs/gear-lib.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/himura/.npm/_logs/2021-04-01T18_00_26_219Z-debug.log
```

Can you please recover the repo or do something to fix the build.
Unfortunately, we have to support IE11, so we can't switch to version 10 yet...

**Comment by Himura2la** [comment]
Can you please at least share your patch to `gear-lib` so that we can deploy this fork on our side...

**Comment by joshgoebel** [comment]
> The non-supported versions should at least work if nothing changes outside.

_To be clear breaking it wasn't intentional._  I merely forgot about this terrible Git dependency 9 has on those repositories...  They have been archived for a long time and nothing has come up regarding them so I just finally deleted them a while back. I know at least one person transpiles us to ES5 using Babel. I can't say that's supported, but it might be something worth considering vs continuing to use version 9.

> Can you please at least share your patch to gear-lib so that we can deploy this fork on our side?

I have no idea what patches we did or did not apply.

---

Here are the `gear` and `gear-lib` dependencies from an old 9.15.10 checkout I found... 

[gear.tar.gz](https://github.com/highlightjs/highlight.js/files/6246079/gear.tar.gz)

**Comment by Himura2la** [comment]
Thank you, I hope it should be enough.
Transpilling to ES5 using Babel sounds promising, it would be great to see the babel config. Maybe we even tried to do it, but that did not raise easy enough

**Comment by joshgoebel** [comment]
I considered vendoring these both right now into the core repository (since now that they are gone I really don't want to add them back) and fixing the build... but as soon as I did `npm install` I was reminded:

```
12 vulnerabilities (10 low, 1 moderate, 1 high)
```

And that just reminded me (of only a few of the reasons) why we've happily left v9 behind. So while breaking the build wasn't intentional, now that it's broken I'm not sure we should fix it.  I'd rather it be a little painful and perhaps encourage some people to look *harder* and finding a way to upgrade to v10.  Perhaps that means transpiling, perhaps for some it means re-evaluating if IE11 is *truly* still a requirement.  Perhaps that's true for you, but perhaps for some it's not.  It's definitely "in flux" as more and more people drop support as time goes on.

This is also really an edge case in that it's only the building that's broken... anyone can still get the old pre-built versions from npm or CDN and they work just fine (other than all the potential security issues).

If someone would like to fork v9 and take responsibility for it, that'd be fine... perhaps you'd like to do that yourself?  ...but I don't think we have the desire or bandwidth.  At this point v10 has been out for over a year and v11 is about to be released.

Considering this issue resolved.

**Comment by noraj** [comment]
There is still the same problem with 10.7.0 but hopefully now I don't need to build from source anymore since `@highlightjs/cdn-assets was introduced.

**Comment by joshgoebel** [comment]
What is the "same problem" with 10.7?  It has no "dead dependencies" that I'm aware of?

**Comment by noraj** [comment]
When running `node scripts/build.js -t node` I get the same issues about gear/gear-lib not exiting (by default github consider them private repos and so try to fetch them via ssh and ask for creds).

**Comment by joshgoebel** [comment]
> When running node tools/build.js -t node I get the same issues about gear/gear-lib not exiting

Then you're building 9, not 10.  10 does not refer to these things at all.

**Comment by noraj** [comment]
```
$ cd /tmp
$ git clone https://github.com/highlightjs/highlight.js.git
$ cd highlight.js
$ git checkout 10.7.2
$ npm i
$ node tools/build.js -t node                                                                                                                                                                                                    00233d63 ✔
Starting build.
Finished build.
Writing styles.
Writing package.json.
Writing languages.
...............................................................................................................................................................................................
Writing highlight.js
```

Right there must have been artifacts from my 9 to 10 upgrade.

**Comment by joshgoebel** [comment]
Of course I released v11 just hours ago. :)
