### ISSUE TITLE
[Request] LibreJS license block

### ISSUE THREAD

**Issue by Caduser2020** [highlightjs/highlight.js#3107]
**Is your request related to a specific problem you're having?**
Users using the [LibreJS](https://www.gnu.org/software/librejs/free-your-javascript.html) plugin cannot run highlight.js scripts.

**The solution you'd prefer / feature you'd like to see added...**
Add to top of generated file:
```js
// @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause License
```
Add to end of file:
```js
// @license-end
```

**Additional context...**
The magnet URI (`magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt`) can be opened in a BitTorrent client to retrieve a copy
of the GNU AGPL 3.0 license. Section 3.2.2.1 from the above [link](https://www.gnu.org/software/librejs/free-your-javascript.html) has
a list of magnet URIs for various free software licenses.

**Comment by joshgoebel** [comment]
At first glance forcing every library in the world to tag itself like this seems like the wrong approach - and does nothing for the potentially thousands of websites using older untagged versions of our library.  Are those websites just permanently broken with LibreJS until one day they might finally upgraded to a tagged copy?

_We already include easily parsable license information at the top of our distributable and have for some time._  We also allow (and encourage) an ecosystem of 3rd party plugins and grammars.  Tagging only the core library so that all our 3rd party integrations break (because they aren't likewise tagged) seems problematic.  We then create a situation where things "half work" - which is more frustrating than being entirely broken.

I'm curious what is the criteria for being included in:

> LibreJS detects many free libraries by default.

We are a free library with over 100 million downloads per month - one of _only two_ popular highlighting libraries in JS that I'm aware of.

**Comment by Caduser2020** [comment]
I was not aware that there was already some parsable information. This should be a bug in LibreJS, then. Maybe contact [bug-librejs@gnu.org](mailto:bug-librejs@gnu.org) also to be added to the free library list?

**Comment by joshgoebel** [comment]
```
  /*
  Highlight.js 10.7.1 (55dd7a65)
  License: BSD-3-Clause
  Copyright (c) 2006-2021, Ivan Sagalaev
  */
```

I've seen other libraries do similar and it seems like this type of thing should be respected without forcing everyone to adopt an arbitrary standard (that isn't even a standard).

> Maybe contact bug-librejs@gnu.org also to be added to the free library list?

I would assume anyone could lodge such a request?  I'm not sure this type of blocking is the right approach (haven't given it much thought), so this isn't high on our list of priorities.

**Comment by allejo** [comment]
I think the problem LibreJS is trying to solve isn't one that really needs to be solved? Seems to me like it's introducing more hurdles for library maintainers than benefits.

I think us following the `/*!` pattern that other giant libraries use (e.g. jQuery and Bootstrap) will suit us just fine if we want to specify our license in builds.

- https://code.jquery.com/jquery-3.6.0.min.js
  ```js
  /*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.org/license */
  ```
- https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js
  ```js
  /*!
    * Bootstrap v4.5.2 (https://getbootstrap.com/)
    * Copyright 2011-2020 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)
    * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
    */
  ```

**Comment by joshgoebel** [comment]
I'm happy to add a `!` if it conveys some magic meaning, but I don't see a real pattern there. :-)

Is there some magic to putting the copyright in the middle?  I don't mind changing the order.

**Comment by allejo** [comment]
No magic about the copyright order or anything, just meant to point out examples of other libraries. As for the `/*!`, [it tells minifying tools to preserve the comment as is and not remove it](https://stackoverflow.com/a/11248430).

**Comment by joshgoebel** [comment]
AH duh, I knew that. :-)  Our header process just adds the header itself at the last minute so it can contain up-to-date Git SHA and version, etc... but I'd be happy to add a `!` to that so something else is less likely to strip it away. Did you see the above? We already do this:

```
  /*
    Highlight.js 10.7.1 (55dd7a65)
    License: BSD-3-Clause
    Copyright (c) 2006-2021, Ivan Sagalaev
  */
```

**Comment by allejo** [comment]
Sorry, allow me to clarify what I was trying to get at on this topic:

Other giant libraries like jQuery and Bootstrap aren't following this LibreJS pattern. So that would give us no motivation to follow suit. Other libraries have copyright notices in these formats, just like us. Oh hey, except maybe the `!`.

**Comment by joshgoebel** [comment]
Agree, I think the proper solution here is for LibreJS to find and parse header comments that already exist -  say by using common RegEx patterns, the same way GitHub attempts to parse LICENSE files, etc... or to maintain a master list of libraries that can be maintained - not by getting thousands of separate libraries to add a very specific annotation.
