### ISSUE TITLE
(python-repl) Can't find a way to highlight python-repl syntax

### ISSUE THREAD

**Issue by fehaa** [highlightjs/highlight.js#3110]
**Describe the issue**
Hello everyone! I'm trying to highlight some python-repl snippets but I can't find a way to do it. Maybe I'm doing something wrong even reading the documentation and seeing the examples. I've also searched for the same problem in the issues but didn't find anything related.

**Which language seems to have the issue?**
python-repl

**Are you using `highlight` or `highlightAuto`?**
highlight 10.7.2

**Sample Code to Reproduce**

https://jsfiddle.net/gzcuw8qb/

**Expected behavior**
Code highlighted like this:
![image](https://user-images.githubusercontent.com/5955068/113604709-05790500-961c-11eb-830b-f3baffba110f.png)

**Additional context**
I'm using a downloaded version of highlight in a local HTML/CSS/JS project but I already tried to use CDN resources and it didn't work for me as well.

**Comment by joshgoebel** [comment]
Thanks for this report, but the problem seems to be your usage or your application.  This is working as expected.

https://jsfiddle.net/ajoshguy/cjhvre2k/

Your fiddle was broken in several ways.  It was using version 9.18 URLs and Python REPL's must start at the beginning of the line... when I updated the Fiddle it not works correctly.

```
# this is a REPl
>>> print(...)

# this not
                  >>> print(...)
```

**Comment by fehaa** [comment]
My mistake, sorry! I changed my code and now it's working as you showed! 😁 

Not starting my code at the beginning of the line was the problem, thanks for replying!
