### ISSUE TITLE
Surround variable names

### ISSUE THREAD

**Issue by andreas-web** [highlightjs/highlight.js#3179]
Is it possible that you surround names of variables and constants (e.g. in JavaScript after the keywords const, let and var) with a <span> so that you can give them their own style?

**Comment by joshgoebel** [comment]
It's a bit weird though to highlight `widget` only in `var widget` but then not later in `widget = "XJR"`... they are both "variable"... so generally we try to avoid being inconsistent. And there is no great way to recognize variables everywhere else they are mentioned.

**Comment by andreas-web** [comment]
Of course I meant everywhere. But the first occurrence can be recognized by the keywords. Then the recognized strings can be searched for and surrounded in the complete code.

**Comment by joshgoebel** [comment]
Same problem.  There is no guarantee that the variable declarations are even within the snippet of code we are being asked to highlight.  Some might be, some might not be, or none might be.  So consistent behavior is impossible.  And that's not what we do.  We're a pattern matcher and try to highlight with *minimal context* (as much as possible).  We don't "remember" things on purpose.  So remembering we saw a variable earlier is out of scope.

**Comment by joshgoebel** [comment]
If you wanted to try writing a plugin or something that did this as a 2nd pass over the text after we highlighted it that might be interesting to see.  Closing this issue as out of scope.

**Comment by taufik-nurrohman** [comment]
I was experimenting with a simple tokenizer to make other regex-based syntax highlighter, but at the moment it&rsquo;s not so up-to-date since I haven&rsquo;t had the time to make it a priority.

https://taufik-nurrohman.js.org/ash/

**Note:** On the demo section, select _JavaScript_ then check the _Inspect_ option to see that variable names can be wrapped as well.

In general, we can wrap the variable after all known tokens have been successfully wrapped. I don&rsquo;t know what happen behind Highlight.js tokenizer, however, here I am just sorting the priority of the tokens to match and then making the last token as variable using simple pattern such as `[\w$]+`.

The order is:
 1. `comment`
 2. `string`
 3. `boolean`
 4. `keyword`
 5. `number`
 6. `punctuation`
 7. `constant`
 8. `variable`

**Comment by joshgoebel** [comment]
> In general, we can wrap the variable after all known tokens have been successfully wrapped. 

This approach might even work for us in Highlight.js for *some* grammars, because it doesn't depend on context or state.
