### ISSUE TITLE
Vue plugin doesn't work with highlight() change

### ISSUE THREAD

**Issue by FeixuRuins** [highlightjs/highlight.js#3185]
**Describe the issue/behavior that seems buggy**

The Vue plugin was not updated to accommodate the breaking change in #2277:
```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

**Sample Code or Instructions to Reproduce**

```vue
<template>
  // ...
  <highlightjs
    language="javascript"
    :code="codeSnippet"
  />
  // ...
</template>

<script lang="ts">
  import Vue from 'vue';
  import { vuePlugin } from 'highlight.js';

  Vue.use(vuePlugin);

  export default {
    data: () => ({
      codeSnippet: 'const foo = 5;'
    })
  }
</script>
```

**Expected behavior**

It should work.

**Additional context**

I'm using Nuxt.

**Comment by joshgoebel** [comment]
> the breaking change in #2277:

There is no breaking change, a console warning is not a breaking change.

---

A PR would be accepted against the `10-stable` branch, but this plugin is no longer part of Highlight.js anymore and has been moved into it's own repo for v11 so that patch probably should happen there [also]. 

https://github.com/highlightjs/vue-plugin

**Comment by mhio** [comment]
plugin PR... https://github.com/highlightjs/vue-plugin/pull/4
