### ISSUE TITLE
`<br>` being removed in version `11.2.0` 

### ISSUE THREAD

**Issue by AyhamAl-Ali** [highlightjs/highlight.js#3302]
**Describe the issue/behavior that seems buggy**

`<br>` are being removed when I updated to version `11.2.0`
I am using `<pre> <code>` but I have a simple `Minify Java code`_(because I am generating my code using a Java code)_ that simply just removes all `\n` therefore I had to use `<br>` and it works perfectly in version `10.7.2` but once I updated to version `11.2.0` it removed all the BRs and my code became 1 line

**Sample Code or Instructions to Reproduce**

Test this code and you will see everything
https://jsfiddle.net/Ldqsy58t/1/
- First time you run it and you will see no new lines
- Then go to the end of the HTML code and disable the version `11.2.0` and enable the version `10.7.2`
- Newlines will come back :)

`10.7.2`
![image](https://user-images.githubusercontent.com/20037329/128617399-0a6a5cf7-1546-418c-a777-ca30279148da.png)
![image](https://user-images.githubusercontent.com/20037329/128617475-7d4e24dd-277a-4843-aa53-17fa5ba3586c.png)

`11.2.0`
![image](https://user-images.githubusercontent.com/20037329/128617429-dcd7ca0f-ffe9-4c2c-89f8-a6c87f15437d.png)
![image](https://user-images.githubusercontent.com/20037329/128617434-3cfa691e-067d-4135-a464-9eadd72401cf.png)

**Expected behavior**

`<br>` should stay and not be removed

**Comment by joshgoebel** [comment]
Please see https://github.com/highlightjs/highlight.js/issues/2889.

**This new behavior is intentional.**  We no longer support mixing HTML into content as it can lead to security issues - and this can be done quite easily enough with plugins (the latest versions of v10 used internal plugins just to verify this is indeed the case) - so it has been removed from core.  

HTML will now be silently stripped and a warning will be logged to the console. (which is what you are seeing)

>  that simply just removes all \n therefore I had to use <br>

I'm not sure HOW you get all those BRs in the content, but the simplest solution would be to replace all the `<br>` with actual line breaks before asking us to process the content in question.  You could perhaps do that with a `before:highlightElement`.

**Comment by AyhamAl-Ali** [comment]
Oh, I see. I have just kept my `10.7.2` version for now maybe later I will use a plugin to solve this. Thank you for your quick response.
