### ISSUE TITLE
[Request] Provide context to the parser of additional code either above or below the highlighted segment

### ISSUE THREAD

**Issue by tomasreimers** [highlightjs/highlight.js#3303]
(This is a continuation of https://github.com/highlightjs/highlight.js/issues/424)

I would like to be able to better style my code (specifically I have a diff view, and I would like to not render parts of the content which weren't changed, however those parts may be necessary context for the parser to highlight appropriately).

I've read https://stackoverflow.com/questions/64280814/how-can-i-correctly-highlight-a-line-by-line-code-using-highlight-js-react. From what I can tell there are two approaches there: 

1. Parse the generated HTML: while I could parse the generated HTML and remove the unwanted sections, I guess it feels a little counter-intuitive to me to go code -> AST -> HTML string -> AST -> HTML string. 
2. Use the internal emitter API: if I'm going to build on an internal API I may as well just use the continuations the way is advocated for above in https://github.com/highlightjs/highlight.js/issues/424 by using this internal function: https://github.com/highlightjs/highlight.js/blob/main/src/highlight.js#L183 (however, from what I can tell this API seems discouraged for public use).

I'm more than happy to extend / contribute here, I am just trying to get a handle on the design decisions made so I know what makes the most sense. Specifically, why did you dislike the continuations API, what if the continuation were opaque to the user? Would it still be bad?

**Comment by joshgoebel** [comment]
>  I guess it feels a little counter-intuitive to me to go code -> AST -> HTML string -> AST -> HTML string.

This isn't quite correct (depending on perspective) - _that there is *currently* something resembling an AST as a purely internal concern_.  This however has not always been the case in the past and may change again in the future (switching back to emit directly to string).  The emitter API is likely to stick around, but technically there is NO real need for us to build an AST at all... At one time I might have considered exposing the AST we have internally, but `lowlight` already does a great job in that regard and I believe smaller tools doing fewer things is better (unix philosophy).

So, truly for outside purposes there exists **only** `Code -> HTML`.  If what you want is `Code -> AST` I'd consider something like [lowlight](https://github.com/wooorm/lowlight) which makes public API guarantees - despite actually being built on our private API (it's a quite stable API, one that saw zero changes from v10 to v11, but it is still declared private).

>  build on an internal API I may as well just use the continuations the way is advocated for above

It's not only discouraged it is deprecated in v10 and entirely gone in v11.  This was done to allow us flexibility in fully rewriting the parser internals during the v11 series - and because it's simply not our core competency.  It is not our goal or desire to be a generic code parsing library.  Our two main goals are:

- Parse **complete** snippets of code, generating HTML
- Detect language type by pattern analysis

You can do a lot within [and on top of] that framework (including many line by line use scenarios), and we're happy to see people do all sorts of fun and crazy things, but we're really not well suited for some things (and hence don't support them):

- live code editors
- partial parsing or "driving" the parser (which is what the few people using continuations tended to use them for)

I'd suggest that in many cases (perhaps not yours) this partial parsing isn't TRULY necessary and the approach I outline in the stack overflow issue works just fine.  It's certainly what those I've spoken with doing line-by-line stuff (that can't be solved with trivial CSS) is switching to when they adopt v11.


--- 

> Specifically, why did you dislike the continuations API

"Less is more" and the desire to rewrite the parser - perhaps in ways where is not even possible (or very difficult) to provide state information since it might be hidden inside a recursive stack trace, etc... since we can't break the public API  between minor releases (semver) the it simply had to go with the v10 -> v11 transition. 

> what if the continuation were opaque to the user? 

You mean if we said "you can make no guarantees about this object or it's properties"?  I'd argue that's technically ALWAYS been the case (IMHO) - that the state object details are purely internal.  I have never considered the object internal public API, so not I don't think this makes a worthwhile difference.

We're simply not interested in people "driving the parser"... we want the black box.  Driving is added complexity that simply is not required for our primary use cases.

**Comment by joshgoebel** [comment]
Also these "drive the parser" line by line solutions are AFAIK fundamentally broken (in an absolute sense).  Most I've seen pass us a line at a time leaning heavily on continuations... _This works in many, many simple cases, but is not a complete or correct solution._  We have grammars with regex that look forward MULTIPLE lines to make decisions... so any "incremental" parser truly needs not only the current line (and prior context) but also ALL remaining lines/content... 

Without this information:

1. the WRONG rule could match because there isn't enough multi-line look-ahead (making line-by-line parsing yield entirely different results)...
1. no match could be found (despite an in scope match being available on future lines)... this would terminate the mode too early
1. entire matches are missed completely because the match MUST consume multiple lines (see multi-line strings in many grammars)

I assume perhaps people are doing some hacks for point 2, but it seems unclear to me that if you started [given parent mode A and child mode B]  in mode B and your end continuation was mode A you could be certain whether mode B had truly ended or if you'd just not found a match due to incomplete data, or some other case.

---

We're also slowly switching from lots of nested modes to more complex regex that often match larger chunks of multi-line data (multi-line strings are the best example) - and this is known to have poor interactions with these non-correct "drive the parser"  solutions.  People have opened issues on this in the past, and this is simply not our problem - we do not support or claim to be useful in these cases - and now we're making that clear by removing the API completely.

**Comment by tomasreimers** [comment]
@joshgoebel , incredible thank you for this! This is a wonderful, wonderful, wonderful write-up. 

This makes a lot of sense; I think the key context I was missing was that you do multi-line lookaheads; thus making line-by-line continuation passing non-viable. 

I'll go ahead and do two things: 
1) Consider building on top of lowlight instead 
2) Look into building a parser that does what you outline in the SO post (take the HLJS output, break it up by line, then fix any HTML by tracking open and close tags). 

Once again, thank you! This is super helpful context.

**Comment by joshgoebel** [comment]
> Look into building a parser that does what you outline in the SO post 

If you're interested in helping the community writing that as a plugin might be helpful for others... you could simply rewrite the HTML in `after:highlightBlock` (into discrete lines), then allowing another plugin stacked up top to do further work (add line numbers, etc)...

There is already code floating around somewhere as other libraries have implemented this approach... it's really only 5-10 lines of code to do this properly - since the HTML we generate is clean and predictable.  

Closing as answered.
