### ISSUE TITLE
(js) Curly braces show exceptions,{} shows &#123; The & # 125;

### ISSUE THREAD

**Issue by Lauweal** [highlightjs/highlight.js#3317]
**Describe the issue**

**Which language seems to have the issue?**

**Are you using `highlight` or `highlightAuto`?**

...

**Sample Code to Reproduce**

**Expected behavior**

**Additional context**

**Comment by Lauweal** [comment]
![image](https://user-images.githubusercontent.com/54409768/131428388-6a541c74-edb9-47ff-a1e4-d22d3f4afdfe.png)

**Comment by joshgoebel** [comment]
I'm not sure what you're trying to show us here... and your description is entirely empty.  Please fill out the template fully if you'd like us to try and help you.

**Comment by Lauweal** [comment]
When I created the blog with hexo, I needed to insert js code blocks in the middle, but I found that {} was converted to &#123; And the & # 125; . As shown above, I tried modifying the source code in node_modules and found that I could fix the problem. So, I'm confused.

**Comment by joshgoebel** [comment]
I'd say your problem is with Hexo or double-escaping or something.  Highlight.js expects the content inside a `<code>` element to be properly HTML escaped - which at a minimum includes `<` and `>` but MIGHT also include other things... it certainly can include `{}` in their escaped forms (though this is not required).

You can confirm this easily with the DOM in a browser console... load an element with valid HTML, then call it's `textContent` property - this is how Highlight.js retrieves the content to be highlighted from an element.

<img width="394" alt="Screen Shot 2021-09-01 at 12 08 35 AM" src="https://user-images.githubusercontent.com/6473/131610326-d9fb5e6a-387e-42de-a5d3-14865f108557.png">

If you can reproduce this with a jsfiddle with ONLY Highlight.js (to show that its' our bug) we'd be happy to look into it, but right now this seems a problem with your code/implementation, not the library itself.  Asking on a Hexo related support channel might yield better results - and if someone more knowledgeable in Hexo thinks it's truly our problem and they can make a reproducible test case then also happy to look into that.
