### ISSUE TITLE
(Haskell) Quotes aren't escaped correctly

### ISSUE THREAD

**Issue by AusCyberman** [highlightjs/highlight.js#3355]
**Describe the issue**
Placing a quotation mark inside of single quotes thats escaped, `'\"'`

**Which language seems to have the issue?**
haskell

**Are you using `highlight` or `highlightAuto`?**
Unsure, it's in discord, im assuming highlight
...

**Sample Code to Reproduce**
```
char '\"' etc etc
```

**Expected behavior**
```hs
char '\"' etc etc
```

**Additional context**

**Comment by joshgoebel** [comment]
Our Haskell grammar only includes double quoted strings, there is currently no mention of single quoted strings ever being a possibility.  

- Could you point to some docs on this?
- Any change you might be willing to work on a PR?

**Comment by Melvar** [comment]
The single-quoted things are character literals, not string literals. See [the Haskell report](https://www.haskell.org/onlinereport/lexemes.html#lexemes-char) for their syntax. Both character and string literals support a number of escape sequences not commonly found in other languages. You could probably ignore all of those for highlighting in most cases …
However, note that normal identifiers may also contain single-quotes (e.g. `a'b'` is a single identifier, not identifier `a` + char literal), and certain extensions (for which the GHC docs may need to be consulted) also make use of single-quotes prefixed onto identifiers (e.g. `'not` and `''Bool` name-quoting of value and type), so it’s important to note that while `'a'` is always a char literal, `'ab'` is a name-quotation of the identifier `ab'`. `'a'b` is a character literal followed by identifier `b`, not a name-quotation of identifier `a'b`.
Single-quotes in Haskell are commonly mishandled by highlighters because of this complexity.

**Comment by joshgoebel** [comment]
So it sounds like if we just consume identifiers first (to prevent `'` inside of them from triggering character literals)... then consume character literals... (our matcher engine does match regex in sequence)

- `a'b'c'd'e'` (match identifiers)
- `'b'` (match character literal) (knowing the most popular escapes would help)
- IF we care about name quotations `'ab'` then stuff like `'not` and `''Bool` might be problematic unless there is a list or we can terminate them a known demarcation (whitespace, known list of operators, etc).

The big worry is hitting a `'` and getting stuck looking for a `'` that we will never find...  I think this would only be an issue if we try to match name quotations (which I'm not sure we need to?)

@Melvar Any chance you'd like to try your hand at a PR?

**Comment by AusCyberman** [comment]
> 
> 
> Our Haskell grammar only includes double quoted strings, there is currently no mention of single quoted strings ever being a possibility.
> 
>     * Could you point to some docs on this?
> 
>     * Any chance you might be willing to work on a PR?
I would be willing to, once I do some research into how parsing is done at all, what part of the grammar is parsing the single quoted chars in the first place

**Comment by joshgoebel** [comment]
No, that's double quoted. https://github.com/highlightjs/highlight.js/blob/1a258a3e72dce8b6534e28a741cfcd7d813463dd/src/lib/modes.js#L51

We match single quotes in only 3 places I see:

- `CONSTRUCTOR`
- inherit from `TITLE_MODE` in two places

The latter is probably already intended to prevent this but I'd wager the regex isn't sufficient enough or it's not being deployed in all the correct contexts.

---

If you were confused on the grammar itself but could even contribute just a list of tests cases and desired behavior for them that we could add to our test suite that'd be a start:

```
-- character literal
'a'
-- something else, etc...
a'b'c
```

O

**Comment by joshgoebel** [comment]
@AusCyberman Still interested in helping out?  trying to figure out what we might be able to get into the 11.5 release.
