### ISSUE TITLE
Fortran problems with "word" and "len"

### ISSUE THREAD

**Issue by Beliavsky** [highlightjs/highlight.js#3450]
I am using the Carbon app to tweet Fortran code, which uses highlight.js. It works pretty well, thanks. For the code [here](https://twitter.com/fortrantip/status/1477632693617799169) it should not highlight any part of `words`, and it has trouble with "len". `len_trim` is an intrinsic function that should be highlighted, and `nlen` and `len_sep` are just variable names and should not be highlighted. Here is the Fortran code.

```
module m
contains
function join(words,sep) result(str)
! trim and concatenate a vector of character variables,
! inserting sep between them
character (len=*), intent(in)                                   :: words(:),sep
character (len=(size(words)-1)*len(sep) + sum(len_trim(words))) :: str
integer                                                         :: i,i1,nw,nlen,len_sep
if (nw < 1) return
len_sep = len(sep)
i1 = 1
nw = size(words)
do i=1,nw
   i2 = i1 + len_trim(words(i)) - 1
   str(i1:i2) = trim(words(i))
   i3 = i2 + nlen
   i1 = i3 + 1
   if (i < nw) str(i2+1:i3) = sep
end do
write (str,"(*(a))") trim(words(1)),(sep // trim(words(i)), i = 2,nw)
end function join
end module m
!
program test_join
use m, only: join
implicit none
character (len=:), allocatable :: words(:)
integer :: i
words = ["one  ","five ","seven"]
print "(a)",join(words,",") ! one,five,seven
! implied do loop used below because TRIM is not elemental
print "(*(a,:,','))",(trim(words(i)),i=1,size(words)) ! one,five,seven
end program test_join
```

**Comment by joshgoebel** [comment]
Please show a snap of the output you are seeing in color.

**Comment by Beliavsky** [comment]
![fortran](https://user-images.githubusercontent.com/38887928/147980136-1f7bf7a5-701e-4040-83fb-9340a65ec480.jpeg)

**Comment by joshgoebel** [comment]
I don't think this is our bug, the result I get with 11.3 looks spot on:

![Screen Shot 2022-01-03 at 4 08 51 PM](https://user-images.githubusercontent.com/6473/147980671-b1ebd308-0ac6-4dad-ad19-3f67d1a94cda.png)

I'd suggest the problem is you aren't truly using Fortran (it's not built into our default bundle) or some other issue with the upstream integration.  If you can produce a test case that shows this result using ONLY our library and no other pieces I'd be happy to take a second look.
