### ISSUE TITLE
How to insert html to render tab characters?

### ISSUE THREAD

**Issue by generateui** [highlightjs/highlight.js#3477]
I'd like to render tab characters as `→` that don't select and are subtly rendered in the background. 

```
if (somevar) {
→	// We'll do something here
}
```

I'm currently rendering `<pre><code></pre></code>` elements where I replace `\t`s with `<span class="tab-character">→</span>\t` with css alike
```css
.tab-character {
  width: 0;
  user-select: none;
  position: absolute;
  color: grey;
}
```

This works great without hljs as it renders the tab character subtly in the background (alike vscode with option `View: Toggle render whitespace`). Copy 'n pasting still works, as `user-select:none` is applied. 

However, hljs strips the `<span>` elements leaving me with a `→` character. I tried switching on `ignoreUnescapedHTML` but that didn't help (I read in the docs that "do not log warnings to console about unescaped HTML in code blocks" which was a little unexpected going by the option name alone. 

Is there a way that I can make this work with hljs anyways?

**Comment by joshgoebel** [comment]
You really have two choices here:

- replace the tabs after highlighting (recommended)
- replace in two passes - using a placeholder the first time around (BUT one that also won't also break the highlighting), and then after highlighting replace the placeholder with the full HTML.

It's possible you could even use `→` as the placeholder (without any HTML trappings). This may break things though since many regex are looking for actual spaces/tabs, not strange `->` characters)...

**Comment by generateui** [comment]
Thanks for your thoughts. I'll think I'll go for the first option. I've though about visualizing tabs 'n spaces being a feature of hljs, but I couldn't make a definite conclusion. On the one hand it would be nice, on the other it does not seem to be a feature that should be part of a highlighting library. Would you even consider a PR with it?

> What would you have named the option?

`dontWarnUnescapedHtml` or `dontWarnForUnescapedHtml` would be closer to the behavior actually involved I'd say. But I'm not very known to the internals of hljs.

**Comment by joshgoebel** [comment]
Closing as asked and answered.
