### ISSUE TITLE
(bash) keywords with numbers are not recognized

### ISSUE THREAD

**Issue by mmattel** [highlightjs/highlight.js#3489]
**Describe the issue**
I have added some code to add custom keywords post the last register entry which is:
`hljs.registerLanguage('yaml', require('highlight.js/lib/languages/yaml'))`
```
const kwds = ['apt', 'apt-get', 'pecl',
'phpenmod', 'phpdismod', 'a2enmod', 'a2dismod', 'a2ensite', 'a2dissite',
'systemctl', 'service', 'sudo', 'wget', 'tar', 'mysql', 'php', 'grep'];

var built_in = hljs.getLanguage('bash').keywords.built_in;
hljs.getLanguage('bash').keywords.built_in = [...new Set([...built_in ,...kwds])];
```

This works great and tested with many scripts to highlight keywords - with one exception:

```
echo "Enabling Apache Modules"
a2enmod dir env headers mime rewrite setenvif
service apache2 reload
```

`echo` and `service` (added) gets correctly highlighted, but not `a2enmod`. After some testes, I renamed in both the text to highlight and the constant  `a2enmod` -->  `aenmod` and this works. The same is true for other a2xxx keywords.

**Which language seems to have the issue?**
`bash` but I guess this is not dependent to a language

**Are you using `highlight` or `highlightAuto`?**
`hljs.highlightElement(node)`

**Sample Code to Reproduce**
See above

**Expected behavior**

Keywords containing numbers should be recognized normally

**Additional context**

**Comment by joshgoebel** [comment]
> `$pattern: /\b[a-z._-]+\b/,`

Our `keywords.$pattern` here is too narrow... we probably need to match `[a-z]` first then also open it up for numerics... technically you could probably start with a number as well but I'd be worried about false positives (performance issue) and I'm also not sure that's a super common thing... is it?

None of the commands/keywords we have so far seem to start with a number.

PR would be welcome.

**Comment by mmattel** [comment]
Regarding a PR, I think you are much faster than I am as you know where to change. The following tests have been made with [regex101](https://regex101.com) in ECMAScript mode and with the [Java Regular Expression Tester](https://www.freeformatter.com/java-regex-tester.html) - both showing the same results.

**I have found a possible regex:** (note it is a bit faster than the original 😃 )
`\b[a-z][a-z0-9._-]+\b`

![image](https://user-images.githubusercontent.com/3321281/155738816-f1972d5d-7d7b-4976-9a1c-cf662ae3ce4d.png)

**The original pattern results the following:**
`\b[a-z._-]+\b`

![image](https://user-images.githubusercontent.com/3321281/155737259-20d74f47-8b13-49bb-8b46-811be1497ebb.png)

**Comment by mmattel** [comment]
Additional note: I would be very happy if there would be a documentation how to add extra keywords. Finding how this is done drove me nuts... You could use my code straight away if you like. It benefits that is does key dedup in case someone adds a key accidentially a second time compared to the existing one. The example is for the `bash` language. If one wants that for another language, he just needs to have a look into the original to identify the correct (sub)keyword array. Maybe to add in the wiki?

**Comment by joshgoebel** [comment]
> Additional note: I would be very happy if there would be a documentation how to add extra keywords. Finding how this is done drove me nuts...

I'd recommend our Discord for such questions the future though, might save you some time.    A few thoughts:

- Honestly hacking grammars from the outside like this isn't meant to be easy to do - _there are all sorts of caveats_. Even your own code would likely break if ran it after highlighting something (and the keywords had previously been compiled).  Also, many languages have multiple `keywords` definitions (inside sub-scopes) or use modes to highlight keywords instead of `keywords`... so there is no true "universal" way to do this.
- ... and for 98% of languages this really makes no sense.  If we're missing keywords for a language, we'd want to add them to the grammar itself via PR - not have everyone doing it themselves on a one-off basis.  Bash is a bit of an edge case as really you're just adding random commands that you'd like to highlight, not keywords. 
- Feel free to add a page to the wiki, but I'd add the above caveats.

I'd suggest this might be a larger discussion about creating some API for this in a broader sense... but (correct me if I'm mistaken) this seems a very small edge case and thus not something that would provide much benefit for users.  It seems really it only applies to shell, bash, etc... 2 or 3 grammars out of 200.

**Comment by mmattel** [comment]
I have created a seperate issue from the comment above to divide the tow topics and have a clean stream 😄
