### ISSUE TITLE
Plain text auto detection error

### ISSUE THREAD

**Issue by ih-abir** [highlightjs/highlight.js#3500]
I'm developing an open source editor where users can type or paste text or code, and they will be able to share that note using decentralized IPFS server.. We are planning to add highlight.js for note read, 
**when user shares any code then it can detect properly but the problem comes when user shares plain text, it can't detect plain text, it also highlights plain text wrongly. can you please help me about that. (note: we are using only browser, no server language).**

**Comment by joshgoebel** [comment]
Plain text cannot be auto-detected (in the same way as other grammars) since there is no "signal" there to auto-detect. But any snippet that has ZERO keywords (or matches) from ANY grammar will default to plaintext (as there is nothing to highlight in any case).  BUT if you have text with any programming keywords such as "if", "and", etc. then yes it's going to think it's code and choose a language.

**This is the correct and expected behavior.**  One could perhaps write a plugin to try and "detect" plaintext, but I have no idea what type of strategy one would use to do that - and it would be outside the scope of the core library.   If you have a plaintext block you should simple flag it as `language-text` in the CSS class and it will not be highlighted.

Also: Auto-detection is only 70-80% reliable in any case and we recommend that in cases where accuracy and reliably matters that people not use it.
