### ISSUE TITLE
Cannot use span tag in "code" tag any more

### ISSUE THREAD

**Issue by MagicJack** [highlightjs/highlight.js#3508]
**Describe the issue/behavior that seems buggy**
Up to ver.10.3.7 I can add some customization tags between &lt;code&gt; and &lt;/code&gt;. But this feature seems to be removed in version 11.

**Sample Code or Instructions to Reproduce**
```
<div class="code">
<pre><code class="plaintext">&gt; <span style='color:orange'>install.packages('IRkernel')</span>
</code></pre>
</div>
```

the related script and style and activation are below.
```
<link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/tomorrow-night-bright.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js" type="text/javascript"></script>
<script>hljs.highlightAll();</script>
```

**Expected behavior**
The color of text `install.packages('IRkernel')` is orange

**Additional context**
Is this feature removed? or is there other method instead of just using `hljs.hilightAll()`

**Comment by joshgoebel** [comment]
This change was intentional. #2889

This functionality could be added back via plugin if anyone wanted to maintain the code, but so far no one has stepped up to the plate to do so.

> plaintext

If all you care about is plaintext then see the README for how to ask Highlight.js to ignore that block entirely, in which case the HTML you're using will "just work" since it's just simple HTML - there is no need for this to go thru Highlight.js for plaintext.
