### ISSUE TITLE
Discuss: Any changes to common subset for 2022 / v12?

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlight.js#3526]
Related: #2848

Time for yearly/release cycle of discussing any changes to the default `common` set of languages we bundle.   v11 was released in May of last year and we do have things on the breaking changes list so I'm starting to think about a summer release of v12.

The list stands at:

```
│ lang         │ minified │
───────────────────────────
│ bash         │ 6202     │
│ c            │ 7923     │
│ cpp          │ 11438    │
│ csharp       │ 8322     │
│ css          │ 3802     │
│ diff         │ 1195     │
│ go           │ 2359     │
│ ini          │ 2335     │
│ java         │ 5090     │
│ javascript   │ 14719    │
│ json         │ 1171     │
│ kotlin       │ 6229     │
│ less         │ 6243     │
│ lua          │ 3054     │
│ makefile     │ 2073     │
│ markdown     │ 5022     │
│ objectivec   │ 4896     │
│ perl         │ 8825     │
│ php          │ 13898    │
│ php-template │ 1147     │
│ plaintext    │ 289      │
│ python       │ 9064     │
│ python-repl  │ 624      │
│ r            │ 7935     │
│ ruby         │ 9188     │
│ rust         │ 5396     │
│ scss         │ 4331     │
│ shell        │ 770      │
│ sql          │ 11736    │
│ swift        │ 12238    │
│ typescript   │ 2745     │
│ vbnet        │ 5265     │
│ xml          │ 5204     │
│ yaml         │ 4562     │
```

And the stats:

```
highlight.min.js    : 117742 bytes
highlight.min.js.gz : 39711 bytes
```

Rather than rehash what "almost" happened last time I'm just going to start this discussion fresh.   We have since added two "hot" new web-related grammars that aren't currently in common that are worth consideration:

- WASM
- GraphQL

I'm not sure why we never added Node REPL last time but we probably should now for parity.

_Opening this up for discussion._  

CC @highlightjs/core

**Comment by joshgoebel** [comment]
I wonder if in 2022 we still need a 3 CSS variants:

- less
- stylus
- scss

Also `makefile` stands out at me a bit as a "which one doesn't belong" if we were looking for something to ut, but it's only only 2kb.... so I'm tempted to leave it...

**Comment by joshgoebel** [comment]
@allejo Any thoughts?

**Comment by allejo** [comment]
I feel like with the widespread support and usage of CSS "variables" (aka custom properties), the need for CSS preprocessors has lessened significantly compared to a few years ago. Unless you're building a CSS library, chances are, you probably won't be writing in a preprocessor anymore. I think if the common subset only had CSS, that would suffice for people.

Regarding Makefile... I don't think it's popular enough to deserve being in the common subset. It's mostly used in the C/C++ ecosystem and _maybe_ Python. I vote to remove it.

I'm on the border but I'd push to remove `vbnet` from the common subset. I see it used in the Microsoft ecosystem, especially for plug-in development, but its use is dwindling since Microsoft has moved [its Office SDKs to JavaScript](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office).

**Comment by joshgoebel** [comment]
Removing:

```
	modified:   src/languages/less.js
	modified:   src/languages/makefile.js
	modified:   src/languages/objectivec.js
	modified:   src/languages/scss.js
	modified:   src/languages/vbnet.js
```
