### ISSUE TITLE
(Pascal) Highlight is wrong on Lazarus files

### ISSUE THREAD

**Issue by Alexey-T** [highlightjs/highlight.js#3568]
**Describe the issue**
I reported the issue here

https://github.com/rouge-ruby/rouge/issues/1842

And then ppl told me it is about highlight.js, so please see.

Lazarus file:
https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/main/lcl/buttons.pp
I see how it's rendered on site gitlab.
It's wrong.

- why "types" id is hilited?
- why "type" keyword is not hilited?
- why “function"/"procedure"/"constructor"/"destructor" keywords are not hilited?
- why comments //text and { text } are not pale?

**Which language seems to have the issue?**
Pascal

**Are you using `highlight` or `highlightAuto`?**
Gitlab site is using it.

**Comment by joshgoebel** [comment]
In quick testing I see none of these problems with our library and it seems GitLab hasn't switched YET - so the problem is likely still with Rouge.  If you believe there is truly an issue in our library please provide a reproducible stand-alone test case that shows the problem and I'd be happy to have a second look.
