### ISSUE TITLE
Undocumented breaking change in 11.x: dracula.css removed

### ISSUE THREAD

**Issue by k-funk** [highlightjs/highlight.js#3590]
Not sure if this was intended behavior, but my integration broke when upgrading from 10.7.3 to 11.x due to `styles/dracula.css` being missing. It was added in 9.2.0, so it seems worthy of marking as a breaking change in 11.0.0 if it was intentional.

**Comment by joshgoebel** [comment]
It moved to the `base16` subdirectory of `styles`. Pretty sure this is documented in the upgrade guide.

**Comment by k-funk** [comment]
Ah yeah, it is in there.

In the future, it would be nice to simplify the breaking changes into `CHANGELOG.md`. That breaking change was a bit buried in the rather lengthy upgrade guide.

**Comment by joshgoebel** [comment]
> it would be nice to simplify the breaking changes into CHANGELOG.md. 

That's a great idea, but more likely it would be a link at the top to the upgrade guide - which is a separate document for a reason - because of it's length, detail, examples, etc... I'll add that to the v12 todo list.

>That breaking change was a bit buried in the rather lengthy upgrade guide.

I'm hope anyone upgrading across **major** versions reads the whole guide carefully... otherwise it's quite likely something breaks - the more complex the use case, the more likely.  If there is a specific change that you feel would make the guide more accessible a PR would be appreciated - and I'll happily review.  I do my best to write our upgrade guides as thoughtfully and clearly as I can.
