### ISSUE TITLE
PHP mixed with JS or CSS not highlighted correctly

### ISSUE THREAD

**Issue by remcokalf** [highlightjs/highlight.js#3599]
We use highlight.js a lot for code blocks which have PHP mixed with JS and CSS.

Some of the code is not highlighted correcly, which seemingly depends on a combination of these factors:
- if the PHP has an opening tag: `<?php` or not
- if the code is mixed or not.

We prefer having **no** `<?php` opening tag because if we use it, then we get a lot of (inexperienced) users in our support tickets who paste it directly in their file with other PHP and get errors.

Having no opening tag goes okay in cases with pure PHP:
![Screen%20Shot%20on%202022-08-16%20at%2014-14-38](https://user-images.githubusercontent.com/4609920/184877154-81eedc99-9c4a-430d-be4d-54de0e7f2b22.png)

But not in other cases in case of mixed content. The first line is tagged as language-xml. (Also some of the JavaScript is not highligted properly as can be seen here):
![Screen%20Shot%202022-08-16%20at%2013 55 27](https://user-images.githubusercontent.com/4609920/184875469-1d191f32-997c-4bc4-94b5-e2e61efe2578.png)

This last example is highlighted better when we use the PHP opening tag. It would be very helpful if without the opening tag, it would also look like this:
![Screen%20Shot%20on%202022-08-16%20at%2013-57-22](https://user-images.githubusercontent.com/4609920/184875566-fc7735bb-b6fb-4819-83c5-a6f8735670b9.png)

Example code for the above:

```
add_action( 'wp_head', function() {
  ?>
    <script>
      (function($) {

        var sortfacet = 'my_sort_facet';

        $(document).on('click', '.sort-radio', function() {
          var val = $(this).attr('data-value');
          FWP.facets[sortfacet] = [val];
          FWP.toggleOverlay('on'); 
          FWP.fetchData();
          FWP.setHash();
        });

        $(document).on('facetwp-loaded', function() {
          if ('undefined' !== typeof FWP.facets[sortfacet]) {
            $('.sort-radio').filter('[data-value="' + FWP.facets[sortfacet] + '"]').addClass("checked");
          }
        });

      })(jQuery);
    </script>

    <style>
        /* Replace 'my_sort_facet' with the name of your sort facet */
        .facetwp-facet-my_sort_facet select {
            display: none;
        }
    </style>
  <?php
}, 100 );

```

**Comment by joshgoebel** [comment]
>  This last example is highlighted better when we use the PHP opening tag. I

Yes, because then it's actually valid PHP. :-)  I feel a bit like you're asking for the impossible here, but here are my quick thoughts.

We have two php grammars. `php` is just for raw php code (sans tags)... it's not going to work well for CSS and HTML though, as it only recognizes PHP. But if you had any plain pure PHP snippets it'd be a great choice.  `php-template` is based on `xml` and starts in in XML context (as you see) so that it can recognize: php, CSS tags, JS tags, etc... but yes it needs the starting PHP tag to recognize embedded PHP.

I think you need to write a tiny plugin (or just some JS) and:

- Include the `<?php` for correctness (and correct highlighting)...
- Post-process the HTML after highlighting to remove the `<?php` from the first line... You could of course add a custom attribute to your code block that turned this behavior on and off, etc... or you could just decide that globally your entire site strips the first tag, no matter what...

Plugin documentation:
https://highlightjs.readthedocs.io/en/latest/plugin-recipes.html

**Comment by remcokalf** [comment]
Thanks for info and the suggestions, very helpful. I didn't know I could add plugins, will look into it.

(I realise our use case is a bit unusual (not using the opening tag), but it prevents a lot of user support issues if they can just paste a snippet in their WordPress install's functions.php.)

**Comment by joshgoebel** [comment]
> but it prevents a lot of user support issues

Yes, I understand the utility on your end. :)
