### ISSUE TITLE
[Request] Make a way for tokens to be clickable or add token data to every highlight...

### ISSUE THREAD

**Issue by velara3** [highlightjs/highlight.js#3601]
**Is your request related to a specific problem you're having?**
A way to add a clickable link on each word or token. 

**The solution you'd prefer / feature you'd like to see added...**
A way to add a function to each highlight HTML element that can be called when it is clicked on. I would like to add at least one value to it and that is the type of entity it is. 

**Any alternative solutions you considered...**
I could add a click event on the container and then check the current target but that doesn't give me the token type. If the highlight HTML elements could have data added to them then that would work. If you had a "div" tag that was highlighted it could be something like: 

`<span token-info="type:'tagname', name:'div'">div</span>`

**Additional context...**
Consider the following un-highlighted raw HTML code before it is highlighted: 

```
<div id="div50">
	<span>Hello world</span>
</div>
```

What I would like is to be able to add a click handler for everything. The code after highlighting would look roughly like this: 

```
<span onclick="hook('div', 'tagname')">div</span> <span onclick="hook('id', 'attribute')">id</span>="div50">
    <span onclick="hook('span', 'tagname')">span</span>Hello world
<span onclick="hook('div', 'tagname')">div</span>
```

**Comment by joshgoebel** [comment]
Could you just highlight first and then just hook up your event handlers to the resulting DOM?  We don't really have a way to generate custom HTML so either what you are wanting to do works with the output we already generate or you're kind of on your own. 

---

You could also read the source regarding our private/internal "emitter" API...  that's the closest you'll get to generating custom HTML (build an emitter), buts technically its unsupported and I can't really help you with it further here.

**Comment by velara3** [comment]
I might have something working using the class names but there aren't class names for everything.

**Comment by joshgoebel** [comment]
Yeah. Not everything is highlighted.

**Comment by velara3** [comment]
How difficult would it be to add highlighting to the unhighlighted tokens? Or have an option to do that? Is tokens the right word? 

For example, this works great for my needs: 

`<span class="hljs-attribute">width</span>:<span class="hljs-number">100px</span>`

but there are cases like this: 

`<span class="hljs-attribute">color</span>:green`

If I could get this: 

`<span class="hljs-attribute">color</span>:<span class="hljs-string">green</span>`

Two things I might guess you might say: 

1. Adding that around all tags increases size and processing time
2. We don't have time or interest to work on this

My response: 

1. Sure I agree. But it might be negligible. Tests would have to be run to see how much difference that is in creating the highlight tags and then the processing. If it is nothing it is nothing. If it's something then it could be placed behind a options flag.
2. I might be able to help add this if I can be pointed to the right location where this can be added. My guess is that the code is already there but if there is no styles then the function exits out without enclosing.

**Comment by joshgoebel** [comment]
You might want to check out docs: https://highlightjs.readthedocs.io/en/latest/

Particularly the Language Definition Guide, Mode Reference, Scope Reference.  You could do this on your own (with a customized CSS grammar or some such)... possibly pretty easy if you used `keywords`, though I'm not 100% sure that would work.  And of course you're only talking about colors here - there are TONS of other CSS-isms that we don't highlight.

_Are colors all you really care about for your use case?_

> add highlight tags (span tags with class) to the unhighlighted tokens? 

You could of course post-process the resulting HTML to add additional highlighting... it's just text that could probably be scanned easily with a Regex, etc...

1. There is no "size" cost in the generated HTML, all the work is done on the client.  Processing also is negligible.  There is a price to pay in the download size, we'd have to store all those 147 color names...

2. But highlighting the color names *might* be a win... 147 names isn't a huge list - we already have long lists of attributes, properties, etc...

---

My worry is you [perhaps?] care more about "make a way to token to be clickable" than you do about "highlight colors as strings" because I think that (unless all you care about is colors) this is just the top of a very, very deep rabbit hole... and not a simple one either.  You have to not only fix CSS but also:

- Less
- SCSS
- Stylus

We have a policy that the highlighting of all "css like grammars" must be identical (in terms of the things they share)... so for every improvement you have to repeat the work across all 4 variants.

---

If you wanted to make an attempt to add color name highlighting to all 4 CSS like grammars... I think we'd be open to that... you might want to see:

- tools/css
- tools/developer.html (after you've build the web version - see building instructions)
- the test suite (particular markup tests)
- `css-shared.js`

This is in addition to the 4 core grammars you're be changing.

**Comment by velara3** [comment]
I read the entire documentation but don't see a way to add span tags around the elements that don't already have span tags around them. 

FYI I'm not concerned about colorizing anything. What I'd like is to add span tags around all of the words or tokens.

**Comment by joshgoebel** [comment]
> I read the entire documentation but don't see a way to add span tags around the elements that don't already have span tags around them.

You'd have to add "rules" that create more syntax highligthing.  That's what https://highlightjs.readthedocs.io/en/latest/mode-reference.html is all about.

> FYI I'm not concerned about colorizing anything. 

You still have to match pieces of text and provide named scopes... it doesn't necessarily have anything to do with color...

> how could someone could syntax highlight if it doesn't have a class name describing it?

Create a rule that matches it - and assign a scope to it:

```js
{
  scope: "css.property",
  match: /css property value/
}
```

**Comment by velara3** [comment]
If that's the case then I'll see if I can create a rule for a string value of a CSS property. 

In my tests, there is a rule for syntax highlighting a CSS number and a CSS RGB color. 

```
.myClass {
	left: 26px; // number is highlighted
	overflow: hidden; // no highlight
}
```

A few questions: 

1. Is it possible to add rules through the plugin system? 
2. Can you point me to the rule that highlights the property value number? I'd like to try adding a test rule to the built project rather than the prebuilt project that I then would have to build. 

What I'd like to do is see if I can add one rule, make sure that works and see how much work that involves.

**Comment by joshgoebel** [comment]
> Is it possible to add rules through the plugin system? 

No. Though you could post-process the string/HTML output that way.

> Can you point me to the rule that highlights the property value number? 

Look in `css-shared.js` or `modes.js`... search for "px" etc should be easy to find.

**Comment by velara3** [comment]
So IIUC css-shared.js and modes.js are eventually "compiled" into highlight.js?

**Comment by velara3** [comment]
For testing purposes, I've opened highlight.js and edited the MODES const to check for the simplest search string I can search for. 

I've added the object block STRING to search for 'butt': 

    const MODES = (hljs) => {
      return {
        STRING: {
          scope: 'number',
          begin: 'butt'
        },

Here is my CSS: 

```
#Rectangle_1_j {
	fill: rgba(255,101,101,1);
	stroke: rgba(112,112,112,1);
	stroke-width: 1px;
	stroke-linejoin: miter;
	stroke-linecap: butt;
	stroke-miterlimit: 4;
	shape-rendering: auto;
}
```

I've left the scope to number for testing purposes. 

So far it is not finding it. 

Does the order of modes affect the search?

**Comment by joshgoebel** [comment]
IDENT finds valid identifiers, not all "strings".   I'm not sure we want to just highlight any random identifier. We do not wish to highlight "booger" if we see it, because that means nothing in CSS.  Remember before: we were talking about adding the list of colors - so we could recognize them.  

If you're just doing this for yourself, you can do whatever you want, but if you're wanting to contribute back to the library itself we need to highlight actual known keywords (or very reliable equiv match patterns), not just random identifiers.

> It looks like I need to add my constant farther down:

There are different nested modes in different grammars... (grammar rules are nested, see the full documentation)... so your rule not only needs to match, but also be placed in the correct mode's `contains`.  In this case (an attribute value) it needs to come after `:` so placing it inside the attribute value mode's `contains` makes total sense.

**Comment by velara3** [comment]
Looking at it, highlighting the color names doesn't seem too difficult at this point but originally I was attempting to enclose the CSS property value so I could make it clickable. Currently, when adding a click handler to the container, when someone clicked on a string property value it would return the PRE or CODE container in the event target. If it was a number and was matched by an existing rule then you could click on it and then the click event target would be that property value string. Using that event target I can find the property name by looking at the sibling and parent elements. 

>IDENT finds valid identifiers, not all "strings". I'm not sure we want to just highlight any random identifier. 

I see two goals emerge in this conversation on this. 
- Highlight the different parts of the code (the selector, the property name, the property value, etc)
- Hint at valid CSS and valid CSS properties and values
 
If you want to highlight all the parts of the CSS code you would need to highlight the property value even if you don't know what it means. 

If you want to hint at valid CSS and only highlight valid CSS properties you'll have to do more work. In my opinion you will need to: 

1. Check if the property name exists in CSS
2. Check if the property value is a valid value for that property

The way I would do this is: 

- Create an HTML element (preferably check for the type in the type selector but it could be base element)
- Check the style exists in the HTML element style object
- Apply the property and see if it returns as a valid property value

The HTML element doesn't have to exist on the document. Here's how I would do it: 

```
If (hljs.checkForValidCSS) {
    var element = new HTMLElement(); // could be cached
    var name = "color";
    var value = "asdf";

    if (name in element.style) {
        // add valid property name class
    }
    else {
        // add invalid property name class
    }

    if (CSS.supports("color", value) {
        // add valid property value class
    }
    else {
        // add invalid property value class
    }
}
```

The end result would be: 

`<span class="hljs attribute valid">color</span>:<span class="hljs attribute-value invalid">asdf</span>`

If you want to Highlighting the colors would be simple given a list of all the color names.

**Comment by joshgoebel** [comment]
> Looking at it, highlighting the color names doesn't seem too difficult at this point but originally I was attempting to enclose the CSS property value so I could make it clickable. 

Yes, and I believe you've already seen how if you customize the grammar (for your own personal uses) you might achieve this result - however that is not something we care about in the core library.  I'm not even yet convinced that all values should be highlighted.  _Highlighting a thing well is as much about what one chooses to highlight as what one does not._

In rethinking this just now I'm not sure we should even add colors - unless we first think whether the plan is to include a list of ALL discrete values.  I think before we go down that road I'd want to know how large a size change this is... would the CSS grammar going to be 10% larger or 200%?

> Hint at valid CSS and valid CSS properties and values

We're not interested in what is "invalid" as this is very hard to do with pattern matching across ALL grammars - and we desire consistency in features we add to the library.  If adding invalid to all grammars would be difficult, we're not interested in adding it to only a few (just because they are easy).

> Check if the property name exists in CSS ... Check if the property value is a valid value for that property

This is WAY out of scope.  _We are not a language parser._  We are a sophisticated pattern matcher.  You may want some type of CSS parser instead.

**Comment by joshgoebel** [comment]
Closing this specific request as cant/wontfix and creating a new issue for the side discussion about whether we should highlight all property values.

**Comment by velara3** [comment]
> > Check if the property name exists in CSS ... Check if the property value is a valid value for that property
> 
> This is WAY out of scope. _We are not a language parser._ We are a sophisticated pattern matcher. You may want some type of CSS parser instead.

Indeed. I bring it up for discussion purposes. I looked into CSS.supports API but that would fail to highlight some values because it's test checks if the browser supports the CSS property and value in that version of the browser. 

I thought briefly about adding a color swatch directly before or after the color value. They do this in browser Web Inspectors.  

<img width="437" alt="image" src="https://user-images.githubusercontent.com/1084127/189543964-2760fc08-4d43-4038-bf35-b14afa293f89.png">

> I'm not even yet convinced that all values should be highlighted. Highlighting a thing well is as much about what one chooses to highlight as what one does not.

Right. Do you want to highlight all style values or do you want to classify it so there is an option for theme authors to highlight it? 

The way I see it, the syntax highlighter parses the code, marks each fragment with a class definition. 

"We've read your code and broke it down into individual parts. This is the selector, this is the attribute, etc. Now, it's up to you, theme authors, in what colors and styles you choose to style."

**Comment by joshgoebel** [comment]
> The way I see it, the syntax highlighter parses the code, marks each fragment with a class definition.

You're still imagining a full parser I think... _we only tag/highlight what we find interesting_ - what we think **MOST** people would want to colorize, sometimes this might only be 5-10% of files total content.  It's not our job to classify *every single item*.  True, we do more than we used to (see #2500).  Yet over 10 years of highlighting CSS and no-one has asked for values to be highlighted - _include yourself_ - you're only asking as a round-about way to achieve some other end.   

Also:

- Other highlighters ignore values (GitHub, Prism, etc)

So I feel we're in pretty good standing with our current behavior.  That said, I did open an issue for this discussion - and we'll see where that goes.  And you're welcome to comment on that thread.
