### ISSUE TITLE
(javascript, typescript) Incorrect handling of digits after `$` in identifiers

### ISSUE THREAD

**Issue by Keyacom** [highlightjs/highlight.js#3645]
**Describe the issue**

`$` isn't treated as a character valid in identifiers, even though it is allowed in identifiers, and is treated like alphabetic letters and `_`. This causes e.g. `1` in `$1` to be highlighted like a numeric literal.

**Which language seems to have the issue?**

`javascript`, `typescript`

**Are you using `highlight` or `highlightAuto`?**

I assume `highlightElement()` uses `highlightAuto()`.

**Sample Code to Reproduce**

The test code is:
```js
const $1 = "buck-one";
const $this = `${$1}`;
const bu$ = "bus";
const $$ = "buck-squared"
console.log(`${new Date()}, ${90 ^ 34}`);
```

https://jsfiddle.net/Keyacom/0ezu3jbd/9/

**Expected behavior**

GitHub syntax highlighting correctly doesn't highlight any digits that follow `$`. Highlight.js must do the same thing. The refrence code block is in the section above.

**Additional context**

**Comment by lachieh** [comment]
The issue here is not that the `$` character doesn't work in identifiers but rather that numbers are matched after identifiers using the `\b` word boundary in which `$` is not considered part of a 'word' in Regex. For example: `$hello0` will highlight correctly, but `$0hello` will not.

The PR above solves this issue, but I'm happy to adjust or rework if there is an alternative solution.

**Comment by Keyacom** [comment]
Yeah, looks good.

**Comment by joshgoebel** [comment]
> do most of the definitions for JavaScript also apply for TypeScript without having to copy?

Yes, TS is built on top of JS grammar.
