### ISSUE TITLE
[Request] `punctuation` and `operator` for TypeScript

### ISSUE THREAD

**Issue by williamd5** [highlightjs/highlight.js#3674]
**Is your request related to a specific problem you're having?**
When using JSON, punctuation such as `{}:,` is parsed as `hljs-punctuation`. This is not the case for TypeScript. There is also no parsing for operators such as `+`, `=`, `=>`, `===`, `!==`, `??`, `?=` and the like.

**The solution you'd prefer / feature you'd like to see added...**
Isolate punctuation in TypeScript (such as object and array braces, for instance) as `hljs-punctuation` and operators as `hljs-punctuation`.

<details><summary>On a side note…</summary> There seems to be <code>hljs-type</code> which is used with doctags such as <code>@type {Type}</code>. Why is that not used for ts types instead of <code>built_in</code> and <code>title.class_</code>? in <code>class Name {}</code> the name is parsed as <code>title.class_</code> but in <code>namespace Name {}</code> it is not parsed at all.</details>

**Comment by joshgoebel** [comment]
> Isolate punctuation in TypeScript

This is pretty hard because of `<` serving so many purposes in TS... find the thread on all the issues with JSX for example... but this would also be covered by #2500, we don't leave a single issue open per language.  If someone steps up to make PRs for this work (and they are solid), they can be merged at any time... and #2500 will stay open over the long-haul.  But as I said, it's no walk in the park with JS/TS.

Closing as dup of #2500.  I'll split the other.

**Comment by joshgoebel** [comment]
Re: TypeScript
> There seems to be hljs-type which is used with doctags such as @type {Type}. Why is that not used for ts types instead of built_in and title.class_? in class Name {} the name is parsed as title.class_ but in namespace Name {} it is not parsed at all.
