### ISSUE TITLE
[Request] Make XML more easily extensible

### ISSUE THREAD

**Issue by thecodewarrior** [highlightjs/highlight.js#3698]
### Is your request related to a specific problem you're having?
While working on the Vue SFC highlighting I wanted to add highlighting for Vue's special HTML attributes, but that's basically impossible when using XML as a `subLanguage`. During my research I found there's a precedent for making one language a superset of another (#2185), which makes this possible. However, trying to do what I want to do requires a pile of awful hacks because there's no way to inject anything into the existing syntax, meaning I have to use fragile heuristics to pull out values and edit them.

### The solution you'd prefer / feature you'd like to see added...
It would be extremely helpful to have a way of injecting custom syntax into various locations in the XML syntax, as well as getting out some of the default regexes/modes without using nasty hacks.

#### The injection/access points I'd need are:

1. For special attributes (`v-if`, `v-foo:bar`, `:prop`) I need to inject custom modes at the start of [`TAG_INTERNALS`](https://github.com/highlightjs/highlight.js/blob/7addd66/src/languages/xml.js#L44)

2. For the `<script lang="...">` and `<style lang="...">` tags I need access to `TAG_INTERNALS` so I can create custom tag modes (e.g. `<script(?=\s[^>]*lang\s*=\s*(?:"ts"|'ts'))`) with the standard tag internals (these are global so no special injection point necessary, though having one would be nice)

3. To highlight special elements (`CamelCase`/`kebab-case` component names) I need to inject custom modes at the start of the [open tag](https://github.com/highlightjs/highlight.js/blob/7addd66/src/languages/xml.js#L206) and [close tag](https://github.com/highlightjs/highlight.js/blob/7addd66/src/languages/xml.js#L224)

4. For the mustache interpolation (`{{ some js }}`) I just need to inject them globally, which doesn't require a formal injection point, though having one would be nice.

#### I'm also planning on working on svelte highlighting, which would need a couple more injection points:

5. For bare bracket attributes (`attr={some js}`) I need to inject a custom mode into the [attribute value `contains` array](https://github.com/highlightjs/highlight.js/blob/7addd66/src/languages/xml.js#L53)

6. For brackets inside attributes (`attr="value and {some js}"`), I need to inject custom modes into the [string contents array](https://github.com/highlightjs/highlight.js/blob/7addd66/src/languages/xml.js#L61)

I have several of these already implemented using the hacks, which you can see the test output [here](https://gistpreview.github.io/?6a7ea3ebc0309666f2969ab73055c73b) (that's the output of the test fixtures from #3697)

### Any alternative solutions you considered...

The only other alternatives are pretty much:
- Stick with the highlighting it has right now, which is just HTML with custom `<script lang="">` and `<style lang="">` tags that set the subLanguage explicitly instead of inferring it

- Copy/paste the XML code into the vue syntax

- Use a bunch of hacks to find the data I need and then manually patch it:
  - I can get `TAG_INTERNALS` using this: 
    ```js
    const TAG_INTERNALS = xmlBase.contains.find(e => e.keywords?.['name'] === 'style' && e.contains.length === 1)?.contains?.[0]
    ```
  - To add custom element name highlighting I need this:
    ```js
    for(const mode of xmlBase.contains) {
      const tagNameMode = mode.contains?.find(e => e.className === 'name')
      if(tagNameMode != null) {
        mode.contains.unshift(
          {...tagNameMode, className: 'title', begin: /[A-Z][a-zA-Z0-9]*(?=\s|>)/},
          {...tagNameMode, className: 'title', begin: /[a-z][a-z0-9]*(-[a-z0-9]+)+(?=\s|>)/},
        )
      }
    }
    ```
  - For the `attr={value}` highlighting I need the `TAG_INTERNALS` hack plus this:
    ```js
    const attrValueMode = TAG_INTERNALS.contains.find(e => e.contains.some(x => x.className === "string"))
    ```
  - For the `attr="some {value}"` highlighting I need the previous step plus this:
    ```js
    attrValueMode.contains.find(e => e.className === "string")?.variants.filter(e => e.contains != null)
    ```

#### Additional context...
To match CamelCase tag names I also need to re-enable case sensitivity for a single mode (see #3699)

**Comment by joshgoebel** [comment]
This is all without taking into consideration that the key might be named `scope` or `className`, there are other such gotchas... or scope can even be a Hash... and that's why I'm not sure this is something we want to encourage.  Outside of injecting rules to the top-level (which is already pretty simple) the rest of our grammars are technically "internal"... we sometimes make *sweeping* changes to grammar internals, even with minor releases - and I would not want to lose the flexibility of doing so.  Assuming you can just change them (even at certain named points) is likely to lead to bad outcomes.

The idea of "injection points" hopes to avoid that, but our grammars are just too flexible... it's possible that the HOW of the injection itself might also change...  Imagine for example that we found a reason to use two different TAG_INTERNALS for different types of tags... now a single injection point doesn't work.  You'd have to review the new version and decide which was relevant (or if both were) - and then perhaps a second injection point would need to be added.

You could of course try and craft some of this changeability into a complex injection system, but I don't think that's a good direction either since it's just more code to maintain and I'm not sure we'd know all the edge cases upfront.

---

I'd suggest one of two approaches:

- fork/copy XML entirely and just mix your changes into that new grammar
- fork XML (but only for the purposes of maintaining a small "injectable" patch against it), add the named injection points you need, build on top of this new injectable XML

I think the first approach would be **much** simpler, but if you really liked this idea of injecting the second system would be workable... worst case, if a major rewrite of XML happened you might have to re-engineer both your fork and your derivative language that's built on top.

Which is why I say I'd just recommend the first approach.

**Comment by joshgoebel** [comment]
If you want to play around with injecting look at JS/TS for a little more inspiration... we have named injection points (labels), but we only use them internally to support the core library.

**Comment by thecodewarrior** [comment]
I'll just make an internal fork with the extension points I need then. That will probably simplify things considerably while avoiding the issue of the two syntaxes getting muddled together.

Thanks for the quick response!
