### ISSUE TITLE
[Request] Re-enable case sensitivity per-mode

### ISSUE THREAD

**Issue by thecodewarrior** [highlightjs/highlight.js#3699]
#### Is your request related to a specific problem you're having?

I'm attempting to improve the Vue SFC highlighting, and as part of that I want to highlight vue components differently from regular HTML elements. I'd be identifying which elements are likely to be components by highlighting `<CamelCase>` and `<kebab-case>` elements as components. However, the XML syntax is marked as case insensitive, so it's impossible to detect CamelCase elements.

#### The solution you'd prefer / feature you'd like to see added...
It would be great if you could manually override the case insensitivity on a mode-by-mode basis, that way I could set my CamelCase and kebab-case modes to be case sensitive while leaving the rest of the grammar unchanged

#### Additional context...
The way I'm doing the Vue highlighting at the moment is by making it a superset of the XML syntax (a la #2185), so I have to inherit the case sensitivity of the XML syntax. Doing this kind of extension requires a ton of hacks at the moment (see #3698)

**Comment by joshgoebel** [comment]
This request is actually impossible due to the design of the parser.  All sub-modes (for a single parent mode) are joined  together into one HUGE regex to find "the next match"... this is for scan performance.  So, since we now have a single regex it must either be case insensitive or not... For simplify we enforce this at the language level.

If someone desired an XML like grammar with case sensitivity I would recommend forking XML rather than trying to build on top of it.

> so it's impossible to detect CamelCase elements.

Not entirely true, as there are per-match callbacks that could do further analysis of matches to render such a judgement.

https://highlightjs.readthedocs.io/en/latest/mode-reference.html#on-begin

**Comment by thecodewarrior** [comment]
Oh, I remember seeing that those callbacks existed, but I didn't really look into them at the time. That should suit my needs perfectly 👍
