### ISSUE TITLE
[Request] Persisting class names inside <pre>

### ISSUE THREAD

**Issue by daniyalhamid** [highlightjs/highlight.js#3712]
**Is your request related to a specific problem you're having?**
A clear and concise description of the problem itself. Ex. I'm always frustrated when [...]

There should be an option perhaps to persist existing class names inside `pre` / `code` tags, for example:

```
<pre>
const foo = <span class="wavy-error">bar</span>;
</pre>
```

**The solution you'd prefer / feature you'd like to see added...**
Allowing certain class names to be persisted and not removed when parsing happens would be a great addition.

**Any alternative solutions you considered...**
I tried creating a custom plugin for this, but can't figure out much with limited documentation on the subject.

**Additional context...**
The desired result I'm trying to achieve is like the following screenshot:

<img width="218" alt="Screen Shot 2023-02-07 at 3 20 27 AM" src="https://user-images.githubusercontent.com/57444458/217131461-2e24454c-85b1-40b6-a6d8-c440880316b1.png">

If it's already possible somehow to persist a class name, I'd really appreciate some guidance.

**Comment by joshgoebel** [comment]
This once upon a time was a feature, it's since been removed.  This is a feature most users do not need and it only increases the risk that 99% of users shoot themselves in the foot introducing HTML/JS injection security issues - to assist the 1% of users who could benefit from this feature.  Simply disallowing this entirely allows us to make it easier to catch these vulnerabilities during development - rather than after a project goes into production.

Ref: https://github.com/highlightjs/highlight.js/issues/2889

This can be done easily enough using a plugin - someone just needs to step up to write/maintain it.  The old code may or may not still work.
