### ISSUE TITLE
[Request] provide removePlugin api

### ISSUE THREAD

**Issue by faga295** [highlightjs/highlight.js#3716]
**Is your request related to a specific problem you're having?**
when I use vue, I add highlightjs plugin inside component, after that, each time when I mount this component, the highlightjs is added a plugin, if I mount  this component multiple times, highlightjs will be added multiple plugins.

**The solution you'd prefer / feature you'd like to see added...**
Provide a removePlugin api, so that I can invoke it before component unmount.

**Any alternative solutions you considered...**
I can't think of any other solutions, 

**Additional context...**
If there has workaround, I will also appreciate a lot.

**Comment by joshgoebel** [comment]
What plugin are you adding exactly that you want to remove later?

**Comment by faga295** [comment]
I copyed from [there](http://highlight.cndoc.wiki/doc/136 )

**Comment by faga295** [comment]
If it necessary, I can provide minimal reproduction

**Comment by faga295** [comment]
I desperately need a workaround, because I can't require all component users to install the latest version.

**Comment by joshgoebel** [comment]
Perhaps a smarter (class based) plugin that you can turn on/off outside HLJS? ...but still only register once.  Or vendor us as part of your library in order to patch us to add a remove method?  I'm not sure why you want to add/remove the plugin 100 times vs just setting it up once and using it as-is.

That said I don't see the harm in `removePlugin(plugin)`... passing the same object that was passed to addPlugin would remove it from the list of registered plugins.  I'd be open to a PR implementing this behavior (and docs).

**Comment by faga295** [comment]
I will provide a minimal reproduction sooner.If it possible, I wish I can submit this PR to challenge myself , surely, I believe you can complete it more prefect.

**Comment by faga295** [comment]
https://stackblitz.com/edit/vitejs-vite-odugjr?file=src/App.vue
reproduce step:
* inspect the `Code` html structure
you will get it
![image](https://user-images.githubusercontent.com/87003751/218951208-114a804e-1ec5-4a29-b4bc-296a2ef1cfa3.png)
* edit `code.vue` or `App.vue` anywhere , vite hmr will unmount component and remount it.
![image](https://user-images.githubusercontent.com/87003751/218952889-fd8a5a75-8ff7-485b-b479-3fe0b6f560a0.png)
