### ISSUE TITLE
es模块导出方式不正确，导致项目构建编译报错[!] Error: 'default' is not exported by node_modules/highlight.js/lib/index.js, imported by node_modules/highlight.js/es/index.js

### ISSUE THREAD

**Issue by hqqxxf** [highlightjs/highlight.js#3862]
**es模块引用了lib/index.js，而lib/index.js是commonjs的导出方式**
<img width="731" alt="image" src="https://github.com/highlightjs/highlight.js/assets/11484241/33bf4070-438f-47ba-af74-923e0099a390">

<img width="613" alt="image" src="https://github.com/highlightjs/highlight.js/assets/11484241/28719a0e-d17f-479d-a120-1b32e47efb94">

**Comment by joshgoebel** [comment]
Yet default is exported you can see it right there... how are you trying to use this in your project?

**Comment by adamburmister** [comment]
Oh, I had this issue too (but had written it off to an oddity of our setup).

For some more colour; our project is a mono repo which has a "platform" and a "ui lib" (which is used by the platform with a package entry of `"ui": "file:../ui"`).
Then we use Vite.

My working theory had been that the highlight.js package.json uses `exports` which alias `require` and `import` definitions, and maybe those are getting lost?

**Comment by joshgoebel** [comment]
Perhaps it's a vite issue?

**Comment by AbandonedFridge** [comment]
Got here b/c I ran into this trying to use highlight.js with @web/dev-server(for dev - which gave me a `The requested module './../core.js' does not provide an export named default` error) and rollup(for build - which gives the same error as in the title - just core.js instead of index).

Neither tool handles commonjs module conversion by default anymore. Have to setup @rollup/plugin-commonjs and - for dev-server at least - explicitly tell it about the highlight.js package.

Can't speak to vite, I'm not using it. The docs say that it handles commonjs module conversion by default, but I wouldn't be surprised if it didn't include node_modules in that. Might need to tell it to convert the package.

**Comment by Pancake-Q** [comment]
问题找到解决方案了吗

**Comment by Backru** [comment]
这个问题有解决方案嘛

**Comment by joshgoebel** [comment]
> Have to setup @rollup/plugin-commonjs

That sounds like a reasonable solution in the interim.   This should also be fixed when we hit version 12 and only ship ES builds.

Closing this as #wontfix.
