### ISSUE TITLE
(C) C23's digit separators are highlighted incorrectly  

### ISSUE THREAD

**Issue by Melkor-1** [highlightjs/highlight.js#4054]
**Describe the issue**

C23 has added digit specifiers to the language (`'`, just like C++). They are not highlighted correctly in the code. It seems as if the engine treats it as the start of a string/character

**Which language seems to have the issue?**
`c`

**Are you using `highlight` or `highlightAuto`?**

Whichever one StackExchange uses.

**Sample Code to Reproduce**

```c
#define _POSIX_C_SOURCE 200'809L
#define _XOPEN_SOURCE   700
```

**Expected behavior**

It should recognize it as a digit separator instead of a character or a string opening quote.

**Additional context**

This was found at this code review post: https://codereview.stackexchange.com/revisions/292149/6

And it was fixed by such a hack:

```c
#define _POSIX_C_SOURCE 200'809L // '
```

**Comment by joshgoebel** [comment]
Does our C++ grammar properly support this already.  If so might be an easy port.

**Comment by LarnuUK** [comment]
@joshgoebel based on the release over on Stack Overflow, neither C or C++ support the grammar.

**Comment by abarkat99** [comment]
Looks like both C++ and C already have support for digit separators. For example the regex for `NUMBERS` in C++ allow usage of single quotes as seprators:

https://github.com/highlightjs/highlight.js/blob/da79da636baa790cfceda931554186ac17f7f48b/src/languages/cpp.js#L52-L95

From my understanding the actual issue is that the `contains` for `PREPROCESSOR` does not include `NUMBERS` but does have `STRINGS` causing the beginning of the single quotes to be considered a string:

https://github.com/highlightjs/highlight.js/blob/da79da636baa790cfceda931554186ac17f7f48b/src/languages/cpp.js#L104-L116

I am not familiar with Highlight.js but my guess is that adding `NUMBERS` in `PREPROCESSOR.contains` should fix the issue

**Comment by joshgoebel** [comment]
> I am not familiar with Highlight.js but my guess is that adding NUMBERS in PREPROCESSOR.contains should fix the issue

I think that would do a bit too much (for some directives), but that's the right idea.  I think the pre-processors may need to be handled more precisely... for example `#define x CODE` might deserve full highlighting (for CODE) but not others... I'm trying to think of what false positive cases we might have.

**Comment by Dxuian** [comment]
is this still open 
i recently made a commit regarding a similar issue i believe i can contribute

**Comment by Dxuian** [comment]
@joshgoebel  upon further inspection the PR i made yesterday 
handles all digit seperators. I believe we can mark this issue as resolved 
![image](https://github.com/user-attachments/assets/6c41bf3c-8ec3-485f-8cf1-0893e3f307a6)

**Comment by joshgoebel** [comment]
Resolved by https://github.com/highlightjs/highlight.js/pull/4094
