### ISSUE TITLE
JSON Comments

### ISSUE THREAD

**Issue by tylercraft** [highlightjs/highlight.js#406]
Comments in a JSON block are ignored. It would be great to be able to highlight these as well. For example:

```
# Example response for user object
{
  id: 1,
  name: "Joe Smith" // String that represents the users name
}
```

**Comment by yyyc514** [comment]
> JSON doesn't have comments in it's spec since it is just a representation of data. 

@sourrust Perhaps you're being a little too literal here?  Our XML syntax currently covers:

```
['html', 'xhtml', 'rss', 'atom', 'xjb', 'xsd', 'xsl', 'plist', 'wsf'],
``` 

While I think some of those things are truly XML, HTML is for sure not, and that's a pretty HUGE discrepancy.  Much larger than JSON vs JSONC in my opinion.


> If you want comments to be highlighted, it is probably best to just use javascript instead of JSON.

Except the Javascript syntax does a much worse job of highlighting JSON because that's not what it was intended for.

---

Any chance your opinion on this one has changed or we'd be more open to this now than we were in 2014?

**Comment by egor-rogov** [comment]
I also can't see any reason for not allowing comments in JSON. It won't break highlighting of valid JSON, and will help other purposes.

**Comment by marcoscaceres** [comment]
Agree.

**Comment by joshgoebel** [comment]
I think this would be a welcome addition.

**Comment by tobiu** [comment]
json5 support is indeed needed.
