### ISSUE TITLE
[Request] Support multiple lines of content

### ISSUE THREAD

**Issue by kueiyu** [highlightjs/highlight.js#4083]
**Is your request related to a specific problem you're having?**
I'm consistently frustrated by newline characters (like `\n`) within my JSON values. While Highlight.js automatically adds a comma afterward, it's often misplaced, appearing visually detached and near the top-right corner. This seems to occur because the comma is treated as separate from the text content.

**The solution you'd prefer / feature you'd like to see added...**
Could the comma be placed within the text content to correct its position? I understand this might result in the comma sharing the same color as the text, but it would be more visually appealing than a seemingly floating quote mark.

**Additional context...**
<img width="587" alt="Screenshot 2024-07-25 at 9 59 24 PM" src="https://github.com/user-attachments/assets/2098fc8e-42cf-4588-8b74-a5664e03013f">

**Comment by joshgoebel** [comment]
> While Highlight.js automatically adds a comma afterward

Highight.js does not rewrite/modify content and we do not use any positioning CSS.   I'd suggest perhaps using your browsers inspector tools to find out more about what is happening.

**Comment by kueiyu** [comment]
I see, thank you for the response.  I will close the request 👍

**Comment by Timmatt-Lee** [comment]
@kueiyu i think this request is still valid. so i use inspector and know what's going on.
Basically, highlight.js is doing a simple thing
create a `display:inline` block and start putting things, all the content alignment is only rely on `display:inline`
1. put a `{\n` in the begining
2. put the first key, in your example `"data"`
3. put the colon `:` afterwards
4. put the content, in your case, a string, and that string will be put into a flex-box, but that's not the point here
5. finally, put a comma `,` if needed.

and the feature request is to put the comma `,` to the right place
since the step 4, if user's string contain line-break symbol, (say `\n`), the step 4's content will have multiline
then the comma should be placed to the end of the line of step 4, instead of the first line of it
well, that's because the nature of outer-box's `display:inline`, so the comma will just stay there.

So @joshgoebel, i think we can use some css to support if user has multi-line content, the comma will still place to the correct position. wfyt? 😇

**Comment by joshgoebel** [comment]
> display:inline
>  will be put into a flex-box

This is not CSS from our library.  We use a very simple preamble:

```
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}

code.hljs {
  padding: 3px 5px;
}
```

If you can _create a jsfiddle showing this is an issue with our core library_ I'd be happy to take another look, but I can't help you with whatever custom CSS you are using that seems to be breaking things.

**Comment by joshgoebel** [comment]
Here is a simple JSFiddle you can add your code to.

https://jsfiddle.net/ajoshguy/5Lkwrgea/5/

**Comment by kueiyu** [comment]
Hi joshgoebel,

Thank you for providing the jsfiddle. It helped me to discover that the issue stemmed from my use of `display: inline-flex` on the `.hljs-string` class to improve JSON display. This inadvertently caused the comma misplacement. Your jsfiddle was instrumental in debugging this.

Thank you for your assistance! I will close this request.

**Comment by joshgoebel** [comment]
Glad to help!
