### ISSUE TITLE
GitHub theme highlighting is wrong

### ISSUE THREAD

**Issue by shner-elmo** [highlightjs/highlight.js#4089]
Hey, I was trying the `github` theme on the website playground, but when I compare it to the code in the README on Github, its not exactly the same:
![image](https://github.com/user-attachments/assets/5ce8b699-d56b-4de8-8bbd-763c96a2dfe3)

And [on GitHub](https://github.com/shner-elmo/TradingView-Screener/blob/master/README.md):
![image](https://github.com/user-attachments/assets/c355b943-c49a-4a57-9f1f-ac8ab96dce99)

---

Interestingly, when the language is set on '(auto)', the output is slightly close to GitHub's highlighting:
![image](https://github.com/user-attachments/assets/60f7eb19-65ac-43ca-999c-7ba2132d150a)

## Expected Behaviour

The class (or namespace that sharts with uppercase) should be highlighted, and the method should also be highlighted.

**Comment by shner-elmo** [comment]
[Highlight.js demo link](https://highlightjs.org/demo#lang=&v=1&theme=github&code=ZnJvbSB0cmFkaW5ndmlld19zY3JlZW5lciBpbXBvcnQgUXVlcnksIGNvbAoKKMUNKCkKIC5zZWxlY3QoJ25hbWUnLCAnY2xvc8UJdm9sdcYTcmVsYXRpdmVfxhNfMTBkX2NhbGMnxEB3aGVyZSgKIMQBY29sKCdtYXJrZXRfY2FwX2Jhc2ljJykuYmV0d2VlbigxXzAwMMQELCA1xQjEBCksyz3aayA%2BIDEuMswsTUFDRC5tYWNkxB09yxRzaWduYWzkAJ7kAKFvcmRlcl9ieSjqANJhc2NlbuQBKT1GYWxzZcUmZmZzZXQoNcQMbGltaXQoMsUMZ2V0X3NjYW5uZXJfZGF0YSgpKQ%3D%3D)

**Comment by joshgoebel** [comment]
We may classify some things entirely differently (in general) than GitHub, so there will never be an exact match.  Also different grammars sometimes classify things differently - so in one grammar `if` is a built-in, in another it's a `keyword`... so themes can look very different depending on the language you pick.  Not optimal, but it's legacy.

Also Github's own theme has changed across time as well, so that could be another issue here.

Also I'm not sure our Python grammar supports attributes/properties (ie, `some.property`)... so that might explain why it's so boring.

**Comment by joshgoebel** [comment]
Would you ilke to work on this issue?  Since GitHub themes change over time I'm going to close this if no one is actually wanting to fix it...  It's possibly not even wrong so much as "classic", etc... plus the other things I mentioned before - about never matching exactly etc.

If you want to work on it, we can re-open it.
