### ISSUE TITLE
Render codes line by line

### ISSUE THREAD

**Issue by Aimeast** [highlightjs/highlight.js#424]
I am writing a project that use `highlight.js` render code, but some code to be split line by line. result in some html mark not closure.

e.g, `hljs.highlight('cpp','/*aa\nbb\ncc*/').value` output (version 8.0)

``` text
<span class="hljs-comment">/*aa
bb
cc*/</span>
```

But I hope the result is

``` text
<span class="hljs-comment">/*aa</span>
<span class="hljs-comment">bb</span>
<span class="hljs-comment">cc*/</span>
```

**Comment by tomasreimers** [comment]
@isagalaev , any advice on how to do this now that the continuation argument has been removed? https://github.com/highlightjs/highlight.js/blob/main/CHANGES.md

**Comment by joshgoebel** [comment]
See the wiki. There are line number plugins. 

For a more specific answer:  

https://stackoverflow.com/questions/64280814/how-can-i-correctly-highlight-a-line-by-line-code-using-highlight-js-react

Ie, parse the HTML and generate proper line by line fragments.

**Comment by tomasreimers** [comment]
@joshgoebel , thank you for the quick response!

I'm not asking with the intention of implementing line numbers, I'm asking because I would like to be able to better style my code (specifically I have a diff view, and I would like to not render parts of the content which weren't changed, however those parts may be necessary context for the parser to highlight appropriately). 

The line number plugins I've looked at seem to run counter to the advice of your StackOverflow post. For example, the first two results on Google (as well as the others from what I've seen), 
 * https://github.com/wcoder/highlightjs-line-numbers.js/blob/master/src/highlightjs-line-numbers.js
 * https://bellido.us/blog/07-06-2014-Adding-LineNumbers-highlight-js.html
Both just break on newline and then place those in their own elements, which will cause issues if you have a styling span that runs across multiple lines (if I'm understanding your post correctly). So I don't particularly want to follow the same pattern.

Re the suggestion in your StackOverflow post, I could parse the generated HTML, but I guess it feels a little counter-intuitive to me to go code -> AST -> syntax tree (or AST with syntax highlights attached) -> DOM -> HTML string -> syntax tree -> DOM -> HTML string. I liked the idea of the emitter API, but if I'm going to build on an internal API I may as well just use the continuations the way is advocated for above in this thread (however, from what I can tell this API seems discouraged for public use): https://github.com/highlightjs/highlight.js/blob/main/src/highlight.js#L183

I'm more than happy to extend / contribute here, I am just trying to get a handle on the design decisions made so I know what makes the most sense. Specifically, why did you dislike the continuations API, what if the continuation were opaque to the user? Would it still be bad?

**Comment by tomasreimers** [comment]
(Continued https://github.com/highlightjs/highlight.js/issues/3303 so that we didn't need to discuss in a closed issue)

**Comment by joshgoebel** [comment]
> The line number plugins I've looked at seem to run counter to the advice of your StackOverflow post.

I make no guarantee that any particular plugins are doing it the "correct" way. :-)  I pointed to that post only as a canonical timeless solution if one TRULY needs line by line HTML. One that has likely worked in years past and will continue to work in years to come - as it depends on nothing special.

**Comment by coyotte508** [comment]
Here's our implementation in Typescript:

```ts
hljs.addPlugin({
  "after:highlight": (params: { value: string; }) => {
    const raw = params.value;
    let processed = "";
    let index = 0;
    const openTags: string[] = [];
    
    while (1) {
      const nextMatch = /(<span [^>]+>)|(<\/span>)|(\n)/.exec(raw.slice(index));
      
      if (!nextMatch) {
        params.value = processed + raw.slice(index);
        return;
      }
      
      const regexStart = index + nextMatch.index;
      const regexEnd = regexStart + nextMatch[0].length;
      
      if (nextMatch[0] === "\n") {
        processed += raw.slice(index, regexStart) + "</span>".repeat(openTags.length) + "\n" + openTags.join("");
      } else if (nextMatch[0] === "</span>") {
        processed += raw.slice(index, regexEnd);
        openTags.pop();
      } else {
        /// <span ...>
        processed += raw.slice(index, regexEnd);
        openTags.push(nextMatch[0]);
      }
      
      index = regexEnd;
    }
  },
});
```

Note that depending on the function you call, you may want to use `after:highlightBlock` or `after:highlightElement` instead.

Or you can just call the function on the output.

Then you can split the result with `\n`
