### ISSUE TITLE
Tabs width

### ISSUE THREAD

**Issue by Vad1mo** [highlightjs/highlight.js#508]
I am happy using TABs, so I do not want to replace a TAB with spaces, but what I would like to is to change the TAB width, Currently a TAB is around 8 spaces. I would like to have a TAB which is 4 spaces.

Any way I can achieve this?

**Comment by dbigham** [comment]
Just tried this -- what I'm finding is that the tabs in my top-of-function comments aren't replaced and thus still show up in the browser width width 8.

**Comment by lukehatfield** [comment]
My tabs aren't getting replaced either. Here's my initialization.
```
$(document).ready(function () {
    hljs.configure({tabReplace: '    '});
    hljs.initHighlighting();
});
```

**Comment by dbigham** [comment]
FYI, I got around this by converting tabs to spaces on the server and not
having Highlight.js do the conversion.

Remember that this conversion is actually quite tricky, because in code
comments where this is non-whitespace to the left of the tabs, the number
of spaces that a tab should be replaced with depends on what is to the left.

**Comment by logicplace** [comment]
Strange, the configure worked for me but I'm using hljs.highlightBlock directly instead of initHighlighting, not sure if it makes a difference.

Alternatively, there is a CSS3 attribute for this now: http://www.w3schools.com/cssref/css3_pr_tab-size.asp

**Comment by lukehatfield** [comment]
Thanks all. Love the CSS3 fix. That'll keep me going for now.
