### ISSUE TITLE
Problem with background-blend-mode in CSS

### ISSUE THREAD

**Issue by pepelsbey** [highlightjs/highlight.js#544]
For some reason `-blend-mode` is out of `hljs-attribute` scope:

```
background-image: url(images/sample.png);
background-color: red;
background-blend-mode: multiply;
```

```
<span class="hljs-attribute">background</span>-blend-mode<span class="hljs-value">: multiply;</span>
```

![screen shot 2014-08-16 at 20 14 25](https://cloud.githubusercontent.com/assets/105274/3942699/9b21c70e-2571-11e4-82c4-6497af26f179.png)

**Comment by isagalaev** [comment]
Nominating it for the next release as I believe we should do something with it anyway. Be it a temporary solution or a full one.

**Comment by isagalaev** [comment]
As it happens, the idea of how to fix it came to me when I was trying to properly describe how it cannot be fixed right in this very comment form… Still feeling a little shocked :-)

Anyway, the upside of it is that rules are now allowed on the top of CSS, not only within `{ .. }`, and detection doesn't seem to be broken.

**Comment by seven-phases-max** [comment]
Btw. the change in v8.5 certainly does the trick but only partially. In fact it breaks `tag:pseudo-selector` detection. See [demo-8.5](http://codepen.io/seven-phases-max/pen/NPZWrX?editors=100) vs. [demo-8.4](http://codepen.io/seven-phases-max/pen/QwXWEm?editors=100). Should I open new issue?

(the reason is obvious: no grammar difference between `tag:pseudo-selector` and `property:value` out of context).

**Comment by isagalaev** [comment]
Yeah, that is definitely a problem. Should think some more…

**Comment by yyyc514** [comment]
> Otherwise every curly-brace based syntax tends to look very similar to CSS. I'm still not sure how to better fix this, I'll keep thinking.

I think if you added a match for RULE (deep copied) at the top level but dropped it's relevancy scores to 0... you'd be able to match CSS property lists without CSS "claiming" any victims in the auto-detect game.  It'd also be pretty much impossible to auto-detect properties only CSS though, so they'd constantly end up as JSON or YAML or whatever else they were similar to.

**Comment by yyyc514** [comment]
If you're wanting a fix just for yourself I'd consider what I just suggested... and make sure you explicitly label your blocks CSS.

I just tried VS Code just now and even it can't properly colorize CSS "out of context".  If you had a blog or somewhere where you constantly were posting such things I'd almost suggest you whip up your own `cssprops` grammar just for this usage.

Closing because it's really impossible to resolve this while keeping auto-detect in mind.

Also just wrapping the whole thing in {} without a selector even seems to work if you were willing to change your snippets:

```css
background-image: url(images/sample.png);
background-color: red;
background-blend-mode: multiply;
```
