### ISSUE TITLE
Java generics are turned into xml tags

### ISSUE THREAD

**Issue by s17t** [highlightjs/highlight.js#628]
Hi,
 as shows in [this jsfiddle](http://jsfiddle.net/90y463m7/) 8.3 version can't highlight Java generics. Generics are turned into xml.

**Comment by JorgeCastilloPrz** [comment]
Hi @isagalaev, we are having this issue again in latest reveal js versions. We can't write any code snippet neither in markdown or html that contains generics (e.g: java or kotlin). It swallows them unless we manually add `&lt;` and `&gt`, which is suspicious because that was working by itself (without the need to replace the `<` `>` characters by the html representations) until not long ago.
