### ISSUE TITLE
Monokai themes don't highlight JSON right

### ISSUE THREAD

**Issue by thewarpaint** [highlightjs/highlight.js#669]
The Monokai themes do not highlight the JSON format right. The second-level braces and quotes for keys do not appear white as they should. I attach two screenshots taken from [the official demo](https://highlightjs.org/static/demo/): 

![Monokai](https://cloud.githubusercontent.com/assets/1839208/5348054/52c538f8-7ef2-11e4-9f14-0dbab450266d.png)
![Monokai Sublime](https://cloud.githubusercontent.com/assets/1839208/5348055/52cad560-7ef2-11e4-8161-1992c0e27f71.png)

**Comment by danelkhen** [comment]
I think that the term JSON in my title has thrown you off. Cuz I'm not sure what you mean by "use javascript". I am using highlight.js in javascript mode, and it colors it wrong. That's all I'm trying to say. Let me ask it another way - is there a way in highlight.js to make my valid code be to be highlighted correctly?

**Comment by sourrust** [comment]
Right, I was stuck in the that mindset because this issue is about JSON.

So I'm guessing you are using autodetection and the language highlight.js is choosing is JSON? The way you specify a language is:

```html
<pre><code class="javascript">...</code></pre>
```

That autodetection error might have been fixed in a later versions than what you are using because 8.4 and the master branch doesn't detect the snippet as JSON.

If this isn't your problem, can you make a separate issue? With this new information, your possible bug has nothing to do with the original issue.

**Comment by danelkhen** [comment]
I think I tried it, but I'll double check and get back to you. Thanks!

**Comment by danelkhen** [comment]
You're right, it has detected it as css instead of js. Seems to render fine when explicitly setting class='javascript'
Thanks!
