### ISSUE TITLE
Templating language tags in javascript strings break syntax highlighting

### ISSUE THREAD

**Issue by dotandimet** [highlightjs/highlight.js#725]
When trying to implement syntax highlighting for Mojolicious templates ([highlight.js pull request](https://github.com/isagalaev/highlight.js/pull/722), [mojo pull request](https://github.com/kraih/mojo/pull/737)), we found that highlight.js can't handle template tags inside javascript strings.

![mojolicious example](https://cloud.githubusercontent.com/assets/95891/5992924/7c0374e4-aa46-11e4-8462-9aee6a1df6b4.png)

This problem also shows up with the ERB syntax (which I used as reference):
![ERB example](https://cloud.githubusercontent.com/assets/95891/5992925/7c057a64-aa46-11e4-94a5-f22e56e50140.png)

It doesn't happen with PHP tags, which are handled internally in the **xml.js** language definition:

![PHP example](https://cloud.githubusercontent.com/assets/95891/5992923/7c011dfc-aa46-11e4-8360-33446debf24b.png)

I suspect this can only be fixed in xml.js, not by modifying an external language definition.

**Comment by isagalaev** [comment]
Good catch, thanks! I'll look into it as time allows but it might prove to be a real tough one…

**Comment by zicai** [comment]
same problem,when i use mustache tag {{  and }}  

in markdown:
[https://github.com/zicai/zicai.github.com/blob/master/_posts/2015-03-08-mustache-intro.md](https://github.com/zicai/zicai.github.com/blob/master/_posts/2015-03-08-mustache-intro.md)

![md1](https://cloud.githubusercontent.com/assets/2225683/6589463/5fb2fdac-c7db-11e4-8bc6-a16153439541.png)

with highlight.js
[http://zicai.github.io/lessons/2015/03/08/mustache-intro/](http://zicai.github.io/lessons/2015/03/08/mustache-intro/)
![md2](https://cloud.githubusercontent.com/assets/2225683/6589465/6d0a403c-c7db-11e4-9977-b96095415828.png)

the words in {{ and }}  are missing

**Comment by isagalaev** [comment]
Removing 8.8 as it is indeed proving to be a tough one.

P.S. @zicai: the issue you mentioned has absolutely nothing to do with the original one. Moreover, it's not a scripting issue at all as those missing words are already missing from your HTML source.

**Comment by dajocarter** [comment]
@zicai If you need the mustache tags {{ }} to render, try wrapping them in `{% raw %} {% endraw %}`.
http://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll

**Comment by codestitch** [comment]
@zicai - it didn't work. it only displays {% raw %} {{data.id}} {% endraw %}

**Comment by swatilk** [comment]
The issue with escaping two curly braces  {{ }} still exists. Anyone know of a solution?

**Comment by lobo-tuerto** [comment]
I just stumbled into this one too.
In my case I'm working with a **Vue.js** app, the fence code that is throwing the error is:

```html
<template lang="pug">
v-app
  v-toolbar
    v-toolbar-title {{ $static.metaData.siteName }}
    v-spacer
    v-toolbar-items
      v-btn(flat exact :to="{ name: 'home' }") Home
      v-btn(flat :to="{ name: 'about' }") About

  v-container
    slot
</template>


<static-query>
query {
  metaData {
    siteName
  }
}
</static-query>
```

The error I'm seeing when enabling **hljs** inside **markdownit** is:

```bash
 ERROR  [Vue warn]: Error in render: "TypeError: Cannot read property 'metaData' of undefined"
```

When **hljs** is disable then no errors are thrown.

**Comment by lobo-tuerto** [comment]
It's as if it was trying to parse and execute the code inside **{{ }}**.

**Comment by lobo-tuerto** [comment]
This is related to Vue.

Solved by changing the **hljs** invocation from this:

```js
hljs.highlight(lang, str).value
```

To this:

```js
let highlighted = hljs.highlight(lang, str).value
highlighted = highlighted.replace(/{{(.*)}}/g, '{{ "\\{\\{$1\\}\\}" }}')
return highlighted
```

**Comment by marcoscaceres** [comment]
There I an alternative Vue language definition that might help  (I've not tried  it):   https://github.com/highlightjs/highlightjs-vue

**Comment by yyyc514** [comment]
I think this problem is misstated (or at the very least oversimplified):

> Templating language tags in javascript strings break syntax highlighting

The reason this doesn't work is because template tags are NOT Javascript. :-)  _I'm not sure you should actually expect this to work IMHO._  I'm not sure it's so great we added automatic PHP support to xml, though I guess that ship has sailed. :-)  There is also a cost here.  Now you can't build a working Hightlight.js with "xml" without bundling "php" as well, although perhaps the parser just quietly ignores missing languages.

But if that's the case I'm not sure how it can ever properly detect the END of the templating, since it can't know about any escaping being using inside it (ie):

```html
<h1>
I'm just a <%= "HAPPY %>" bunch of more Ruby code here that isn't html %>
</h1>
```

Although I guess if you weren't actually using that templating engine then it wouldn't so much matter if it silently failed and also never matched.

---

The real problem is many (all?) template engines are generic.  You can use ERB with JS, HTML, XML, JSON, CoffeeScript, and much more... so if we're going to add to one, we need to add to all - or we need to understand clearly why JS is such an exception compared to the others. AFAIK, ERB is more commonly used with HTML than JS - so if JS is an exception I think HTML would be a larger exception.

**IE, this is NOT just an issue with the Javascript parser, and shouldn't be though of as such.**  Again, unless we first define why it's such an exception vs the other cases.  We made need a better way to think about templating engines in general.

Perhaps it'd be best to flag a snippet as "php/html".... or "erb/js"...

**Comment by yyyc514** [comment]
Since most major template engines "trump everything" (ie, the "start" macros can show up literally anywhere) perhaps there is some built-time option we could add to say "compile highlight.js with ERB support"... and then magically you can just toss ERB in the middle of any language - and it will "just work"...  If you look closely you can see even say the built-in support for PHP starts to fail if you look at edge cases, like PHP inside attribute strings... which should definitely be possible... you should be able to break in anywhere:

```
![Screen Shot 2019-10-06 at 1 25 31 AM](https://user-images.githubusercontent.com/6473/66264688-4fd7b680-e7d8-11e9-8957-4d963c52455e.png)
```

**Comment by yyyc514** [comment]
I forgot (well, actually I never know) that in our own repo we have example of how you'd actually do this correctly, such as VBScript-HTML:

```
function(hljs) {
  return {
    subLanguage: 'xml',
    contains: [
      {
        begin: '<%', end: '%>',
        subLanguage: 'vbscript'
      }
    ]
  };
}

```

**Comment by yyyc514** [comment]
@dotandimet You still around?  I think what you want is your own language that's defined similar to the VBScript/HTML language.   It's a bad idea (and simply not practical) to add every possibly templating language under the sun to `xml`.  Adding PHP to `xml` in the past was probably short-sighted without considering what that would look like long-term.

Also it becomes almost impossible when as soon as have different templating languages that share similar syntaxes... (it looks like ERB and Mojolicious are very similar).  Having a separate language per templating engine removes all the ambiguity.

**Comment by yyyc514** [comment]
Closing as asked and answered and lack of activity.
